XiaoMi/rdsn

src/dist/replication/meta_server/meta_backup_service.cpp, src/dist/replication/meta_server/meta_backup_service.h, src/dist/replication/test/meta_test/unit_test/backup_test.cpp
fix incorrect usage of `std::chrono::seconds` in option `block_retry_delay_ms` & use chrono literal to replace uint64_t to represent time
=> meta_backup_service: fix incorrect usage of std::chrono::seconds

src/dist/replication/test/simple_kv/case-603.act
case 603 has too strict constraint for replica status, give it a
looser one
=> replication_test: fix case 603

include/dsn/tool-api/uniq_timestamp_us.h, src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_2pc.cpp, src/dist/replication/lib/replica_init.cpp
Reimplement this for 2 reasons:
1. All threads shared a lock in the old implementation, which was
not friendly to performance. As a matter of fact, it's not necessary
for different replicas to keep an global increasing timestamp, so we
can try this optimization
2. Although the timestamp was replicated to secondaries from primary,
timestamp value of secondaries never updated accordingly, for which reason
we were exposed to the risks that a newer mutation may had smaller timestamp
if primary switched.
=> replica_server: reimplement uniq_timestamp generator

include/dsn/c/api_utilities.h, include/dsn/dist/replication/replication_app_base.h, include/dsn/utility/strings.h, src/apps/skv/simple_kv.server.impl.h, src/core/core/service_api_c.cpp, src/core/core/strings.cpp, src/dist/replication/client_lib/replication_common.cpp, src/dist/replication/client_lib/replication_common.h, src/dist/replication/ddl_lib/replication_ddl_client.cpp, src/dist/replication/lib/replica.cpp, src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_config.cpp, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h, src/dist/replication/meta_server/server_state.cpp, src/dist/replication/test/simple_kv/simple_kv.server.impl.h
Replication_service_app's envs can be updated by config_sync, which is useful when we want to adjust parameters of storage engine without updating server's configuration. A typical usage is "bulk load", in which case storage engine is adjusted firstly for better writing throughput, then for better reading latency.
=> replica_server: support update_app_envs by config sync

src/dist/replication/meta_server/server_load_balancer.cpp, src/dist/replication/meta_server/server_load_balancer.h
add black list in simple_load_balancer, so as to
skip some nodes when adding secondary, which is very
useful for offline some nodes
=> simple_load_balancer: support black list

include/dsn/c/api_utilities.h, include/dsn/service_api_cpp.h, include/dsn/tool-api/task_spec.h, include/dsn/tool-api/uri_address.h, include/dsn/utility/config_api.h, include/dsn/utility/config_helper.h, include/dsn/utility/configuration.h, src/core/core/config_api.cpp, src/core/core/configuration.cpp, src/core/core/global_config.cpp, src/core/core/perf_test_helper.cpp, src/core/core/rpc_engine.cpp, src/core/core/rpc_engine.h, src/core/core/service_api_c.cpp, src/core/core/service_engine.cpp, src/core/core/service_engine.h, src/core/core/uri_address.cpp, src/core/tests/clientlet.cpp, src/core/tests/configuration.cpp, src/core/tests/service_api_c.cpp, src/dist/replication/meta_server/server_state.cpp, src/tools/repli/repli.app.cpp, src/tools/repli/repli.main.cpp
1. move configuration related APIs from c interface to utility,
2. add comments for these APIs
3. remove API: dsn_config_dump
=> configuration: refactor configuration related APIs

include/dsn/utility/config_api.h, src/core/core/config_api.cpp
this API is mistakenly removed from last pr due to merge from a old commit.
=> configuration: add dsn_config_get_value_int64 back

include/dsn/dist/replication/meta_service_app.h, include/dsn/dist/replication/replication_service_app.h, src/apps/skv/CMakeLists.txt, src/apps/skv/simple_kv.main.cpp, src/dist/replication/lib/CMakeLists.txt, src/dist/replication/lib/replication_service_app.cpp, src/dist/replication/meta_server/meta_service_app.cpp, src/dist/replication/test/meta_test/unit_test/main.cpp, src/dist/replication/test/replica_test/unit_test/CMakeLists.txt, src/dist/replication/test/simple_kv/CMakeLists.txt, src/dist/replication/test/simple_kv/simple_kv.main.cpp, src/tests/dsn/CMakeLists.txt, src/tools/repli/CMakeLists.txt
1. rename initialization functions of replica_server/meta_server
as the feature of loading shared library when running process
has removed
2. rename dsn_layer2_stateful_type1 to dsn_replica_server
3. small refactor on meta_server's components init procedure
=> replication: some rename refactors

include/dsn/cpp/json_helper.h, src/core/tests/json_helper_test.cpp
现在 json_helper 不支持把 json 序列化到 const 对象里. 比如下面代码
```cpp
struct info {
const int a;
};
dsn::json::json_forwarder<info>::decode(json, decoded_info);
```
编译时会报错.
我们现在的很多代码选择不用 const 定义, 使得可读性比较差, 不注释的话看不出来变量会不会在某处被修改.
这个问题在代码复杂的场景尤其明显.
=> utils: support decoding json into a const object

include/dsn/c/api_utilities.h, include/dsn/cpp/json_helper.h, src/core/tests/json_helper_test.cpp
1. encode map's key to string, which is a requirement of json's standard
=> json_helper: bug fix

src/dist/replication/meta_server/meta_service.h, src/dist/replication/meta_server/meta_state_service_utils.cpp, src/dist/replication/meta_server/meta_state_service_utils.h, src/dist/replication/meta_server/meta_state_service_utils_impl.h, src/dist/replication/test/meta_test/unit_test/meta_state_service_utils_test.cpp
`get_children` wraps upon the original `meta_state_service::get_children` and exposing similar interface.
=> meta_server: introduce get_children for mss::meta_storage

src/dist/replication/meta_server/meta_service.cpp
因为json库重构造成对map<int,int>中key的序列化/反序列化方式发生变化。
原来：{1:1,2:2}
现在：{"1":1,"2":2}
为了避免兼容性带来的集群无法加载的问题，我们将backup policy在zookeeper上的存储节点路径换为一个新的路径。在升级集群时，需要将原集群的backup policy信息转换后写入到新路径中，将会提供专门的工具来做这件事情。
=> meta: change backup policy node on zookeeper to handle json compatibility

include/dsn/cpp/json_helper.h, include/dsn/dist/replication/duplication_common.h, src/core/core/perf_counters.cpp, src/core/tests/json_helper_test.cpp, src/core/tools/common/profiler_command.cpp, src/dist/replication/meta_server/meta_backup_service.cpp, src/dist/replication/meta_server/meta_data.h, src/dist/replication/meta_server/server_state.cpp, src/dist/replication/test/meta_test/unit_test/json_compacity.cpp
reimplement the json_encode/decode with rapidjson so that the json output will more closer to standard.
currently only one rule are disobey the standard: we encode "Bool" to "0/1", but not "True/False"
=> json: bug fix of json decode & encode

bin/compiler_info.cmake, bin/dsn.cmake
This PR is to fix the compilation error (occurred after this commit: https://github.com/XiaoMi/rdsn/pull/105/files) when building with clang:
```sh
➜  rdsn git:(master) ✗ ./run.sh build --compiler clang-3.9,clang++-3.9
...
Scanning dependencies of target dsn.core
[  1%] Building CXX object src/apps/cli/CMakeFiles/dsn.cli.dir/cli_types.cpp.o
[  1%] Building CXX object src/dist/failure_detector/CMakeFiles/dsn.failure_detector.dir/failure_detector.cpp.o
[  1%] Building CXX object src/apps/nfs/CMakeFiles/dsn.nfs.dir/nfs_client_impl.cpp.o
[  1%] Building CXX object src/core/tools/hpc/CMakeFiles/dsn.tools.hpc.dir/fastrun.cpp.o
[  2%] Building CXX object src/core/tools/common/CMakeFiles/dsn.tools.common.dir/asio_net_provider.cpp.o
[  3%] Building CXX object …
```
=> scripts: fix clang warning due to ccache

include/dsn/utility/defer.h
`defer` is an useful util to implement RAII semantic in golang, much alike `try...finally...` in java. In C++ we used to implement an RAII class wrapping around the resource:
```cpp
struct object_raii 
{
object_raii() {
_obj = c_object_new();
}
~object_raii() {
c_object_free(_obj);
}
private:
c_object *_obj;
};
```
Now with defer, things will be simplified: 
```cpp
c_object *obj = c_object_new();
auto cleanup = dsn::defer([obj]() { c_object_free(obj); });
```
=> utility: add defer

include/dsn/c/api_utilities.h, include/dsn/utility/autoref_ptr.h, include/dsn/utility/endians.h, src/core/tools/common/asio_net_provider.cpp, src/core/tools/common/asio_rpc_session.cpp, src/core/tools/common/thrift_message_parser.cpp
to fix #114 
原因是：在asio_network_provider::do_accept()中，新建的asio_rpc_session的构造函数中，调用了start_read_next()，进一步调用 asio_rpc_session::do_read()：先add_ref()，如果立即调用回调函数，会release_ref()，如果该release_ref()发生在构造函数返回之前，这个新建的对象asio_rpc_session就会被立即析构。在构造函数返回之后，do_accept()中继续持有和使用该对象，就会造成double free。
解决办法：asio_rpc_session的构造函数中不调用start_read_next()，而是在对象创建完成后，在外面调用start_read_next()。
=> rdsn: fix asio_rpc_session bug which may cause double free

include/dsn/tool-api/network.h, src/core/core/network.cpp, src/core/tools/common/asio_rpc_session.cpp, src/core/tools/common/asio_rpc_session.h, src/core/tools/common/network.sim.cpp, src/core/tools/common/network.sim.h, src/core/tools/hpc/hpc_network_provider.bsd.cpp, src/core/tools/hpc/hpc_network_provider.h, src/core/tools/hpc/hpc_network_provider.linux.cpp, src/core/tools/hpc/hpc_network_provider.win.cpp
1. adjust name and position of some functions in rpc session
2. rename "close_on_fault_injection" to more general "close"
3. delete a useless function
=> rpc_session: do some refactor

include/dsn/perf_counter/perf_counter.h, include/dsn/perf_counter/perf_counter_utils.h, include/dsn/perf_counter/perf_counter_wrapper.h, include/dsn/perf_counter/perf_counters.h, include/dsn/tool-api/task_queue.h, include/dsn/utility/utils.h, src/core/core/utils.cpp, src/core/perf_counter/builtin_counters.cpp, src/core/perf_counter/builtin_counters.h, src/core/perf_counter/perf_counter.cpp, src/core/perf_counter/perf_counter_atomic.h, src/core/perf_counter/perf_counters.cpp, src/core/tests/perf_counter.cpp, src/core/tests/perf_counters.cpp
1. change the value type of perf counters from unsigned to signed
2. move the feature take_snapshot/query_snapshot/query_counter_by_regexp
from pegasus to rdsn, so as to support other executables to use these
features conveniently
3. remove the useless query_counter interfaces in perf_counters
4. add some unit tests
=> perf-counter: bug fix & refactor

include/dsn/utility/blob.h
- `blob::create_from_bytes`: Support zero-copy construction of blob based on implementation 
https://github.com/XiaoMi/pegasus/blob/master/src/base/pegasus_value_schema.h#L55
- In addition we also support a copy-version of `blob::create_from_bytes`, which memcpy an allocated `char*` into the buffer of blob. This is widely used in rDSN (cases: [fds_service.cpp](https://github.com/XiaoMi/rdsn/blob/master/src/dist/block_service/fds/fds_service.cpp#L699), [thrift_message_parser.cpp](https://github.com/XiaoMi/rdsn/blob/master/src/core/tools/common/thrift_message_parser.cpp#L128)) but not generalized as utility.
=> utility: refactor on blob

include/dsn/utility/safe_strerror_posix.h, include/dsn/utility/utils.h, src/core/core/build_config.h, src/core/core/filesystem.cpp, src/core/core/safe_strerror_posix.cpp, src/core/core/utils.cpp
1. fix thread safety problem of strerror
2. remove source code for windows
=> filesystem: bug fix & code refactor

include/dsn/tool-api/rpc_address.h, include/dsn/utility/strings.h, src/core/core/rpc_address.cpp, src/core/core/strings.cpp, src/dist/block_service/local/local_service.cpp, src/dist/block_service/local/local_service.h, src/dist/replication/common/replication_common.cpp
1. modify the cold backup path from checkpoint@a.b.c.d:port to chkpt_a.b.c.d_port, as old format not valid in hdfs
2. implement meta_data's query interface for local block service. in order to support meta-data querying, a small metadata file is added for each real file.
=> cold_backup: some bug fix to support hdfs-fuse as storage media

CMakeLists.txt, bin/dsn.cmake, run.sh, scripts/linux/build.sh, src/apps/skv/CMakeLists.txt, src/core/tests/CMakeLists.txt, src/dist/nfs/test/CMakeLists.txt, src/dist/replication/test/meta_test/balancer_simulator/CMakeLists.txt, src/dist/replication/test/meta_test/unit_test/CMakeLists.txt, src/dist/replication/test/replica_test/unit_test/CMakeLists.txt, src/dist/replication/test/simple_kv/CMakeLists.txt, src/tests/dsn/CMakeLists.txt
Support build without building unit test. By default rDSN always builds everything.
```
./run.sh build --notest
```
With this feature the total build time of rDSN was reduced from "3m 44s" to "2m 16s" on my PC.
It will be beneficial for low-end machine (eg. laptop or vm on travis-ci), and building unit test of rdsn in pegasus's CI can be avoided.
=> misc: reduce build time

include/dsn/c/api_layer1.h, src/core/core/disk_engine.cpp, src/core/core/disk_engine.h, src/core/core/service_api_c.cpp
- remove the windows specific code
- remove `dsn_rpc_enqueue_response` since i don't find any places using it
- remove `disk_file::ctrl` and `disk_engine::ctrl` since they are not even implemented completely. We may reimplement this function when we need.
=> core: remove useless code

run.sh
This PR is to fix the mistakes I made on #170 that adds `shift` after parsing some options. I'm sorry for that.
=> scripts: revert "shift" on some options in run.sh

compile_thrift.py
Formerly in #167 we removed dsn.cg.sh and dsn.generate_code.php, which was used to generate the thrift files. Now we refactor compile_thrift.py to make it work.
btw, the script is formatted under pep8
```
$ ./compile_thrift.py 
thrift_exe = /home/mi/git/release/pegasus/rdsn/bin/Linux/thrift
root_dir = /home/mi/git/release/pegasus/rdsn
>>> compiling thrift file dsn.layer2.thrift ...
mkdir /home/mi/git/release/pegasus/rdsn/src/output
/home/mi/git/release/pegasus/rdsn/bin/Linux/thrift -gen cpp:moveable_types -out output dsn.layer2.thrift
mv output/dsn.layer2_types.h /home/mi/git/release/pegasus/rdsn/include/dsn/cpp/serialization_helper
mv output/dsn.layer2_types.cpp /home/mi/git/release/pegasus/rdsn/src/core/core
rm -rf /home/mi/git/release/pegasus/rdsn/src/output
>>> compiling thrift file …
```
=> scripts: refactor compile_thrift.py

src/dist/replication/common/replication_common.cpp, src/dist/replication/common/replication_common.h, src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_2pc.cpp, src/dist/replication/lib/replica_config.cpp
support to disable write on table by set environment variable on table:
```
>>> use temp
OK
>>> set_app_envs replica.deny_client_write true               // disable write
set app envs succeed
>>> set_app_envs replica.deny_client_write false              // enable write
set app envs succeed
>>> 
```
=> server: support to disable write on table

.travis.yml, compile_thrift.py, run.sh, scripts/linux/build.sh, scripts/linux/clear_zk.sh, scripts/linux/start_zk.sh, scripts/linux/stop_zk.sh, src/core/core/rpc_address.cpp, src/core/tests/run.sh, src/tests/dsn/distributed_lock_zookeeper.cpp, src/tests/dsn/restart_zookeeper.sh, src/tests/dsn/run.sh
主要改动点：
* 改进pegasus-thirdparty-prebuild，包含完整的依赖，譬如gflags
* 改进start_zk.sh，不再依赖thirdparty/src，避免在travis里面额外下载zookeeper
* 编译时不再下载bin/Linux/thrift，只在调用compile_thrift.py时按需要下载
=> scripts: improve build scripts

src/dist/failure_detector/failure_detector.cpp
pegasus issue [239](https://github.com/XiaoMi/pegasus/issues/239)
=> fd: fix failure detection bug

include/dsn/tool-api/command_manager.h, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h, src/dist/replication/meta_server/server_load_balancer.cpp, src/dist/replication/meta_server/server_state.cpp
to dynamically change `gc_disk_error_replica_interval_seconds` and `gc_disk_garbage_replica_interval_seconds`.
for the reason, please refer to: [垃圾文件夹管理](https://github.com/XiaoMi/pegasus/wiki/%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86#%E5%9E%83%E5%9C%BE%E6%96%87%E4%BB%B6%E5%A4%B9%E7%AE%A1%E7%90%86)
=> replica-server: support remote command useless-dir-reserve-seconds

src/core/tests/service_api_c.cpp, src/dist/replication/lib/mutation_log.cpp, src/dist/replication/lib/mutation_log.h, src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_backup.cpp, src/dist/replication/lib/replica_context.cpp, src/dist/replication/replication.thrift, src/dist/replication/test/simple_kv/case-402.act
to release storage resouces as soon as possiable.
=>  replica-server: remove checkpoint dirs when cold backup completed

include/dsn/dist/replication/replication_ddl_client.h, include/dsn/utility/absl/utility/utility.h, include/dsn/utility/output_utils.h, src/core/core/output_utils.cpp, src/dist/replication/ddl_lib/replication_ddl_client.cpp
```
A tool used to print data in a table form.
Example usage 1:
table_printer tp;
tp.add_title("table_title");
tp.add_column("column_name1");
tp.add_column("column_name2");
for (...) {
tp.add_row("row_name_i");
tp.append_data(int_data);
tp.append_data(double_data);
}
std::ostream out(...);
tp.output(out);
Output looks like:
table_title  column_name1  column_name2
row_name_1   123           45.67
row_name_2   456           45.68
Example usage 2:
table_printer tp;
tp.add_row_name_and_data("row_name_1", int_value);
tp.add_row_name_and_data("row_name_2", string_value);
std::ostream out(...);
tp.output(out, ": ");
Output looks like:
row_name_1 :  4567
row_name_2 :  hello
```
=> shell: refactor table data output method

.travis.yml, bin/dsn.cmake, scripts/linux/build.sh, thirdparty/build-thirdparty.sh
Previously:
Now:
There's one problem that travis doesn't have libunwind built in, and gperftools requires it as necessary. Therefore as a work round we disable gperf on travis. 
> For that reason, if you use a 64-bit system, we strongly recommend you                                                                                                                                      
install libunwind before trying to configure or install gperftools.                                                                                                                                         
libunwind can be found at    
> If you cannot or do not wish to install libunwind, you can still try
to use the built-in stack unwinder.  The built-in stack unwinder
requires that your application, the …
=> bugfix: link tcmalloc by default

include/dsn/dist/failure_detector/failure_detector.h, src/dist/failure_detector/failure_detector.cpp, src/dist/replication/meta_server/meta_options.cpp, src/dist/replication/meta_server/meta_options.h, src/dist/replication/meta_server/meta_service.cpp, src/dist/replication/meta_server/meta_service.h
**Implementation Notes**
[https://github.com/XiaoMi/pegasus/issues/238](url)
white list feature is implemented by using allow_list in failure detector.
**Assistant Tool**
we can use remote_command “meta.fd.allow_list” to query the replica white list in meta-server.
```
>>> remote_command -t meta meta.fd.allow_list
COMMAND: meta.fd.allow_list
CALL [meta-server] [xxx] succeed: get ok: allow list disabled.
```
or
```
>>> remote_command -t meta meta.fd.allow_list
COMMAND: meta.fd.allow_list
CALL [meta-server] [xxx] succeed: get ok: allow list enabled. list: x.x.x.x:xx, x.x.x.x:xx
```
we can control node_live_percentage_threshold_for_update by
` remote_command -t meta meta.live_percentage  [num | DEFAULT]`
=> meta: support white list of replica-servers & add remote cmd to ctrl live_percentage

include/dsn/dist/failure_detector/failure_detector.h, include/dsn/tool-api/network.h, src/core/tests/gtest.filter, src/dist/failure_detector/failure_detector.cpp, src/tests/dsn/CMakeLists.txt, src/tests/dsn/config-whitelist-test-failed.ini, src/tests/dsn/config-whitelist-test.ini, src/tests/dsn/failure_detector.cpp, src/tests/dsn/gtest.filter, src/tests/dsn/main.cpp, src/tests/dsn/run.sh
1. whitelist单测：为了白名单里的ip地址和worker的ip地址的获取方式统一，把network::get_local_ipv4()改为public
2.set_allow_list bug修复
3.dsn.core.tests单独提出tools_simulator，因为有些机器的dsn.core.tests顺序不一样，tools_simulator会影响perf_counters的query_snapshot_by_regexp测试
=> add unit test of whitelist & fix bug

include/dsn/dist/fmt_logging.h, include/dsn/tool-api/gpid.h, include/dsn/tool-api/task_code.h, include/dsn/utility/error_code.h, src/core/core/string_view.cpp, src/core/tests/string_view_test.cpp, src/dist/replication/common/CMakeLists.txt, src/dist/replication/common/test/CMakeLists.txt, src/dist/replication/common/test/config-test.ini, src/dist/replication/common/test/fmt_logging_test.cpp, src/dist/replication/common/test/main.cpp, src/dist/replication/common/test/run.sh
补充了 
```cpp
std::ostream &operator<<(std::ostream &o, string_view piece)
```
的实现（拷贝于 abseil），之前 string_view 是不支持 operator<< 的
=> utils: test format utilities

include/dsn/dist/replication/duplication_common.h, include/dsn/dist/replication/replication_ddl_client.h, src/dist/replication/common/duplication_common.cpp, src/dist/replication/common/test/duplication_common_test.cpp, src/dist/replication/ddl_lib/replication_ddl_client.cpp
This PR added these 3 ddl commands: **add_dup**, **query_dup**, **change_dup_status**, as well several utilities reside in `duplication_common.h/cpp`.
To configure a remote cluster for duplication, users need to set a unique **"cluster_id"** for it under **' [duplication-group]'** section:
```
[duplication-group]
wuhan-mi-srv-ad = 3
tianjin-mi-srv-ad = 4
``` 
The mapping of "cluster_name" to "cluster_id" is stored internally in class **`duplication_group_registry`**, which is a singleton. The implementation is hiding behind the pure function APIs to make our header more cleaner.
=> ddl_client: add duplication related commands

include/dsn/perf_counter/perf_counters.h, src/core/perf_counter/perf_counters.cpp
fix perf_counter_info::timestamp to the timestamp when perf_counters::take_snapshot()
=> fix perf_counter_info::timestamp

include/dsn/utility/hpc_locks/sema.h, src/core/core/message_utils.cpp, src/core/core/rpc_engine.cpp, src/core/core/rpc_message.cpp, src/core/tools/common/raw_message_parser.cpp, src/core/tools/common/thrift_message_parser.cpp, src/dist/replication/lib/replica_context.cpp, src/dist/replication/meta_server/meta_backup_service.h
1. fix invalid argument of sem_timedwait: 
```
rdsn/src/core/tests/sema.cpp:47: Failure
Value of: s.wait(10)
Actual: false
Expected: true
```
The bug is in this code: 
```
clock_gettime(CLOCK_REALTIME, &ts);
ts.tv_sec += timeout_milliseconds / 1000;
ts.tv_nsec += timeout_milliseconds % 1000 * 1000000;
```
ts.tv_nsec may be greater than 1000 million, but it's invalid. And it may cause the error "EINVAL", which errno is 22.
>        The following additional errors can occur for sem_timedwait():
>        EINVAL The value of abs_timeout.tv_nsecs is less than 0, or greater
>               than or equal to 1000 million.
>       <http://man7.org/linux/man-pages/man3/sem_wait.3.html>
2. fix compile warnings when using gcc 8.3.0
```
error: ‘char* strncpy(char*, const char*, size_t)’ output …
```
=> *:fix Semaphore bug & Compile warnings

src/dist/replication/meta_server/duplication/meta_duplication_service.h, src/dist/replication/meta_server/meta_data.h, src/dist/replication/meta_server/meta_service.cpp, src/dist/replication/meta_server/meta_service.h, src/dist/replication/meta_server/server_state.h
考虑到目前 code review 比较慢，我们这里把大 PR 做拆分，这样既方便大家通过，我也可以做更多解释。
1. 处理热备份 rpc 的类不是 meta_service，也不是 server_state，而是 **meta_duplication_service** （`_dup_svc`）。解耦之后代码会变得更干净。
2. 每个表的元信息 app_state 现在会多一个字段，叫 **duplications**，一个表可以有多个热备份，即一个集群可以热备到多个集群上。
3. 关于 `_meta_storage`。热备份的 zk 读写都是用 `mss::meta_storage` 实现的，它和 `meta_state_service`
最大的区别就是我们隐藏了错误重试的细节，精简了代码和逻辑。
这个工具类在 #83 #51 引入，但我们在当前 PR 才第一次使用。
=> duplication: add meta_duplication_service (part 0)

src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h
https://github.com/XiaoMi/pegasus/issues/319
=> fix too many ERR_BUSY logs problem when write throttling enabled

.gitignore, src/core/tools/common/thrift_message_parser.cpp, src/core/tools/common/thrift_message_parser.h
这里只是做一些小的代码重构，没有改任何逻辑，为后面的 PR 做准备：
- 把不必要的 virtual 删掉
- 补充注释
- 移动了几个函数的位置，把 thrift_messsage_parser 的实现分为  Request Parsing 和 
Response Encoding 两个部分，提升可读性
=> rpc: minor refactoring on thrift_messsage_parser

include/dsn/cpp/rpc_stream.h, include/dsn/tool-api/message_parser.h, src/core/core/message_parser.cpp, src/core/tests/message_reader_test.cpp
主要补充了 message_reader 的注释和单测，这个类是一个错误的设计被放在一个正确的地方。
它本质上是用来从数据流中读入数据的，和 message 没有关系，却被叫做 message_reader。
它可以类比 [sofa-pbrpc readbuffer](https://github.com/baidu/sofa-pbrpc/blob/master/src/sofa/pbrpc/buffer.h) 或者 [brpc IOBuf](https://github.com/apache/incubator-brpc/blob/master/src/butil/iobuf.h)，但实现非常粗糙，会产生较多内存拷贝，后续可以在此处进行优化。
rpc_write_stream 删除了一个构造函数，这个构造函数会造成内存泄漏，好在我们没有使用到它。
=> rpc: minor refactoring on message_reader

include/dsn/dist/replication/replication_ddl_client.h, include/dsn/utility/output_utils.h, src/dist/replication/ddl_lib/replication_ddl_client.cpp
- JSON output supported for `list_app` and `cluster_info`
- fix a bug in single `table_printer` object output in JSON
=> ddl_client: JSON output supported for list_app and cluster_info

.travis.yml, bin/dsn.cmake, src/core/core/fail_point.cpp, src/core/tests/CMakeLists.txt
C++14 has many advantages over C++11, and now it's fully mature for nearly three years. Besides, there's no difficulty for our current codebase to move onto C++14. What we need to do is to upgrade our least compiler support to gcc-5 (suggested GCC-5.5).
The first benefit is that we are no longer suffering from the bug of `std::regex` lib in gcc-4.9, so no need for `boost::regex` then.
New features introduced in C++14 can be found in https://www.wikiwand.com/en/C%2B%2B14, some by far are useful for us:
- `std::make_unique`: will replace `dsn::make_unique`
- user-defined literals: will replace `dsn/utility/chrono_literals.h`
=> use c++14 mode for compilation

src/core/core/network.cpp, src/core/tools/common/asio_rpc_session.cpp, src/core/tools/common/asio_rpc_session.h
Fixed https://github.com/XiaoMi/pegasus/issues/307. 
The core problem is when the socket is reading/writing, the other threads which encounter a network error will close that socket, and may cause its internal `descriptor_data` to be null, then the thread w/r using the wild pointer will coredump in this case.
The solution is to add write-lock on close and read-lock on r/w, so that will ensure thread-safety of the Boost-ASIO socket.
=> rpc: fix asio bug that causes coredump

include/dsn/utility/output_utils.h, src/core/core/output_utils.cpp, src/core/tests/output_utils_test.cpp
Shell aborts if the table's envs is empty.
```
>>> use mico_voip
OK
>>> get_app_envs -j
{
"app_envs"F2019-07-05 11:30:39.100 (1562297439100980327 0b4b)  mimic.io-thrd.02891: output_utils.cpp:59:json_encode(): assertion expression: false
F2019-07-05 11:30:39.100 (1562297439100992622 0b4b)  mimic.io-thrd.02891: output_utils.cpp:59:json_encode(): Unknown mode
./run.sh: line 1576:  2891 Aborted                 ./pegasus_shell ${CONFIG} $CLUSTER_NAME
```
Return immediately if the table has not data.
Tests 
- Unit test
- Manual test (add detailed scripts or steps below)
Related changes
- Need to cherry-pick to the release branch
- Need to be included in the release note
=> utils: fix a bug in table_printer and add several unit tests

src/dist/failure_detector/failure_detector.cpp
We reproduce failure detection bug (issue: https://github.com/XiaoMi/pegasus/issues/315) this week, it is caused by integer overflow. 
Master(meta server) will check lease periodically, like codes below:
```
now = dsn_now_ms();
{
zauto_lock l(_lock);
if(now - last_beacon_recv_time > grace_time){
// master consider worker disconnected
}
}
```
I found that last_beacon_recv_time might be larger than now during getting the lock, logs are below:
> **replica send beacon succeed**
> D2019-07-16 11:00:23.345 (1563246023345980449 20459) replica.     fd1.04080001000000bf: failure_detector.cpp:542:send_beacon(): send ping message, from[<replica_server_ip>], to[<meta_server_ip>], time[1563246023345]
> **meta receive beacon succeed**
> D2019-07-16 11:00:23.346 (1563246023346024792 7fe2)   meta. …
=> fd: fix ingeter overflow

include/dsn/dist/replication/duplication_common.h, src/dist/replication/meta_server/duplication/duplication_info.cpp, src/dist/replication/meta_server/duplication/duplication_info.h, src/dist/replication/meta_server/duplication/meta_duplication_service.cpp, src/dist/replication/meta_server/duplication/meta_duplication_service.h, src/dist/replication/test/meta_test/unit_test/duplication_info_test.cpp, src/dist/replication/test/meta_test/unit_test/meta_duplication_service_test.cpp
What this PR does:
- Fix the bug where:
Change a PAUSED duplication to PAUSED, since the status is not altered, after
meta server successfully persist the change to zookeeper, `dup->persist_status` will
unexpectedly fail because of the assertion:
```cpp
void duplication_info::persist_status()
{
zauto_write_lock l(_lock);
// this line fails
dassert_dup(_is_altering,
this,
"impossible, callers never write a duplication that is not altering to meta store");
```
Solution:
If the status is not altered, meta server return ERR_OK instead of writing this change to zookeeper.
```cpp
+    if (!dup->is_altering()) {
+        return;
+    }
```
- The removed duplication is still visible to users, for ease of debugging.
```cpp
-        // the invalid duplication is not visible to user.
-        if …
```
=> duplication: bugfix on pause_dup

src/dist/failure_detector/failure_detector.cpp
this pr is to improve #272 
the root cause is, if we get now time out of lock, `the now time` may be too old because of thread switch when waiting for the lock. 
so we should get now time in the lock to reduce the possibility.
=> fd: improve failure detector to avoid getting now time out of lock

include/dsn/tool-api/global_config.h, src/core/tests/aio.cpp, src/core/tests/config-test-corrupt-message.ini, src/core/tests/config-test-posix-aio.ini, src/core/tests/config-test-sim.ini, src/core/tests/config-test.ini, src/core/tests/service_api_c.cpp, src/dist/nfs/test/config.ini, src/dist/nfs/test/nfs_test_file1, src/dist/nfs/test/nfs_test_file2, src/dist/replication/common/test/config-test.ini, src/dist/replication/storage_engine/simple_kv/config.ini, src/dist/replication/test/meta_test/unit_test/config-ddl-test.ini, src/dist/replication/test/meta_test/unit_test/config-test.ini, src/dist/replication/test/replica_test/unit_test/config-test.ini, src/dist/replication/test/simple_kv/config.ini, src/tests/dsn/config-test.ini, src/tests/dsn/config-whitelist-test-failed.ini, src/tests/dsn/config-whitelist-test.ini
The following configs are removed:
- io_worker_count
- io_mode (see https://github.com/XiaoMi/rdsn/pull/117) 
- package_id
=> configs: remove useless configs

src/tests/dsn/failure_detector.cpp
commit #277 may cause unit test fail, for the reason of timeout  boundary problem.
so we extend lease/grace timeout from 4/5 to 9/10, to avoid the problem.
=> fd: fix unit test

include/dsn/dist/replication/replication_app_base.h, src/dist/replication/lib/mutation_cache.cpp, src/dist/replication/lib/mutation_cache.h, src/dist/replication/lib/replica.cpp, src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_chkpt.cpp, src/dist/replication/lib/replica_config.cpp, src/dist/replication/lib/replica_learn.cpp, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h, src/dist/replication/lib/replication_app_base.cpp, src/dist/replication/meta_server/meta_state_service_utils_impl.h, src/dist/replication/test/replica_test/unit_test/main.cpp, src/dist/replication/test/replica_test/unit_test/run.sh
What this PR did:
Remove some of the useless functions in replica-server:
- `replication_app_base::reset_counters_after_learning`
- `replication_app_base::install_perf_counters`
- `mutation_cache::remove_mutation_by_decree`
Some functions are refactored:
- `replica::query_app_envs`
- `replica::update_app_envs`
Rename  `update_commit_statistics` to `update_commit_qps`, `_counter_replicas_total_commit_throught` to `_counter_replicas_commit_qps`.
=> minor refactoring on replica-server and meta-server

CMakeLists.txt, bin/dsn.cmake, scripts/linux/build.sh, src/core/CMakeLists.txt, src/core/tests/CMakeLists.txt, src/dist/cli/shell/CMakeLists.txt, src/dist/http/test/CMakeLists.txt, src/dist/nfs/test/CMakeLists.txt, src/dist/replication/common/test/CMakeLists.txt, src/dist/replication/meta_server/CMakeLists.txt, src/dist/replication/storage_engine/simple_kv/CMakeLists.txt, src/dist/replication/test/meta_test/balancer_simulator/CMakeLists.txt, src/dist/replication/test/meta_test/unit_test/CMakeLists.txt, src/dist/replication/test/replica_test/unit_test/CMakeLists.txt, src/dist/replication/test/simple_kv/CMakeLists.txt, src/tests/dsn/CMakeLists.txt, thirdparty/fix_s2_for_pegasus.patch
https://github.com/XiaoMi/pegasus/issues/361#issuecomment-514975986
=> *: remove DSN_IN_CORE, improve BOOST linking, fix build.sh

src/dist/replication/common/replication_common.cpp, src/dist/replication/lib/CMakeLists.txt, src/dist/replication/lib/duplication/duplication_sync_timer.cpp, src/dist/replication/lib/duplication/duplication_sync_timer.h, src/dist/replication/lib/duplication/replica_duplicator_manager.h, src/dist/replication/lib/replica.cpp, src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h
This is the first part of the implementation of duplication on the replica-server side.
`duplication_sync_timer` is the timer periodically (10 seconds) sends `duplication_sync` to meta-server for retrieving the entire set of duplications on this server (aka `replica_stub`).
```
+-----------------------+
|                       |
|     meta server       |
|                       |
+-------^--------+------+
|        |
duplication_sync_request  duplication_sync_response
|        |
|        |
+------------+---+
|   |            |
+---+---+--------v---+--+
| duplication_sync_timer|
|   |                |  |
|   +----------------+  |
|                       |
|    replica server     |
|                       |
+-----------------------+
```
If the replica server successfully get the response …
=> dup: add duplication_sync_timer

thirdparty/build-thirdparty.sh, thirdparty/download-thirdparty.sh
prometheus-gateway need "curl.h" to run
so add curl to 3rdparty to build prometheus-cpp
=> thirdparty: add curl to help build prometheus

include/dsn/utility/errors.h, src/dist/replication/lib/CMakeLists.txt, src/dist/replication/lib/duplication/replica_duplicator.cpp, src/dist/replication/lib/duplication/replica_duplicator.h, src/dist/replication/lib/duplication/replica_duplicator_manager.cpp, src/dist/replication/lib/duplication/replica_duplicator_manager.h, src/dist/replication/lib/duplication/test/CMakeLists.txt, src/dist/replication/lib/duplication/test/config-test.ini, src/dist/replication/lib/duplication/test/duplication_sync_timer_test.cpp, src/dist/replication/lib/duplication/test/duplication_test_base.h, src/dist/replication/lib/duplication/test/main.cpp, src/dist/replication/lib/duplication/test/replica_duplicator_manager_test.cpp, src/dist/replication/lib/duplication/test/run.sh, src/dist/replication/lib/replica.cpp, src/dist/replication/test/replica_test/unit_test/mock_utils.h, src/dist/replication/test/replica_test/unit_test/replica_test_base.h
```
+--------------------------------+
|                                |
|  +--------------------------+  |
|  |                          |  |
|  |                          |  |          +--------------+
|  |   +-----------------+    |  |          |              |
|  |   |                 +----------------->+  bjsrv ad    |
|  |   |                 |    |  |          |              |
|  |   +--replica_duplicator  |  |          +--------------+
|  |                          |  |
|  |   +-----------------+    |  |          +--------------+
|  |   |                 +----------------->+              |
|  |   |                 |    |  |          |  gzsrv ad    |
|  |   +--replica_duplicator  |  |          |              |
|  |                          |  |          +--------------+
|  | …
```
=> dup: complete implementation of replica_duplicator_manager

include/dsn/utility/fail_point.h, src/core/core/fail_point.cpp, src/core/core/fail_point_impl.h, src/core/tests/CMakeLists.txt, src/core/tests/fail_point_test.cpp, thirdparty/build-thirdparty.sh
What does this PR do:
- enable fail point directly by `setup()`, rather than using macro `ENABLE_FAIL`. This will allow us to compile once for both testing purpose (enable fail point) and production purpose (disable fail point).
- add debugging logs on fail point
Additionally, this PR also disables building shared lib of curl (https://github.com/XiaoMi/rdsn/pull/288/files), which may conflict with system-built libcurl.so in some environment.
=> utility: enhance fail point functionality

bin/dsn.cmake, compile_thrift.py, src/dist/cli/shell/CMakeLists.txt, src/dist/http/CMakeLists.txt, src/dist/http/test/CMakeLists.txt, src/dist/replication/common/test/CMakeLists.txt, src/dist/replication/lib/duplication/test/CMakeLists.txt, src/dist/replication/storage_engine/simple_kv/CMakeLists.txt, src/dist/replication/test/meta_test/balancer_simulator/CMakeLists.txt, src/dist/replication/test/meta_test/unit_test/CMakeLists.txt, src/dist/replication/test/replica_test/unit_test/CMakeLists.txt, src/dist/replication/test/simple_kv/CMakeLists.txt, src/tests/dsn/CMakeLists.txt, thirdparty/build-thirdparty.sh
https://github.com/XiaoMi/pegasus/issues/361#issuecomment-515656652
It's unnecessary to build curl with [libidn](https://www.gnu.org/software/libidn/manual/libidn.html#Introduction).
=> build: use official thrift, cmake set default 3rdlibs, curl without idn

include/dsn/dist/replication/mutation_duplicator.h, src/core/tests/task_test.cpp, src/dist/replication/lib/CMakeLists.txt, src/dist/replication/lib/duplication/duplication_pipeline.cpp, src/dist/replication/lib/duplication/duplication_pipeline.h, src/dist/replication/lib/duplication/load_from_private_log.cpp, src/dist/replication/lib/duplication/load_from_private_log.h, src/dist/replication/lib/duplication/replica_duplicator.cpp, src/dist/replication/lib/duplication/replica_duplicator.h
This PR added interface `mutation_duplicator` and pipeline of duplication procedure.
This is the interface of data "sender" to be extensible for multiple endpoint types.
For example, if the remote endpoint is a pegasus cluster, the `pegasus_mutation_duplicator` will
transfer client RPCs to the remote pegasus.
If there's a further requirement to duplicate data to HBase/MySQL/etc., we can implement this interface.
The other part of this PR is simple. In each round of duplication, a batch of mutations is loaded
from private-log, and is sent via `mutation_duplicator` to remote endpoint.
So the pipeline can be declared like the following (in bash convention):
```bash
while true
do
load_from_private_log | ship_mutations
done
```
Each procedure in our implementation is declared as a **class**:
- …
=> feat(dup): add interface mutation_duplicator & duplication procedure

src/dist/replication/lib/replica_backup.cpp
issue: https://github.com/XiaoMi/pegasus/issues/311
现有逻辑为，接收到clean request（backup_id==0），先取得backup_context：
1.   如果backup_context不存在就clear_backup_checkpoint，确保相应目录被删除。如果是primary，还要把clean request发给secondary。
1. 如果backup_context存在，则删除backup_context。如果是primary，还要把clean request发给secondary。删除相应目录。
问题点在于收到clean request时，可能正在checkpointing，这时如果目录在copy to dir 途中删除，就会造成core。
2019-10-10 01:05出现的core，精确时间Modify: 2019-10-10 01:05:37.504636201 +0800：
```
pegasus::server::pegasus_server_impl::copy_checkpoint_to_dir_unsafe(
/home/work/ssd1/pegasus/azmbcloudsrv-storecom/replica/reps/3.16.pegasus/backup/backup_tmp.every_day.1570640707754.1570640708469
```
及日志：
D2019-10-10 01:05:28.469 (1570640728469920756 11607) replica.replica13.040015d28eb66b87: replica_stub.cpp:893:on_cold_backup(): received cold backup …
=> fix(backup): delay clearing obsoleted backup when it's still checkpointing

include/dsn/utility/binary_reader.h, src/core/core/binary_reader.cpp
I didn't find any usage of the three functions. So let's remove them.
=> refactor: remove useless functions from binary_reader

src/dist/replication/meta_server/server_state.cpp
[issue #331](https://github.com/XiaoMi/rdsn/issues/331)
=> fix: meta unnecessary assert

include/dsn/dist/replication/replication_types.h, include/dsn/tool-api/task_spec.h, src/core/core/task_spec.cpp, src/dist/replication/common/replication_types.cpp, src/dist/replication/lib/replica.cpp, src/dist/replication/lib/replica.h
Add table level latency perf-counters for all of the table read or write operations.
1.Count all the storage request rpc codes into `std::vector<dsn::task_code> storage_rpc_req_codes`  from function register_storage_task_code, which would be called by creating storage rpc code.
2.when a replica is created, using the replica's table name,  a list of perf counters will be created for each task code in storage_rpc_req_codes. If a perf counter was already created, it would not created repeatly.
3.For read operations, the running time of `_app->on_request(request)` is Statisticed in function replica::on_client_read.
4.For write operations, a variable was added in mutation_update, which name is start_time_ns. So in execute_mutation function, the running time of the write operaiton will be …
=> feat: add table level latency perf counters

include/dsn/tool-api/task_spec.h, src/core/core/task_spec.cpp, src/dist/replication/lib/replica.cpp
In function test of pegasus, insert into s_storage_rpc_req_codes will cause coredump, which was call by macro DEFINE_STORAGE_WRITE_RPC_CODE. But it`s normal when I runs onebox on local environment. It is caused by static initialization order probleom. Because DEFINE_STORAGE_WRITE_RPC_CODE was called first, but s_storage_rpc_req_codes was not initlized, so it produces coredump.  As description, we have a 50%-50% chance of corrupting the program.
=> fix(bug): resolve static initialization order problem of s_storage_rpc_req_codes

src/dist/replication/common/replication_common.cpp, src/dist/replication/common/replication_common.h, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h
Pull request #278 add a new feature that releasing memory periodically by tcmalloc `ReleaseFreeMemory`. `ReleaseFreeMemory` will release all tcmalloc reserved and not-used memory back to operating system. Releasing memory will lock `page heap`, the structure used to allocate memory from operating system and release memory back to operating system, shared by all threads. As a result, releasing all free memory will lock `page heap` for a long time and block all threads, more seriously, it will affect cluster performance. More tcmalloc information can be find in [tcmalloc website](https://gperftools.github.io/gperftools/tcmalloc.html).
So we optimize the releasing memory method, which is similar to kudu's way [(kudu gc_memory).](https://github.com/apache/kudu/blob/3d57198663f3ed6980f4d9272096 …
=> feat: optimize tcmalloc release memory

include/dsn/c/api_utilities.h, include/dsn/dist/fmt_logging.h, include/dsn/tool-api/logging_provider.h, src/core/core/logging.cpp, src/core/tests/logging.cpp, src/core/tools/common/simple_logger.cpp, src/core/tools/common/simple_logger.h
Because the bug of log interface in fmt_logging.h, using it to print a string which contrains "%n" will result in core dump. For more detail: https://github.com/XiaoMi/pegasus/issues/431
=> fix: fix log bug in fmt logging

src/core/tools/common/shared_io_service.h
In shared_io_service, there are some threads running. But shared_io_service doesn't have a destructor, so these threads can't be stopped.
So this pull request add a destructor for it to stop these threads.
=> fix: fix the bug that threads don't stop when shared_io_service is released

include/dsn/perf_counter/perf_counters.h, src/core/perf_counter/perf_counters.cpp, src/core/tests/perf_counters_test.cpp, src/dist/http/http_server.cpp, src/dist/http/perf_counter_http_service.cpp, src/dist/http/perf_counter_http_service.h, src/dist/http/test/perf_counter_http_service_test.cpp
Add a  http interface to get perf counter info by the name of this perf counter.
request url: 
```
http://127.0.0.1:34803/perfCounter?name=replica*eon.replica*table.level.RPC_RRDB_RRDB_PUT.latency(ns)@temp
```
response:
```
{"name":"replica*eon.replica*table.level.RPC_RRDB_RRDB_PUT.latency(ns)@temp","p99":"0.00","p999":"0.00","type":"PERCENTILE","description":"table.level.RPC_RRDB_RRDB_PUT.latency(ns)@temp"}
```
=> feat: add http interface to get perf counter info

src/dist/replication/meta_server/server_state.cpp, src/dist/replication/test/meta_test/unit_test/state_sync_test.cpp
#332 resolve the core dump when assert the meta state, but the response state to client is not reasonable. This pr fix the bug.
=> fix: fix meta response state to client 

bin/dsn.cmake, run.sh
In #359 add the sanitizer support, but in commit [e80446f](https://github.com/XiaoMi/rdsn/pull/359/commits/e80446faa6fe716bfa144368bdc72aac160c186c), the code
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=${SANITIZER}" )
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=${SANITIZER}" )
```
was moved into `dsn_setup_compiler_flags`  function and it don't take effect because `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` change to local variable. The pr change the code to:
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=${SANITIZER}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=${SANITIZER}" CACHE STRING "" FORCE)
```
=> fix: sanitizer options don't take effect 

src/dist/replication/meta_server/greedy_load_balancer.cpp, src/dist/replication/meta_server/greedy_load_balancer.h
Removes `greedy_load_balancer::secondary_balancer_globally` and `greedy_load_balancer::primary_balancer_globally` because they are not used.
=> refactor: remove unused functions in greedy_load_balancer

src/core/tests/string_conv_test.cpp
```
==16642==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00000094dd26 at pc 0x7f073c539935 bp 0x7f072bb8c810 sp 0x7f072bb8bfb8
READ of size 7 at 0x00000094dd26 thread T21 (client.THREAD_P)
#0 0x7f073c539934 in __asan_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8c934)
#1 0x63c267 in std::char_traits<char>::copy(char*, char const*, unsigned long) /usr/include/c++/5/bits/char_traits.h:290
#2 0x63c267 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long) /usr/include/c++/5/bits/basic_string.h:299
#3 0x63c267 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char*, char*) /usr/include/c++/5/bits/basic_string.h:341
#4 0x63c267 in void …
```
=> fix(asan):  global-buffer-overflow in string_conv_test

include/dsn/utility/autoref_ptr.h, src/core/tests/autoref_ptr_test.cpp
It reports ` heap-use-after-free`  error that the pointer `self_ptr_` is used after free in `autoref_ptr_test.ScopedRefPtrToSelfPointerAssignment` when run test with [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) tool.
```
#0 0x4cfb64 in operator= /home/mi/work/PegasusDB/pegasus/rdsn/include/dsn/utility/autoref_ptr.h:155
#1 0x4cfb64 in RefCountedUnitTest_ScopedRefPtrToSelfPointerAssignment_Test::TestBody() /home/mi/work/PegasusDB/pegasus/rdsn/src/core/tests/autoref_ptr_test.cpp:157
#2 0x6aab1e in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/mi/work/PegasusDB/pegasus/rdsn/builder/src/core/tests/dsn.core.tests+0x6aab1e)
``` …
=> fix(asan): pointer used after free in autoref_ptr_test

src/dist/replication/meta_server/meta_backup_service.cpp, src/dist/replication/meta_server/meta_backup_service.h, src/dist/replication/meta_server/meta_service.h, src/dist/replication/meta_server/server_state.h, src/dist/replication/test/meta_test/unit_test/backup_test.cpp, src/dist/replication/test/meta_test/unit_test/balancer_validator.cpp, src/dist/replication/test/meta_test/unit_test/data_definition_test.cpp, src/dist/replication/test/meta_test/unit_test/json_compacity.cpp, src/dist/replication/test/meta_test/unit_test/main.cpp, src/dist/replication/test/meta_test/unit_test/meta_load_balance_test.cpp, src/dist/replication/test/meta_test/unit_test/meta_service_test_app.h, src/dist/replication/test/meta_test/unit_test/server_state_test.cpp, src/dist/replication/test/meta_test/unit_test/state_sync_test.cpp, src/dist/replication/test/meta_test/unit_test/update_configuration_test.cpp
I'm going to refactor the load balancing related tests and codes. This is the first step. I moved the `simple_lb_xxx` tests to `meta_load_balance_test` to make it clear.
My goal is to:
1. Simplify `simple_lb_balanced_cure`, which consists of 600+ LOC.
2. Make the codes of load balancer easier to read, both unit tests and implementation.
=> refactor: move load balance related tests under another test suite

include/dsn/tool-api/http_server.h, include/dsn/utility/autoref_ptr.h, src/dist/http/http_server.cpp, src/dist/http/perf_counter_http_service.h, src/dist/http/pprof_http_service.h, src/dist/http/root_http_service.h, src/dist/http/server_info_http_services.h, src/dist/http/test/http_server_test.cpp, src/dist/replication/meta_server/meta_http_service.h
```
http 127.0.0.1:34601
```
```
{
"/": "ip:port/", 
"/meta/app": "ip:port/meta/app?app_name=temp", 
"/meta/app_envs": "ip:port/meta/app_envs?name=temp", 
"/meta/apps": "ip:port/meta/apps", 
"/meta/backup_policy": "ip:port/meta/backup_policy", 
"/meta/cluster": "ip:port/meta/cluster", 
"/meta/nodes": "ip:port/meta/nodes", 
"/perfCounter": "ip:port/perfCounter?name={perf_counter_name}", 
"/pprof/cmdline": "ip:port/pprof/cmdline", 
"/pprof/growth": "ip:port/pprof/growth", 
"/pprof/heap": "ip:port/pprof/heap", 
"/pprof/profile": "ip:port/pprof/profile", 
"/pprof/symbol": "ip:port/pprof/symbol", 
"/recentStartTime": "ip:port/recentStartTime", 
"/version": "ip:port/version"
}
```
```
http 127.0.0.1:34801
```
```
{
"/": "ip:port/", 
"/perfCounter": …
```
=> feat(http): print help info on root path of the http server

src/dist/replication/lib/duplication/duplication_pipeline.cpp, src/dist/replication/lib/duplication/duplication_pipeline.h, src/dist/replication/lib/replica.cpp, src/dist/replication/lib/replica_stub.cpp
`load_mutation` is a part of the duplication procedure:
```
while true
do
load_mutations | ship_mutations
done
```
If currently there are newly added mutations on disk, it will call `load_from_private_log` to load them and goes on next stage, otherwise it sleeps 10sec like polling.
=> feat(dup): implement load_mutation

include/dsn/tool-api/global_config.h, src/core/core/rpc_engine.cpp, src/core/core/service_engine.cpp, src/core/core/task_engine.cpp, src/core/core/zlocks.cpp
rDSN provides several pluggable components that can be customized via `aspects`: https://github.com/microsoft/rDSN/blob/8aee3ac874e7d6fe2a90b01aceae39c0002f305d/src/plugins/apps.echo/config.ini#L119. However they are never used in our system, and they are rather complicated.
They are confirmed not used in our production environment. This refactoring is safe.
=> refactor: remove aspects for dsn runtime

src/dist/replication/test/meta_test/unit_test/meta_load_balance_test.cpp
Related issue: #364 
The reason is `svc->set_filter(default_filter)` free the heap which is located by `svc->set_filter([&](const dsn::rpc_address &target, dsn::message_ex *req) -> cur_ptr {...});`, and the variable `proposal_sent` is also freed, however, it is still used in L435.
https://github.com/XiaoMi/rdsn/blob/1e5d529eb0c7a96965c885a0de2c80f76580ed89/src/dist/replication/test/meta_test/unit_test/simple_lb_cure_test.cpp#L435
https://github.com/XiaoMi/rdsn/blob/1e5d529eb0c7a96965c885a0de2c80f76580ed89/src/dist/replication/test/meta_test/unit_test/simple_lb_cure_test.cpp#L423-L437
`proposal_sent=true` before `svc->set_filter(default_filter)`
=> fix(asan): heap-use-after-free in simple_lb_cure_test.cpp

src/dist/replication/test/meta_test/unit_test/meta_test_base.h
#376 
The 3th argument  of `utils::factory_store<server_load_balancer>::create(const char *name, ::dsn::provider_type type, T1 t1)` is set to `meta_test_base` type in line 24 of `meta_test_base.h`. 
https://github.com/XiaoMi/rdsn/blob/7b370383ba111bf5171c82b0e0ab323794aadee8/src/dist/replication/test/meta_test/unit_test/meta_test_base.h#L21-L29
Therefore, It will be illegally cast to `meta_service` type in line 60 of `server_load_balancer.h` and report `heap-buffer-overflow` in line 235. 
https://github.com/XiaoMi/rdsn/blob/7b370383ba111bf5171c82b0e0ab323794aadee8/src/dist/replication/meta_server/server_load_balancer.h#L54-L61
https://github.com/XiaoMi/rdsn/blob/7b370383ba111bf5171c82b0e0ab323794aadee8/src/dist/replication/meta_server/server_load_balancer.h#L230-L240
The root cause is …
=> fix(asan): heap-buffer-overflow in meta_test_base.h

src/dist/replication/test/replica_test/unit_test/replica_split_test.cpp
```
==28319==ERROR: AddressSanitizer: heap-use-after-free on address 0x60c000011cc8 at pc 0x7f9bd911df10 bp 0x7f9bc21db080 sp 0x7f9bc21db070
READ of size 4 at 0x60c000011cc8 thread T29 (replica.replica)
[       OK ] replica_split_test.add_child_succeed (1 ms)
[----------] 1 test from replica_split_test (1 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 1 test.
#0 0x7f9bd911df0f in dsn::fail::fail_point::eval[abi:cxx11]() /home/mi/work/PegasusDB/pegasus/rdsn/src/core/core/fail_point.cpp:140
#1 0x7f9bd911e1a1 in dsn::fail::eval[abi:cxx11](dsn::string_view) /home/mi/work/PegasusDB/pegasus/rdsn/src/core/core/fail_point.cpp:37
#2 0x7f9bd8eb8d7e in dsn::replication::replica::child_init_replica(dsn::gpid, …
```
=> fix(asan): fix heap-use-after-free in replica_split_test

include/dsn/dist/replication/replication_types.h, src/dist/replication/common/replication_types.cpp, src/dist/replication/lib/mutation.cpp, src/dist/replication/replication.thrift
Pull request #336 added a new filed called `start_time_ns` for structure `mutation_update`. `mutation_update` is defined in `replication.thrift`, and we generate `.h` and `.cpp` files atomically by thrift. However, original pr directly added this filed in `.h` and `.cpp` file, which might be difficult to maintain. 
This pr add a new filed `start_time_ns` for structure `mutation_update` in thrift file, and initialize it when creating this structure in function `add_client_request`.
=> fix(thrift): add start_time_ns for structure mutation_update in thrift file

include/dsn/utility/time_utils.h, src/core/tests/time_utils_test.cpp, src/core/tests/utils.cpp
There is a function in time_utils, which name is ```get_localtime```. It calls ```localtime_r(const time_t *timep, struct tm *result)``` and return the return value of this function.
While ```localtime_r``` needs the second parameter, the struct tm *result, as a buffer to store the return value. But in our ```get_localtime``` function, it pass a local variable to ```localtime_r```. And after it returns, the local variable is destroyed. So this leads to some undefined errors.
=> fix(utils): fix bug in time_utils

include/dsn/dist/replication/replication_types.h, src/dist/replication/common/replication_common.cpp, src/dist/replication/common/replication_types.cpp, src/dist/replication/meta_server/duplication/meta_duplication_service.cpp, src/dist/replication/replication.thrift
add_dup previously used error code to identify the failure. In most cases this is enough. 
However, error code may be ambiguous, ERR_INVALID_ARGUMENT for example:
```cpp
if (request.remote_cluster_name == get_current_cluster_name()) {
response.err = ERR_INVALID_PARAMETERS;
response.__set_hint("illegal operation: adding duplication to itself");
return;
}
auto remote_cluster_id = get_duplication_cluster_id(request.remote_cluster_name);
if (!remote_cluster_id.is_ok()) {
response.err = ERR_INVALID_PARAMETERS;
response.__set_hint(fmt::format("get_duplication_cluster_id({}) failed, error: {}",
request.remote_cluster_name,
remote_cluster_id.get_error()));
return;
}
```
Between the above two cases, we still need a hint to determine the cause.
When the error code is self-descriptive, …
=> feat(dup): respond with hint when add_dup failed

src/dist/replication/lib/replica.cpp, src/dist/replication/lib/replica.h, src/dist/replication/test/replica_test/unit_test/replica_test.cpp
Add a perf-counter to statistics the qps of backup request for each app.
Related issue: https://github.com/XiaoMi/pegasus/issues/251
=> feat: add perf-counter for backup request

scripts/linux/build.sh, src/dist/replication/common/duplication_common.cpp, src/dist/replication/lib/duplication/test/replica_http_service_test.cpp, src/dist/replication/lib/replica_http_service.cpp, src/dist/replication/meta_server/duplication/duplication_info.cpp, src/dist/replication/test/meta_test/unit_test/meta_duplication_service_test.cpp
We didn't have `dsn_replica_dup_test` run in travis-ci. So this PR adds it to build.sh.
Meta's HTTP output is also changed.
For `http://xxx/meta/app/duplication?name=temp` I remove `not_confirmed_mutations_num`, because replica-server does not sync "last_committed_decree" to meta, which is unable to calculate the result by `part.last_committed_decree - it->second.stored_decree;`.
So the final result is:
```json
{
"1": {
"create_ts": "2020-03-21 08:30:42",
"dupid": 1584750642,
"fail_mode": "FAIL_SLOW",
"remote": "onebox2",
"status": "DS_START"
},
"appid": 2
}
```
If we want to check `not_confirmed_mutations_num` of a specified table, we can query for all the replica nodes via `http://xxx/replica/duplication?appid=2`.
=> feat(dup): add dsn_replica_dup_test to CI testing and fix http outputs

src/dist/replication/lib/duplication/duplication_pipeline.cpp, src/dist/replication/lib/duplication/duplication_pipeline.h, src/dist/replication/lib/duplication/load_from_private_log.cpp, src/dist/replication/lib/duplication/load_from_private_log.h, src/dist/replication/lib/duplication/replica_duplicator.cpp, src/dist/replication/lib/duplication/replica_duplicator.h, src/dist/replication/lib/duplication/test/ship_mutation_test.cpp, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h
1. Some duplication perf-counters are moved  from `replica_stub` to where they are updated:
- `_counter_dup_shipped_bytes_rate` to `ship_mutattion`
- `_counter_dup_log_read_mutations_rate` to `load_from_private_log`
- `_counter_dup_log_read_bytes_rate` to `load_from_private_log`
One advantage is when duplication is paused, these perf-counters will be immediately removed, due to destruction of the duplication pipeline. Therefore we can ensure these counters are accurate after pause_dup.
Another advantage is the improved modularity by separating duplication metrics from `replica_stub`, reduce its code complexity.
2. Uses `cancel_all` instead of `wait_all` for pause_dup. (replica_duplicator.h)
Formerly duplication may not be able to pause in some bad cases, for example, where the remote …
=> fix(dup): multiple fixes on replica duplication

include/dsn/dist/replication/duplication_common.h, include/dsn/dist/replication/replication_ddl_client.h, include/dsn/dist/replication/replication_types.h, src/dist/block_service/fds/fds_service.cpp, src/dist/replication/common/duplication_common.cpp, src/dist/replication/common/replication_types.cpp, src/dist/replication/ddl_lib/replication_ddl_client.cpp, src/dist/replication/lib/duplication/duplication_sync_timer.cpp, src/dist/replication/lib/duplication/duplication_sync_timer.h, src/dist/replication/lib/duplication/load_from_private_log.cpp, src/dist/replication/lib/duplication/load_from_private_log.h, src/dist/replication/lib/duplication/replica_duplicator.h, src/dist/replication/lib/duplication/replica_duplicator_manager.cpp, src/dist/replication/lib/duplication/replica_duplicator_manager.h, src/dist/replication/lib/duplication/test/load_from_private_log_test.cpp, src/dist/replication/lib/duplication/test/replica_http_service_test.cpp, src/dist/replication/lib/replica_http_service.cpp, src/dist/replication/meta_server/duplication/duplication_info.cpp, src/dist/replication/meta_server/duplication/duplication_info.h, src/dist/replication/meta_server/duplication/meta_duplication_service.cpp, src/dist/replication/replication.thrift, src/dist/replication/test/meta_test/unit_test/meta_duplication_service_test.cpp
This PR introduces a new concept, namely "fail_mode" for duplication, in case of permanent failure occurred, fail-modes will allow flexible and extensible failure handling strategies.
replication.thrift
```thrift
// How duplication reacts on permanent failure.
enum duplication_fail_mode
{
// The default mode. If some permanent failure occurred that makes duplication
// blocked, it will retry forever until external interference.
FAIL_SLOW = 0,
// Skip the writes that failed to duplicate, which means minor data loss on the remote cluster.
// This will certainly achieve better stability of the system.
FAIL_SKIP,
// Stop immediately after it ensures itself unable to duplicate.
// WARN: this mode kills the server process, replicas on the server will all be effected.
FAIL_FAST
}
```
We …
=> feat(dup): support multiple fail modes for duplication

src/dist/replication/lib/log_block.cpp, src/dist/replication/lib/log_block.h, src/dist/replication/lib/mutation_log.cpp, src/dist/replication/lib/mutation_log.h, src/dist/replication/test/replica_test/unit_test/log_block_test.cpp
To write a mutation, the mutation_log first appends it to `_pending write`, which is a `log_block`, then flush this block to disk by `commit_log_block`.
Throughout the procedure, some variables are participated, for shared log:
```cpp
std::shared_ptr<log_block> _pending_write;
std::shared_ptr<callbacks> _pending_write_callbacks;
std::shared_ptr<mutations> _pending_write_mutations;
int64_t _pending_write_start_offset;
```
For private log:
```cpp
std::shared_ptr<log_block> _pending_write;
std::shared_ptr<mutations> _pending_write_mutations;
int64_t _pending_write_start_offset;
uint64_t _pending_write_start_time_ms;
decree _pending_write_max_commit;
decree _pending_write_max_decree;
```
Apparently, some codes and variables are repeated in both private log and shared log that we can wrap into …
=> refactor: move log-block-writing-related codes from mutation_log to log_block

src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h
In pull request #343 , we optimize tcmalloc release memory. Based on the former implementation, this pull request add more improvements about it:
1. Add a new perf-counter to record tcmalloc release memory
2. Add a new remote command to control release memory or not
3. Fix percentage range check from (0, 100) to (0, 100]
`replica*eon.replica_stub*tcmalloc.release.memory.size`
This perf-counter has a **problem** that it will only be updated every interval time. For example, if tcmalloc memory release time interval is one hour, one server releases 1G memory at 10:00, the value won't change until 11:00. As a result, the monitor graph will be like a trapezoid.
If you have a better way to solve this problem, please comment this pull request or discuss with me offline.
command help: …
=> feat: tcmalloc memory release improvements

src/dist/replication/lib/log_block.cpp, src/dist/replication/lib/log_block.h, src/dist/replication/lib/mutation_log.cpp, src/dist/replication/lib/mutation_log.h, src/dist/replication/test/replica_test/unit_test/log_block_test.cpp, src/dist/replication/test/replica_test/unit_test/log_file_test.cpp
The current `mutation_log` implementation is unfriendly with such case:
There're some writes being flushed into the disk, in the meantime, new incoming writes are pending in the `log_block` waiting to be flushed.
As the pending `log_block` grows, it could be considerably large (like tens of MB) which is unfriendly for both replica recovery and duplication. I've met a bug while testing duplication that reading a large log block may cause tcmalloc to allocate an inaccessible memory.
This PR limits the log block to 1MB using `log_appender`, reduces the possibility of large block related bug.
`log_appender` is a buffer for multiple log blocks. This PR doesn't change the behavior that **all the pending writes** will be flushed to disk (`mutation_log::commit_pending_mutations`), **no matter how …
=> feat: append mlog in fixed-size blocks using log_appender

include/dsn/utility/TokenBucket.h, src/core/tests/TokenBucketTest.cpp, src/core/tests/TokenBucketTest.h
In this pr, token bucket is added for rate limit, which is migrated from https://github.com/facebook/folly/blob/master/folly/TokenBucket.h
There are some changes here, which are based on folly's version:
- Replace folly::optional with boost::optional. 
1. Replace folly::optional::value_or() with boost::optional::get_value_or()
2. Replace folly::optional::value() with boost::optional::get()
- Replace folly::unlikely with dsn_unlikely
=> feat(util): add token bucket for rate limit

src/dist/replication/lib/duplication/duplication_pipeline.cpp, src/dist/replication/lib/duplication/load_from_private_log.h
Previously, the time-lag between master and slave was 10+seconds. It's unacceptable for most of our users. After listening for their requirement I found a **1-second-time-lag** is mostly satisfying for them. So here I did some optimization experiments:
1. Reduce the repeat delay time when one replica finds no committed mutations on disk:
```diff
if (_replica->private_log()->max_commit_on_disk() < _start_decree) {
-        // wait 10 seconds for next try if no mutation was added.
-        repeat(10_s);
+        // wait 100ms for next try if no mutation was added.
+        repeat(100_ms);
return;
}
```
This optimization greatly decreases the time lag to 1s. 
2. Another optimization is based on that `load_from_private_log` will sleep 10s when it is unable to read more from plog. One naive …
=> feat(dup): optimize time-lag by reducing repeat delay

src/dist/block_service/local/local_service.cpp
We use this way to get characters from fin
```
buf.reserve(total_sz + 1);
```
but there is a problem in this way, which is `buf.length()` = 0.  It means that int this way, we cann't get the real size of characters.
=> fix: fix bug in local_service

include/dsn/cpp/rpc_holder.h
While creating request in rpc_holder, `thread_hash` is always equal to 0. 
`thread_hash` is used for thread dispatching, which is critical to rpc between replica servers.
This pull request update rpc_holder, permitting define thread_hash.
=> feat: update rpc_holder

thirdparty/build-thirdparty.sh, thirdparty/download-thirdparty.sh
According to https://github.com/cameron314/concurrentqueue/releases, `concurrentqueue` has a stable version, so I update it.
=> improvement(third-party): Update the concurrentqueue to a stable release version

src/dist/replication/common/replication_common.cpp, src/dist/replication/common/replication_common.h, src/dist/replication/meta_server/meta_bulk_load_service.cpp, src/dist/replication/meta_server/meta_bulk_load_service.h, src/dist/replication/test/meta_test/unit_test/meta_bulk_load_service_test.cpp
The whole bulk load process is like:
1. client sends request to meta server to start bulk load
2. meta sends bulk_load_request to primary replicas
3. primary broadcasts group_bulk_load_request, collects bulk load states from secondary, and reports group bulk load states to meta
4. meta receive bulk_load_response, if bulk load not finished, jump to step2, resend bulk_load_request
This pull request is about meta receive bulk_load_response from primary, the step4 above.
- if rpc meet error or resp.err is OBJECT_NOT_FOUND and INVALID_STATE, meta considers that bulk load meets some recoverable errors and tries to rollback to downloading and resend bulk load request
- each node will limit bulk load downloading count, if resp.err is BUSY, it means that the node has already have enough replica …
=> feat(bulk-load): meta handle bulk_load_response

src/core/tools/hpc/hpc_task_queue.h
In this pr(https://github.com/XiaoMi/rdsn/pull/462), concurrentqueue is updated to a stable release version. But this version changes the namespace of `LightweightSemaphore` from `moodycamel::details::mpmc_sema` to `moodycamel::LightweightSemaphore`. So in hpc_task_queue we should change it synchronously.
=> fix: fix bug in hpc_task_queue

thirdparty/download-thirdparty.sh
`READERWRITER_QUEUE_NAME` was mistakenly written as `CONCURRENT_QUEUE_NAME`, so was `READERWRITER_QUEUE_PKG`
=> fix: fix bug in download-thirdparty

src/dist/replication/meta_server/duplication/meta_duplication_service.cpp, src/dist/replication/test/meta_test/unit_test/config-test.ini, src/dist/replication/test/meta_test/unit_test/meta_duplication_service_test.cpp
This fix is to ensure the robustness when the remote cluster address of `add_dup` was misconfigured.
=> fix(dup): reject add_dup if remote address incorrect

src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_file_provider.cpp, src/dist/replication/test/replica_test/unit_test/mock_utils.h, src/dist/replication/test/replica_test/unit_test/replica_file_provider_test.cpp
This pull request add `do_download` function and its unit test. This function is used to download files from remote provider.
=> feat(bulk-load): bulk load download part2 - replica download files

src/core/tools/common/asio_net_provider.cpp
In rdsn, if you use UDP to send beacon between meta server and replica server, the memory usage will continue to grow. It is because the response is not released after it is sent by asio_udp_provider.
For the callers of `dsn_rpc_reply`, they think the response is released by `dsn_rpc_reply` itself by default. So they shouldn't need to release the response. For example: `serverlet<T>::reply`, `rpc_holder::reply`. They just create a response and pass it to `dsn_rpc_reply`.
```cpp
DSN_API void dsn_rpc_reply(dsn::message_ex *response, dsn::error_code err)
{
auto msg = ((::dsn::message_ex *)response);
::dsn::task::get_current_rpc()->reply(msg, err);
}
```
Then `dsn_rpc_reply` simply passes the response to `rpc_engine::reply`, and let it release the response.
Let's have a look at …
=> fix: fix memory leak in asio_udp_provider

include/dsn/utility/filesystem.h, src/core/core/filesystem.cpp, src/dist/replication/common/replication_common.cpp, src/dist/replication/common/replication_common.h, src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.h, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp
This pull request is about what will replica do after downloading metadata file and sst files.
- if download metadata succeed, replica will parse metadata from file to local `_metadata` (in function `parse_bulk_load_metadata`)
- if download sst file succeed, replica will compare sst file size and md5 with the value parsed from metadata (in function `verify_file`)
- if pass verification, replica will update download progress (in function `update_bulk_load_download_progress`)
- if current replica download all sst files, will turn bulk load status to downloaded (in function `check_download_finish`)
=> feat(bulk-load): bulk load download part3 - replica parse metadata, verify files and update progress

src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.h, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp, src/dist/replication/lib/replica_context.cpp, src/dist/replication/lib/replica_context.h, src/dist/replication/test/replica_test/unit_test/mock_utils.h
The whole bulk load download process is like:
1. meta server set app and all partitions bulk load status is downloading #454
2. meta server send request to primary to download files #457
3. primary download files #465 #471 #475 
4. primary broadcast request to secondary #460
5. secondary download files #465 #471 #475 
6. **secondary report download progress and status to primary**
7. **primary report group download progress and status to meta server**
8. meta receive download progress
- if all replicas of the group finish download all files, meta set this partition status as downloaded, and if all partitions are downloaded, app status will be set as downloaded, otherwise, meta will resend request to primary
This pull request is about replica report download status and progress, step 6 and …
=> feat(bulk-load): bulk load download part4 - replica report download status and progress

.travis.yml, scripts/linux/start_zk.sh, src/core/tests/address.cpp, thirdparty/build-thirdparty.sh, thirdparty/download-thirdparty.sh
RocksDB was maintained as a stable submodule with no frequent modification. So we make it a thirdparty now. Then we can build Pegasus faster if the thirdparties all prebuilt.
=> build: add rocksdb as thirdparty

src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/replica_split.cpp, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h, src/dist/replication/test/replica_test/unit_test/replica_disk_test.cpp
For most RPC interfaces of replica server, use rpc holder to reimplement them.
=> refactor: use rpc holder to reimplement rpc interface of replica server

include/dsn/utility/filesystem.h, src/core/core/filesystem.cpp, src/core/tests/file_system_test.cpp, src/dist/block_service/block_service_manager.cpp, src/dist/block_service/block_service_manager.h, src/dist/block_service/test/block_service_manager_test.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp
This pull request is about to move function `verify_file` from `block_service_manager` to `file_system`. This is not related to block service, only check if file metadata is equal to expected value. This pull request also move unit tests.
=> refactor: move function verify_file to file_system

src/dist/replication/meta_server/meta_bulk_load_service.cpp, src/dist/replication/replication.thrift, src/dist/replication/test/meta_test/unit_test/meta_bulk_load_service_test.cpp
The whole bulk load ingestion process is like:
1. meta server set app and all partitions bulk load status as ingesting #486 
2. meta send two requests to primary 
- send ingestion request to primary #486 
- send bulk load request to query ingestion status #457
3. primary handle two requests above:
- primary consider ingestion request as a client write and replica group execute 2pc process to do actual rocksdb ingestion operation #490 pegasus pr [#546](https://github.com/XiaoMi/pegasus/pull/546)
- primary handle bulk load request and broadcast it to secondary
4. secondary handle two cases:
- ingestion files through 2pc #490 pegasus pr [#546](https://github.com/XiaoMi/pegasus/pull/546)
- report ingestion status to primary 
5. primary report group ingestion status to primary
6. meta handle …
=> feat(bulk-load): bulk load ingestion part4 - meta handle ingestion response

include/dsn/dist/replication/replication_types.h, src/dist/replication/common/replication_types.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.h, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp, src/dist/replication/lib/prepare_list.cpp, src/dist/replication/lib/prepare_list.h, src/dist/replication/lib/replica.h, src/dist/replication/lib/replica_2pc.cpp, src/dist/replication/lib/replica_context.cpp, src/dist/replication/lib/replica_context.h, src/dist/replication/replication.thrift, src/dist/replication/test/replica_test/unit_test/mock_utils.h
The whole bulk load ingestion process is like:
1. meta server set app and all partitions bulk load status as ingesting #486 
2. meta send two requests to primary 
- send ingestion request to primary #486 
- send bulk load request to query ingestion status #457
3. primary handle two requests above:
- primary consider ingestion request as a client write and replica group execute 2pc process to do actual rocksdb ingestion operation #490 pegasus pr [#546](https://github.com/XiaoMi/pegasus/pull/546)
- **primary handle bulk load request** and broadcast it to secondary #460 
4. secondary handle two cases:
- ingestion files through 2pc #490 pegasus pr [#546](https://github.com/XiaoMi/pegasus/pull/546)
- **report ingestion status to primary**
5. **primary report group ingestion status to meta …
=> feat(bulk-load): bulk load ingestion part5 - replica handle bulk load request during ingestion

include/dsn/cpp/rpc_holder.h, src/dist/replication/meta_server/meta_service.cpp, src/dist/replication/meta_server/meta_service.h
use check_status to reimplement some rpc interfaces of meta_service: including `on_query_configuration_by_index` and `on_start_recovery`
=> refactor: use check_status to reimplement some rpc interfaces of meta_service

src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/meta_server/meta_bulk_load_service.cpp, src/dist/replication/test/meta_test/unit_test/meta_bulk_load_service_test.cpp
The whole bulk load ingestion process is like:
1. meta server set app and all partitions bulk load status as ingesting #486 
2. meta send two requests to primary 
- send ingestion request to primary #486 
- send bulk load request to query ingestion status #457
3. primary handle two requests above:
- primary consider ingestion request as a client write and replica group execute 2pc process to do actual rocksdb ingestion operation #490 pegasus pr [#546](https://github.com/XiaoMi/pegasus/pull/546)
- primary handle bulk load request and broadcast it to secondary #496 #460
4. secondary handle two cases:
- ingestion files through 2pc #490 pegasus pr [#546](https://github.com/XiaoMi/pegasus/pull/546)
- report ingestion status to primary #496 
5. primary report group ingestion status to meta …
=> feat(bulk-load): bulk load ingestion part6 - meta handle bulk_load_response during ingestion

include/dsn/dist/replication/storage_serverlet.h
In this PR we add an interface of `rpc_holder` in order to replace `rpc_replier`
We plan to remove `rpc_replier` in subsequent refactorings.
=> refactor: add a interface of rpc_holder in storage_serverlet

include/dsn/dist/replication/replication_types.h, src/dist/replication/common/replication_types.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.h, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp, src/dist/replication/replication.thrift, src/dist/replication/test/replica_test/unit_test/mock_utils.h
The whole bulk load succeed process is like:
1. meta server set app and all partitions bulk load status is succeed #500 
2. meta server send bulk_load_request to primary #457
3. **primary handle bulk_load_request**
4. primary broadcast request to secondary #460
5. **secondary handle bulk_load_request**
6. **secondary report cleanup flag to primary**
7. **primary report group cleanup flag  to meta server**
8. meta handle bulk load succeed
This pull request is about replica handle bulk load succeed, step 3,5,6,7 above.
- **handle bulk_load_request in function `do_bulk_load`**
- when request status is succeed, local status is ingesting, will call `handle_bulk_load_succeed`
- when request status is succeed, local status is succeed, will call `handle_bulk_load_finish`
- both primary and …
=> feat(bulk-load): bulk load succeed part1 - replica handle bulk load succeed

src/dist/replication/meta_server/meta_bulk_load_service.cpp, src/dist/replication/meta_server/meta_bulk_load_service.h, src/dist/replication/test/meta_test/unit_test/meta_bulk_load_service_test.cpp
The whole bulk load succeed process is like:
1. meta server set app and all partitions bulk load status is succeed #500 
2. meta server send bulk_load_request to primary #457
3. primary handle bulk_load_request #502 
4. primary broadcast request to secondary #460
5. secondary handle bulk_load_request #502 
6. secondary report cleanup flag to primary #502 
7. primary report group cleanup flag  to meta server #502 
8. **meta handle bulk load succeed**
This pull request is about meta handle bulk load succeed, step 8 above.
meta handle bulk_load_response in `handle_bulk_load_finish`
- if all replicas in group cleaned up bulk load state, set `_partitions_cleaned_up[pid] = true` and `_apps_in_progress_count[app_id] - 1`
- if all partitions cleaned up, remove bulk load directory(in function …
=> feat(bulk-load): bulk load succeed part2 - meta handle bulk load succeed

src/dist/replication/lib/replica_stub.cpp
https://github.com/XiaoMi/pegasus/issues/552
We found the shared log may be incomplete after one replica_server node down and restart,  for avoid some unexpected problem,  this pr `dassert` the case.  it can help us find problem in time when error happens.
=> fix: dassert if shared log is damaged when replica server init

src/dist/replication/lib/replica_stub.cpp
#513 think when shared log damaged because of node crash, we should forbid to restart it to avoid unexpected problem. however, since the the shared log usually wouldn't flush disk in time but private log do, so the `shared log != private log` case is common. In this case, restart failed will be frequently, which is not our expected.
After revert the commit, if shared log damaged, pegasus server will try reply from private log. But It do should be note that  private log may be not coincident. 
Consider the two above case, we prefer to avoid restart failed when the node server crash, so we choose revert the commit.
=> fix: revert "dassert if shared log is damaged when replica server init" commit

src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.h, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp, src/dist/replication/meta_server/meta_bulk_load_service.cpp, src/dist/replication/test/meta_test/unit_test/meta_bulk_load_service_test.cpp
Pause bulk load process is like:
1. client sends pause request to meta server, and meta server update app and partitions' bulk load status to pausing #514
2. meta server still broadcast pause bulk load to replica server through `bulk_load_request`  #457 
3. **primary handle bulk_load_request**
4. primary broadcast request to secondary #460
5. **secondary handle bulk_load_request**
6. **secondary report is_paused flag to primary**
7. **primary report group is_paused flag to meta server**
8. **meta handle bulk load paused**
This pull request is about the remaining part of the process.
-  replica handle bulk_load_request
- when bulk load status of request is  `pausing`, replica will try to cleanup all downloading tasks and turn status to `paused` (in function `pause_bulk_load`)
- secondary …
=> feat(bulk-load): pause bulk load part2 - implement bulk load pause

include/dsn/tool-api/command_manager.h, include/dsn/tool-api/global_config.h, src/core/core/command_manager.cpp, src/core/tools/common/nativerun.cpp, src/core/tools/simulator/simulator.cpp, src/dist/failure_detector/failure_detector.cpp, src/dist/nfs/nfs_client_impl.cpp, src/dist/replication/lib/replica_stub.cpp, src/dist/replication/lib/replica_stub.h, src/dist/replication/meta_server/greedy_load_balancer.cpp, src/dist/replication/meta_server/meta_service.cpp, src/dist/replication/meta_server/server_load_balancer.cpp, src/dist/replication/meta_server/server_state.cpp
In command_manager, `command_manager::register_app_command` needs app_name which is get from dsn_runtime. In this pull request, we want to let command_manager decoupled from dsn_runtime, so I delete this function, and use `command_manager::register_command` instead.
=> refactor: make command manager decoupled from dsn_runtime

bin/dsn.cmake
It will be easier to update thirdparty/rocksdb, no need to change path in CMakeLists.
=> build: use regex to find rocksdb depend module path

src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp, src/dist/replication/meta_server/meta_bulk_load_service.cpp, src/dist/replication/test/meta_test/unit_test/meta_bulk_load_service_test.cpp
This pull request is about cancel bulk load by client.
1. client send cancel/force_cancel request to meta server #514 
2. meta server handle cancel bulk load
- cancel bulk load is only allowed when current bulk load status is downloading or paused, while force bulk load has no limit, however, force bulk load may lead to consistency problem, some data may have ingested while some data may not (in function `on_control_bulk_load`)
- update app bulk load status to canceled (in function `update_app_status_on_remote_storage_reply`)
- update each partition status to canceled, and if old status is paused, should set `should_send_request` = true to resend bulk_load_request, for other status, request will be resent in function `on_partition_bulk_load_reply` #482 
3. replica server receive …
=> feat(bulk-load): cancel bulk load

src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp, src/dist/replication/meta_server/meta_bulk_load_service.cpp, src/dist/replication/meta_server/meta_bulk_load_service.h, src/dist/replication/test/meta_test/unit_test/meta_bulk_load_service_test.cpp
This pull request is about handle bulk load failed and app unavailable during bulk load.
**bulk load failed**
1. when bulk load meet unrecoverable errors such as file on remote storage is corrupted, bulk load process will be considered as failed, call function `handle_bulk_load_failed`
- update app bulk load status to failed (in function `update_app_status_on_remote_storage_reply`)
- update each partition status to failed #482
- send bulk_load_request to replica server #457 
2. replica server receive bulk_load_request during failed
- when replica receive request whose status is failed, will call function handle_bulk_load_finish to cleanup bulk load (in function `do_bulk_load`)
- secondary reports cleaned up flag to primary (in function `report_bulk_load_states_to_primary`)
- primary …
=> feat(bulk-load): handle bulk load failed and app unavailable

include/dsn/tool-api/logging_provider.h, src/core/core/logging.cpp, src/core/core/service_api_c.cpp, src/core/tools/common/simple_logger.cpp, src/core/tools/common/simple_logger.h
In `simple_logger.cpp`, function `print_header` calls `dsn::task::get_current_node_name()` and `dsn::task::get_current_worker2()>pool_spec().name.c_str()`, which are coupled with dsn_runtime.
=> refactor: make simple logger decoupled from dsn_runtime

src/dist/replication/lib/bulk_load/replica_bulk_loader.cpp, src/dist/replication/lib/bulk_load/replica_bulk_loader.h, src/dist/replication/lib/bulk_load/test/replica_bulk_loader_test.cpp, src/dist/replication/lib/replica_config.cpp, src/dist/replication/lib/replica_context.cpp, src/dist/replication/lib/replica_context.h, src/dist/replication/test/replica_test/unit_test/mock_utils.h
As previous pull requests shows, bulk load process is like:
1. meta sends bulk load request to primary replica to let primary replica executing bulk load (#457)
2. primary replica broadcasts group_bulk_load_request to secondaries to let secondary replicas executing bulk load (#460)
3. secondary replica reports its bulk_load_state through group_bulk_load_response (#479)
4. primary replica reports group bulk_load_state through bulk_load_response (#479)
This pull request is about how replica handle errors during bulk load process, including two parts:
1. primary meet errors while receiving `group_bulk_load_response`
- primary stores secondary bulk load state in primary context, when meet errors, primary should reset this secondary's state (in function `on_group_bulk_load_reply` and …
=> feat(bulk-load): replica handle errors during bulk load

compile_thrift.py
In pr(#550 ), I forget to change the output directory of  `_types.cpp`. It will produce compile thrift error.
=> fix: fix compile thrift error in compile_thrift.py

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp
When meta server crash during bulk load, meta server will sync bulk load info from remote storage (#553), then do validation before continue bulk load(#559), this pull request will continue app bulk load process.
=> feat(bulk-load): continue bulk load while meta server start part2

src/meta/meta_bulk_load_service.cpp, src/meta/meta_state_service_simple.cpp
For zk `node_exist` interface, if node not exist, it will return error `ERR_OBJECT_NOT_FOUND`, for mock remote storage, it will return error `ERR_PATH_NOT_FOUND`.
In previous implementation, I use `ERR_PATH_NOT_FOUND`, however, we should use `ERR_OBJECT_NOT_FOUND`. This pull request fix this bug and update error code for mock remote storage.
=> fix(bulk-load): fix bug while check app bulk load states

src/meta/meta_data.h, src/meta/server_state.cpp, src/meta/test/meta_app_envs_test.cpp, src/meta/test/meta_bulk_load_service_test.cpp, src/meta/test/meta_http_service_test.cpp, src/meta/test/meta_service_test.cpp, src/meta/test/meta_split_service_test.cpp, src/meta/test/meta_test_base.cpp, src/meta/test/meta_test_base.h
This PR reduce the compilation work of meta tests by moving the impl of class `meta_test_base` to `meta_test_base.cpp`.
There're many unit testing files for meta server (under `srv/meta/test`), every of them includes `meta_test_base.h`, then indirectly includes many headers that it depends:
```cpp
#include "meta/server_load_balancer.h"
#include "meta/meta_server_failure_detector.h"
#include "meta/meta_split_service.h"
#include "meta/meta_bulk_load_service.h"
#include "meta/test/misc/misc.h"
#include <dsn/dist/replication/replication_types.h>
#include "meta_service_test_app.h"
#include "meta/meta_data.h"
```
For example, take a look at a simple test `src/meta/test/meta_service_test.cpp`.  Apparently some of them like  "meta/meta_bulk_load_service.h"  "meta/meta_split_service.h" are …
=> refactor: reduce compilation size for building each meta test

src/meta/server_state.cpp
Pull request #571 add a check for load balance, apps who are executing bulk load should not be balanced. However, it raises a bug that the apps who are executing bulk load won't add secondary. This pull request fix this bug.
=> fix(bulk-load): fix bug while check_all_partitions

include/dsn/cpp/pipeline.h, src/aio/native_linux_aio_provider.cpp, src/block_service/block_service_manager.cpp, src/meta/meta_bulk_load_service.cpp, src/meta/meta_rpc_types.h, src/meta/meta_service.h, src/meta/test/meta_bulk_load_service_test.cpp, src/replica/duplication/duplication_pipeline.h, src/replica/duplication/load_from_private_log.h, src/replica/duplication/test/duplication_test_base.h, src/replica/duplication/test/ship_mutation_test.cpp, src/replica/replica_split.cpp, src/replica/replica_stub.cpp, src/replica/test/mutation_log_test.cpp, src/replica/test/replica_test_base.h, src/utils/test/autoref_ptr_test.cpp
This PR I try to fix all compilation errors using clang-9/clang++-9, which generates much more detailed information and code style checks than GCC. I plan to add clang-9 building as a Travis-CI test. Suppressing the errors is my first step.
=> fix: fix building errors by clang-9

src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/replica_bulk_loader.h, src/replica/replica_config.cpp
This pull request fix the bug about function `clear_bulk_load_states_if_needed`, it will be called by `update_local_configuration` when replica configuration changed. This function will compare current partition status and new_status in new configuration, if new_status is primary or secondary and current status is not two status, will clear bulk load states. However, when this function is called, the current status has already be updated to new_status, `status()` will always be equal to `new_status`, which will lead bulk load states not cleaned up in this condition.
To fix this bug, this pull request adds another parameter `old_status` for this function, which is the real partition status before updating configuration.
=> fix(bulk_load): fix bug of clear_bulk_load_states_if_needed

src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/replica_bulk_loader.h, src/replica/bulk_load/test/replica_bulk_loader_test.cpp, src/replica/replica_config.cpp
This pull request fix the bug about concurrent bulk load downloading replica count.
The bug will be raised when bulk load failed or paused. In previous implementation, when bulk load failed or paused, if original status is downloading, we will decrease this count. However, the partition may be not doing exact downloading. For example, the max count is 5, this stub already have 5 partitions executing downloading, besides there are 8 partitions waiting for downloading, one of them meet unrecoverable error so the whole bulk load process failed, all 13 partition will try to decrease the count, which leads to wrong count -8.
To fix this bug, this pull request adds a `is_downloading` variety, only the partition who is executing downloading will decrease this count. Besides, this pull request …
=> fix(bulk-load): fix bug about concurrent downloading count

src/meta/meta_bulk_load_service.cpp, src/meta/test/meta_bulk_load_service_test.cpp, src/replica/replica_2pc.cpp
This pull request fixs the bug of bulk load ingestion.
In previous implementation, when replica is executing ingestion request, it will reject normal write request by returning `ERR_OPERATION_DISABLED`. When replica received repeated ingestion request, it will also return `ERR_OPERATION_DISABLED`, meta will rollback to downloading if receiving a response with this error code. However, meta needn't to rollback to downloading, it should just wait for this ingestion. This pull request separates those different case. When replica is executing ingestion request, if it receives normal write request, it will still return `ERR_OPERATION_DISABLED` to user client, if it receives repeated ingestion request, it will return `ERR_NO_NEED_OPERATE` to meta server, meta server will ignore this repeated …
=> fix(bulk-load): fix bug during ingestion

src/http/http_message_parser.cpp, src/http/http_message_parser.h, src/http/test/http_server_test.cpp
rDSN `http_server` currently ignores entirely the HTTP body, headers, except for URL query-params. Therefore, only URL could be used for the HTTP-client to send arguments.
```sh
127.0.0.1/meta/app_envs?name=<app_name> # we can only use query-params as the request's arguments
```
In order to support serving HTTP post-form ("application/x-www-form-urlencoded")  requests, our HTTP server must be able to parse "Content-Type" field in the HTTP header.
```sh
~ $ http --form -v POST httpbin.org/post hello=world
POST /post HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 11
Content-Type: application/x-www-form-urlencoded; charset=utf-8 # post-form 
Host: httpbin.org
User-Agent: HTTPie/2.1.0
```
So in this PR, I add support to parse "Content-Type" in rdsn …
=> feat(http): support parsing content-type of HTTP request

src/runtime/security/server_negotiation.cpp, src/runtime/security/server_negotiation.h
select a mechanism which is supported by both server and client.
negotiation process:
```
client                             server
|---    SASL_LIST_MECHANISMS     -->|
|<--  SASL_LIST_MECHANISMS_RESP  ---|
|---   SASL_SELECT_MECHANISMS   --->|
|<-- SASL_SELECT_MECHANISMS_RESP ---|
|                                   |
|------     SASL_INITIATE    ------>|
|                                   |
|<----      SASL_CHALLENGE     -----|
|-----       SASL_RESPONSE     ---->|
|                                   |
|               .....               |
|                                   |
|<----      SASL_CHALLENGE     -----|
|-----       SASL_RESPONSE     ---->|
|                                   |        (authentication will succeed
|                                   |        if all …
```
=> feat(security): select mechanism

src/runtime/security/client_negotiation.cpp, src/runtime/security/client_negotiation.h, src/runtime/security/negotiation.cpp, src/runtime/security/negotiation.h, src/runtime/security/server_negotiation.cpp, src/runtime/security/server_negotiation.h
In previous implementation, when something is wrong in `server_negotiation`, it send a message to `client_negotiation`, and the `client_negotiation` will close the connection when it receives the message.
So I think we can directly close the connection in this case, no need to send a message.
=> refactor(security): close the connection when something is wrong with sever_negotiation

.gitignore, scripts/linux/build.sh, src/runtime/core_main.cpp
If we download the sources from github releases rather than using git clone, the git commit of rdsn will be missing. Because in this case rdsn is not a git repo. However, `DSN_GIT_COMMIT` relies strongly with the fact that rdsn is a git repo. This is not always be true.
In this PR I deleted include/dsn/git_commit.h and `DSN_GIT_COMMIT`. It has no effect.
```
wget https://codeload.github.com/neverchanje/rdsn/zip/gcid
unzip rdsn-gcid
cd rdsn-gcid
./run.sh build -c -j 4
```
All success.
=> chore: remove usages of rdsn git commit

src/runtime/security/sasl_server_wrapper.cpp, src/runtime/security/server_negotiation.cpp, src/runtime/security/server_negotiation.h, src/runtime/test/server_negotiation_test.cpp
server_negotiation handle challenge response from client_negotiation
```
negotiation process:
client                             server
|---   SASL_LIST_MECHANISMS    -->|
|<-- SASL_LIST_MECHANISMS_RESP ---|
|---  SASL_SELECT_MECHANISMS  --->|
|<-- SASL_SELECT_MECHANISMS_OK ---|
|                                 |
|------    SASL_INITIATE   ------>|
|                                 |
|<----     SASL_CHALLENGE    -----|
|-----      SASL_RESPONSE    ---->|
|                                 |
|              .....              |
|                                 |
|<----     SASL_CHALLENGE    -----|
|-----      SASL_RESPONSE    ---->|
|                                 |        (authentication will succeed
|                                 |        if all chanllenges passed)
| <--- …
```
=> feat(security): server_negotiation handle challenge response

include/dsn/utils/latency_tracer.h, src/replica/mutation.cpp, src/utils/latency_tracer.cpp, src/utils/test/latency_tracer_test.cpp
`_is_sub` control whether to dump the point when deconstructer, if one tracer isn't marked as `is_sub` at initialization, but wait `set_sub_tracer`, which will cause tracer that hoped `is_sub` but not be `set_sub_tracer` dump points. for example, `learn` and `log write` process will create `aio_task`, but only `log write` process `set_sub_tracer`,  the result is that `aio_task` of `learn` will dump points, which is not expected. So if we hope one tracer `is_sub`, we should init it at first constructer
=> fix: set the tracer type when init

src/replica/CMakeLists.txt, src/replica/backup/replica_backup_manager.cpp, src/replica/backup/replica_backup_manager.h, src/replica/backup/replica_backup_server.cpp, src/replica/backup/replica_backup_server.h, src/replica/replica_stub.cpp, src/replica/replica_stub.h
This PR extracts the rpc handling (`register_rpc_hander`) code of backup to `replica_backup_server`. It intends to reduce the responsibility of `replica_stub` and improve the overall modularity of cold backup.
=> refactor(backup): move backup rpc handling to replica_backup_server

src/block_service/fds/fds_service.cpp, src/block_service/fds/fds_service.h
This patch doesn't contain any functional changes.
=> refactor(fds_service): clean up duplicate code

src/runtime/security/client_negotiation.cpp, src/runtime/security/negotiation_service.cpp, src/runtime/security/server_negotiation.cpp, src/runtime/test/negotiation_service_test.cpp
In previous implementation, if message is not in white list and negotiation is not succeed, the message is not allowed to send or receive. But this will produce error when rolling update.
For example: the `enable_auth` configuration of client session is false, and it is true on the server session side. So client session will not do negotiation work with server session. And when the server session receives one message from this client session , it will close this session connection because this message is not in white list and the negotiation is not succeed. 
In this pr, I make send/recv message allowed when mandatory_auth is false, so the message will be received successully in this situation. This will make our rolling update work to proceed smoothly.
=> refactor(security): make send/recv message allowed when mandatory_auth is false

src/replica/split/replica_split_manager.cpp, src/replica/split/replica_split_manager.h
This pull request is about `replica_split_manager`, including:
- update some log and comments
- update rpc call
=> feat(split): small refactor and fix of replica split

include/dsn/dist/replication/replication_ddl_client.h, src/client/replication_ddl_client.cpp, src/common/replication_common.h, src/meta/meta_rpc_types.h
This function add a ddl interface `start_partition_split`, it will send start_split_rpc to meta server.
=> feat(split): add ddl interface start_partition_split

src/replica/replica_config.cpp, src/replica/split/replica_split_manager.cpp, src/replica/split/test/replica_split_test.cpp
If parent partition configuration changed or meet other error during partition split, the split process should be stopped, child partition status will turn from `partition_split` to `error` (this has been implemented in #391), this pull request only calls it in function `child_handle_split_error` and updates some unit tests.
=> feat(split): implement child_handle_split_error

include/dsn/dist/replication/replication_enums.h, include/dsn/dist/replication/replication_types.h, src/common/replication_types.cpp, src/meta/meta_data.h, src/meta/meta_split_service.cpp, src/meta/test/meta_split_service_test.cpp, src/replica/split/replica_split_manager.cpp, src/replica/split/replica_split_manager.h, src/replica/split/test/replica_split_test.cpp, src/replication.thrift
This pull request adds two sturctures to show split status.
Define five split_status for partition (not_split, splitting, pausing, paused, canceling), both replica and meta will use it.
- For replica, we used to use `_child_gpid` to distinguish whether a replica is executing splitting, if `_child_gpid.get_app_id() > 0`, the replica is splitting, otherwise not. It can only show two split status. Now, we use `_split_status` to describe partition split status.
- For meta, see split_state
Define sturct `split_state` to show app split progress, this sturcture include splitting partition count and each split_status for those splitting partitions. If `splitting_count = 0`, it means current app is not splitting or has finished splitting. 
This sturcture is helpful to query app split progress and …
=> feat(split): add split_status

src/runtime/test/netprovider.cpp
As [pegasus issue 567](https://github.com/apache/incubator-pegasus/issues/567) shows, there are some unit tests are time-cosuming, ` tools_common.asio_network_provider_connection_threshold` is one of them, it will cost 70017ms. This pull request is a refactor of this unit test to reduce its executing time, it will cost 2077ms to run this unit test.
=> refactor: reduce netprovider unit test executing time

src/replica/replica_check.cpp, src/replica/split/replica_split_manager.cpp, src/replica/split/replica_split_manager.h, src/replica/split/test/replica_split_test.cpp
1. meta receives client partition split request, and change partition count #286
2. replica notices partition count changed during on_config_sync #653 
3. parent partition create child partition #291
4. parent prepare states for child to learn #299
5. child partition async learn states from parent #309 #319
6. child notify parent catch up #390
7. update child group partition count #645 
8. register child partition #391
9. **update parent group partition count**
More partition split discussion in issue #69 and partition split design doc
This pr solves the part of ninth step of partition split, which is bold in process description.
When primary parent registers child succeed, it will update its own partition_count, then broadcast this to secondary through group_check. Besides, this pull …
=> feat(split): parent group update partition count

src/block_service/block_service_manager.cpp, src/block_service/block_service_manager.h, src/meta/meta_backup_service.cpp, src/meta/meta_backup_service.h, src/meta/meta_bulk_load_service.cpp, src/meta/server_state_restore.cpp, src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/replica_backup.cpp, src/replica/replica_restore.cpp
The way we determine whether a backup provider is valid is to construct a `block_service_manager` and destroy it, which is not reasonable and may cause problems when use hdfs as backup provider.
=> fix(backup): use existing block_service_manager when add backup policy

src/http/http_message_parser.cpp, src/http/http_message_parser.h, src/http/http_server.cpp, src/http/test/http_server_test.cpp
In previous pr #593, http server can parse content-type of HTTP request. The incoming http request will parse into message_ex structure, msg->buffers[3] indicate the content-type, the msg->buffers will be resized as 4. When parsing message into http _request, the size of buffers will be checked. However, function `parse` still consider the right size of buffers is 3, it will reject all requests. This pull request fix it, add BUFFER_SIZE and update related unit tests.
=> fix(http): fix message buffers size check

src/http/http_server.cpp, src/http/test/http_server_test.cpp
In #594, it simplified http path, but it left a problem. For example:
The http request sent to meta server to list all apps is like `ip:port/meta/apps`, http server will add a tuple like `<'meta/apps', 'apps_handler'>`, when server receives a http request, it will parse path from request, and find the handler by path. 
In current implementation, the registered path is like `meta/apps`, and the path parsed from request is `/meta/apps`, as a result, the handler can not be found. 
This pr fix this problem, the path parsed from request will be `meta/apps` as the implementation before #594.
=> fix(http): fix parse path from message

thirdparty/CMakeLists.txt
The pull request #666 updates thirdparty fmtlib from 4.0.0 to latest 7.1.2, the later version will lead to compile error for gcc 5.4.0. This pull request updates fmtlib version to 5.3.0, the latest version who would not lead to compile problem.
=> thirdparty: update fmtlib

src/utils/time_utils.cpp, thirdparty/CMakeLists.txt
time_utils.cpp was unable to compile because of the rollback of fmtlib in this PR https://github.com/XiaoMi/rdsn/pull/671.
Because in fmtlib <6.x versions, we need `fmt/time.h` to be included together for time format. This file was removed for 6.x+ versions.
=> fix: fmtlib incompatibility problems from 7.1.3 to 5.3.0

include/dsn/tool-api/aio_task.h, src/aio/aio_provider.cpp, src/aio/aio_provider.h, src/aio/disk_engine.cpp, src/aio/disk_engine.h, src/aio/sim_aio_provider.cpp
`aio_task::support_write_vec` is initiated to false, and nowhere it's set to true. So I remove this variable to make the code clear.
=> refactor: remove support_write_vec in aio_task

src/runtime/security/replica_access_controller.cpp, src/runtime/test/replica_access_controller_test.cpp, src/utils/test/utils.cpp
enable access replica when appenv `replica_access_controller.allowed_users` is empty.
So the access to replica is enabled when the appenv is not set.
=> feat(security): enable access replica when appenv `replica_access_controller.allowed_users` is empty

thirdparty/CMakeLists.txt
```
src/zookeeper.c: In function 'format_endpoint_info':
src/zookeeper.c:3469:21: error: '%d' directive writing between 1 and 5 bytes into a region of size between 0 and 127 [-Werror=format-overflow=]
3469 |     sprintf(buf,"%s:%d",addrstr,ntohs(port));
|                     ^~
src/zookeeper.c:3469:17: note: directive argument in the range [0, 65535]
3469 |     sprintf(buf,"%s:%d",addrstr,ntohs(port));
|                 ^~~~~~~
In file included from /usr/include/stdio.h:867,
from ./include/zookeeper.h:29,
from src/zookeeper.c:27:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: '__builtin___sprintf_chk' output between 3 and 134 bytes into a destination of size 128
36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
| …
```
=> fix: compile error of zookeeper 3.4.10 on gcc9

include/dsn/dist/replication/replication_ddl_client.h, include/dsn/dist/replication/replication_types.h, src/client/replication_ddl_client.cpp, src/common/replication_common.cpp, src/common/replication_common.h, src/common/replication_types.cpp, src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp, src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/replica_bulk_loader.h, src/replica/bulk_load/test/replica_bulk_loader_test.cpp, src/replication.thrift
In previous implementation, bulk load will download files from specific remote storage path, which is defined in config file, name is `bulk_load_provider_root`. This pull request removes this config, and adds `remote_root_path` for starting bulk load request, server will use it as the root path of remote file storage.
=> feat(bulk-load): support user-define remote storage root path

include/dsn/utility/defer.h, src/utils/test/time_utils_test.cpp, thirdparty/CMakeLists.txt
https://github.com/XiaoMi/rdsn/pull/685 introduces a compilation flag "CFLAGS=-Wno-error=format-overflow" to suppress integer overflow errors of zookeeper-c-client.
```cmake
ExternalProject_Add(zookeeper
URL ${OSS_URL_PREFIX}/zookeeper-3.4.10.tar.gz
http://ftp.jaist.ac.jp/pub/apache/zookeeper/zookeeper-3.4.10/zookeeper-3.4.10.tar.gz
URL_MD5 e4cf1b1593ca870bf1c7a75188f09678
CONFIGURE_COMMAND cd src/c && CFLAGS=-Wno-error=format-overflow ./configure --enable-static=yes --enable-shared=no --prefix=${TP_OUTPUT} --with-pic=yes
BUILD_COMMAND cd src/c && make
INSTALL_COMMAND cd src/c && make install
BUILD_IN_SOURCE 1
)
```
"format-overflow" was introduced in gcc-7 https://gcc.gnu.org/gcc-7/changes.html. But lower-version compilers unrecognized with this flag will fail. So I use …
=> fix: zk compile cflag no warn format errors

bin/dsn.cmake
Fix compilation errors in the context of ubuntu dev environment.
=> fix(hdfs): fix 'libjvm.so not found' error

include/dsn/utility/defer.h, src/runtime/security/client_negotiation.cpp
When you rolling_update a cluster, if the new config set enable_auth = true. The new version server will send negotiation message to the server which has old version. And it will return `ERR_HANDLER_NOT_FOUND` to the new version server, so the negotiation will always fail.
=> feat(security): treat negotiation succeed if server is old version

src/meta/meta_bulk_load_service.cpp, src/meta/meta_http_service.cpp, src/meta/meta_http_service.h, src/meta/test/meta_http_service_test.cpp
This pull request adds a new http interface for meta server to start bulk load.
=> feat(bulk_load): add start bulk load http interface

src/block_service/block_service_manager.cpp, src/block_service/test/block_service_manager_test.cpp, src/block_service/test/block_service_mock.h
As the title shows, this pull request add check in `download_file`, when local file only has same file name with remote file, local file will be removed, and download from remote file provider. Besides, when local file is same as remote file, it will set `download_file_size` as file size.
=> fix(block_service): download file when local file is different from remote file

scripts/linux/clear_zk.sh, scripts/linux/start_zk.sh, scripts/linux/stop_zk.sh
#658 updates zk version in `start_zk.sh`, however it left some version not changed, this pr fix it.
=> fix(scripts): fix zk version in zk scripts

src/meta/meta_http_service.cpp, src/meta/meta_http_service.h, src/meta/test/meta_http_service_test.cpp
This pull request adds the http interface for meta server to update app_envs of manual_compaction.
=> feat(bulk_load): add update compaction envs http interface

src/runtime/security/client_negotiation.cpp, src/runtime/security/negotiation_manager.cpp, src/runtime/test/client_negotiation_test.cpp, src/runtime/test/negotiation_manager_test.cpp
remove mandatory_auth on client side, keep same with java client.
For `on_rpc_send_msg ` function, there are two cases when `mandatory_auth` is false:
1. enable_auth = false. In this case, the `on_rpc_send_msg` joint point will not be added to `on_rpc_send_message`. So this function will not be excuted.
2. enable_auth = true. In this case, I think we should send nothing before negotiation succeed. So this rule is broken in previous implementation if we don't remove the mandatory_auth.
So I remove mandatory_auth in this pull request, making it a server-side config.
=> fix(security): remove mandatory_auth on client side

src/meta/meta_http_service.cpp, src/meta/meta_http_service.h, src/meta/test/meta_http_service_test.cpp
This pull request adds update rocksdb scenario envs interface for meta server.
=> feat: add update rocksdb scenario interface

run.sh, thirdparty/CMakeLists.txt
The process exits with "Illegal instruction (core dumped)" while trying to launch pegasus server on certain nodes. By trouble-shooting, we find "PORTABLE" is disabled while rocksdb is built. The pegasus server can be built and run normally on standard nodes with "PORTABLE" disabled. However, hardware varies in some other nodes where certain instructions are not supported. We have to achieve portability for these nodes at the cost of a little of performance.
=> feat: support to build a portable rocksdb binary

src/replica/replica.cpp, src/replica/replica.h, src/replica/replica_http_service.cpp, src/replica/replica_http_service.h, src/replica/replica_stub.cpp, src/replica/replica_stub.h, src/replica/test/replica_test.cpp
This pull request adds replica http interface for query app compaction status.
=> feat(bulk_load): add query compaction status http interface

src/replica/replica_http_service.cpp, src/replica/replica_stub.cpp, src/replica/replica_stub.h, src/replica/test/replica_test.cpp
PR #706 support the replica http interface to query app data_version, it will return data_version of any partition for the app, however, it is possible for partitions have different data_version. This pr fix it, return <pidx, data_version> map instead.
=> feat: update query partition data version

CMakeLists.txt, src/runtime/security/client_negotiation.cpp, src/runtime/security/negotiation_manager.cpp, src/runtime/test/negotiation_manager_test.cpp
In pr(https://github.com/XiaoMi/rdsn/pull/708), I remove mandatory_auth on client_side. But I forgot that both `on_rpc_recv_msg` and `on_rpc_recv_msg` will be called by both server and client session. So in this pull request, I fix it to make mandatory_auth to be a server side config.
I have tested all of the cases below for this pr:
server | server | server | client | client | expected result | test result
-- | -- | -- | -- | -- | -- | -- 
support security | enable_auth | mandatory_auth | support security | enable_auth
no | - | - | yes | TRUE | √ | √
no | - | - | yes | FALSE | √ | √
yes | FALSE | - | no | - | √ | √
yes | TRUE | FALSE | no | - | √ | √
yes | TRUE | TRUE | no | - | × | ×
server | server |  client | expected result | test result
-- | -- | -- | -- | --
enable_auth | …
=> fix(security): make mandatory_auth to be a server side config

src/common/backup_utils.cpp, src/common/backup_utils.h, src/meta/meta_backup_service.cpp, src/meta/server_state_restore.cpp, src/replica/backup/cold_backup_context.cpp, src/replica/backup/replica_backup_manager.cpp, src/replica/replica_restore.cpp, src/replica/test/cold_backup_context_test.cpp
This patch remove `policy_name` from backup files' path.
If we want to restore apps which is backed up in this new way, we don't need to use `-p` to specify the `policy_name`. If we want to restore old apps, we could also use `-p`.
I have tested this using onebox cluster, backup and restore some apps, all works well.
=> BREAKING CHANGE(backup): remove 'policy_name' from backup files' path

include/dsn/utility/flags.h, src/http/builtin_http_calls.cpp, src/http/builtin_http_calls.h, src/http/config_http_service.cpp, src/utils/flags.cpp
add a http interface to get all configs
1. Start onebox
2. use http://localhost:34601/listAllConfigs to get all the configs, the result shows:
```
{"abnormal_write_trace_latency_threshold":"{\"name\":\"abnormal_write_trace_latency_threshold\",\"section\":\"replication\",\"type\":\"4\",\"tags\":\"\",\"description\":\"latency trace will be logged when exceed the write latency threshold\",\"value\":\"1000000000\"}\n","aio_factory_name":"{\"name\":\"aio_factory_name\",\"section\":\"core\",\"type\":\"6\",\"tags\":\"\",\"description\":\"asynchonous file system provider\",\"value\":\"dsn::tools::native_aio_provider\"}\n","capacity_unit_saving_ttl_days":"{\"name\":\"capacity_unit_saving_ttl_days\",\"section\":\"pegasus.collector\",\"type\":\"1\",\"tags\":\"\",\"description\":\"the ttl of the CU …
```
=> feat: add http interface to get all configs

src/meta/meta_backup_service.cpp, src/meta/meta_backup_service.h, src/meta/test/backup_test.cpp
This patch did some refactoring:
1. refactor `add_backup_policy()`, if a policy contains invalid app/backup_interval/backup_probider/policy_name, meta would response `ERR_INVALID_PARAMETERS` and return.
2. remove `backup_requests` from `backup_progress`, which was not used in backup service.
3. improve tests, log messages and comments.
=> refactor(backup): refactor add_backup_policy

include/dsn/utility/flags.h, src/http/builtin_http_calls.cpp, src/http/builtin_http_calls.h, src/http/config_http_service.cpp, src/utils/flags.cpp, src/utils/test/flag_test.cpp
add http interface to get a specified config
***TEST***
request:
```http://localhost:34801/config?name=abnormal_write_trace_latency_threshold```
response: 
```
{"name":"abnormal_write_trace_latency_threshold","section":"replication","type":"FV_UINT64","tags":"","description":"latency trace will be logged when exceed the write latency threshold","value":"1000000000"}
```
=> feat: add http interface to get a specified config

src/block_service/hdfs/hdfs_service.cpp, src/block_service/hdfs/hdfs_service.h
This pull request adds folly read limiter for hdfs, different from fds implementation, this pr uses `BasicDynamicTokenBucket` provided by folly to make it thread-safe to update limiter size dynamically.
- Unit test
- Manual test
I depoly one server supporting limiter(100M), the rest servers don't support limiter executing bulk load from hdfs, the result like the graph shows:
I also update limiter size dynamically: 100M -> 200M -> 50M
```diff
+ [replication]
+ hdfs_read_limit_rate_megabytes = 200
```
=> feat: add read limiter for hdfs

src/client/partition_resolver.cpp, src/common/duplication_common.cpp
1. Don't resend message if it is rejected by server.  because it means that the server is overload if it reject this message. So if we resend the message, it will makes the situation even worse.
2. use cflags to define cluster_name. But we can't use flag validator, because cpp client will not set cluster name. so the validator will always fail for it
=> refactor: don't resend message if it is rejected by server

include/dsn/utility/TokenBucket.h, include/dsn/utils/time_utils.h, src/aio/test/aio.cpp, src/runtime/rpc/rpc_message.cpp, src/utils/logging.cpp, src/utils/simple_logger.cpp, src/utils/test/priority_queue.cpp, src/utils/time_utils.cpp
```
std::function<std::string()> log_prefixed_message_func = []() {
static thread_local std::string prefixed_message;
static thread_local std::once_flag flag;
std::call_once(flag, [&]() {
prefixed_message.resize(23);
int tid = dsn::utils::get_current_tid();
sprintf(const_cast<char *>(prefixed_message.c_str()), "unknown.io-thrd.%05d: ", tid);
});
return prefixed_message;
```
This function prepends "unknown.io-thrd.<thread id>: " to every line of our log when the rdsn runtime is not set up.
But this prefix has no useful meaning, as tid is also logged via `static void print_header(FILE *fp, dsn_log_level_t log_level)
`.  So I here simplify this function to output ": " instead.
This function has a mem-leak that the thread-local "prefixed_message" will be freed even when …
=> fix: multiple asan errors

src/runtime/rpc/rpc_message.cpp
Function `copy_message_no_reply` will be used during partition split when child copy parent's mutation, its header should not be an empty structure.
=> fix(split): message header should not be empty struct

src/replica/test/log_block_test.cpp, src/replica/test/replica_test_base.h
In function `create_test_mutation`, it uses `const std::string &data`as it's second param. And gets the pointer of data, reserving it. But the caller of `create_test_mutation` may release variable `data`. So the `mu` will reserves a wild pointer in this case. and the use of the reserved pointers will produce `heap-use-after-free` error.
=> fix(asan):  heap-use-after-free caused by replica_test_base::create_test_mutation

src/replica/storage/simple_kv/test/checker.cpp, src/runtime/service_api_c.cpp, src/runtime/tool_api.cpp
In latest tests I found that we try to destroy `service_node` repeatly when exiting pegasus process.
coredump stack:(see frame 54 and 26)
```
#0  0x00007f48ef7221d7 in raise () from /lib64/libc.so.6
#1  0x00007f48ef7238c8 in abort () from /lib64/libc.so.6
#2  0x00007f48f1588ceb in tcmalloc::Log (mode=mode@entry=tcmalloc::kCrash, filename=filename@entry=0x7f48f15a0336 "src/tcmalloc.cc", line=line@entry=332, a=…, b=…, c=…, d=…)
at src/internal_logging.cc:118
#3  0x00007f48f157a797 in (anonymous namespace)::InvalidFree (ptr=<optimized out>) at src/tcmalloc.cc:332
#4  0x00007f48f42f4674 in deallocate<boost::asio::detail::thread_info_base::default_tag> (size=<optimized out>, pointer=<optimized out>, this_thread=<optimized out>)
at /home/zhangyifan8/work/pegasus/rdsn/thirdparty/output/include/bo …
```
=> fix: fix the usage of service_engine::get_all_nodes()

src/runtime/profiler.cpp, src/runtime/profiler_command.cpp, src/runtime/profiler_header.h
In latest tests I found that pegasus server crashed when destroy a static map after called `exit()` in libc.so.6.
Coredump stack is:
```
(gdb) bt
#0  std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, dsn::tools::perf_counter_ptr_type>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, dsn::tools::perf_counter_ptr_type> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, dsn::tools::perf_counter_ptr_type> > >::_M_erase …
```
=> fix(perf_counter): remove static map from counter_info

src/block_service/hdfs/hdfs_service.cpp, src/block_service/hdfs/hdfs_service.h
When we kill a pegasus progress, `vm_direct_exit(int)` was first called, after that we should not call `hdfsDisconnect()` which would try to gc jni objects.  So I removed `hdfsDisconnect()` from the destructor, this may lead connections leaked, but I couldn't find a safe way to call it when progress terminated.
=> fix(hdfs): do not call hdfsDisconnect() after jvm exited

include/dsn/cpp/rpc_stream.h, src/runtime/rpc/thrift_message_parser.cpp
fix heap-use-after-free in rpc_read_stream.
In src/runtime/rpc/thrift_message_parser.cpp L113, the message is deleted. And when the dstor of rpc_read_stream is called, it will call _msg->read_commit. So heap-use-after-free occured.
```
==30014==ERROR: AddressSanitizer: heap-use-after-free on address 0x60f0000c32c8 at pc 0x5605c96ac468 bp 0x7ff9f4fc66a0 sp 0x7ff9f4fc6690
READ of size 1 at 0x60f0000c32c8 thread T20 (client.THREAD_P)
#0 0x5605c96ac467 in dsn::message_ex::read_commit(unsigned long) /home/mi/workspace/rdsn/src/runtime/rpc/rpc_message.cpp:505
#1 0x5605c96c0242 in dsn::rpc_read_stream::~rpc_read_stream() /home/mi/workspace/rdsn/include/dsn/cpp/rpc_stream.h:62
#2 0x5605c96c0242 in create_message_from_request_blob /home/mi/workspace/rdsn/src/runtime/rpc/thrift_message_parser.cpp:93 …
```
=> fix(asan): heap-use-after-free in rpc_read_stream

include/dsn/tool-api/rpc_message.h, include/dsn/utility/transient_memory.h, src/runtime/rpc/rpc_message.cpp, src/runtime/test/rpc_message.cpp, src/utils/transient_memory.cpp
remove the dependency of tls memory for `message_ex::create_receive_message_with_standalone_header` and `message_ex::copy_message_no_reply`
=> refactor:  remove the dependency of tls memory for some member functions in message_ex

include/dsn/dist/replication/replication_app_base.h, src/replica/split/replica_split_manager.cpp, src/replica/storage/simple_kv/simple_kv.server.impl.h, src/replica/storage/simple_kv/test/simple_kv.server.impl.h, src/replica/test/mock_utils.h
In pegasus pr [535](https://github.com/apache/incubator-pegasus/pull/535), we use rocksdb's original API CreateCheckpoint to do checkpoint. In function `copy_checkpoint_to_dir_unsafe`, it will create a checkpoint without flush memtable, code like below:
```
// CreateCheckpoint() will not flush memtable when log_size_for_flush = max
status = chkpt->CreateCheckpoint(checkpoint_dir, std::numeric_limits<uint64_t>::max());
```
When parent partition prepare states for child to learned, it should create a checkpoint with memtable flushed.  As a result, this checkpoint will contain more data, less data will be learned during async-learn stage. 
This pull request adds `flush_memtable` option for function `copy_checkpoint_to_dir`, the pegasus implementation is in pegasus pr …
=> fix(split): add flush_memtable for copy_checkpoint_to_dir

include/dsn/dist/replication/replica_envs.h, src/common/replication_common.cpp, src/meta/app_env_validator.cpp, src/meta/meta_split_service.cpp, src/meta/test/meta_split_service_test.cpp
During partition split, original partition will split into two parts. To avoid reading from wrong partition or writing into wrong partition, each read and write request should be checked if it is sent to the right partition. This pull request adds an app_env called `SPLIT_VALIDATE_PARTITION_HASH`, when partition split started, it will be set as true. How this app_env works will be implmented in further pull request.
=> feat(split): add app_env split_validate_partition_hash

src/aio/disk_engine.cpp
next_offset must be initialized. Or it may produce error when it goes to L61
=> fix: error reported in build process of pegasus-docker

include/dsn/perf_counter/perf_counters.h, include/dsn/tool-api/command_manager.h, src/meta/server_state.cpp, src/nfs/nfs_client_impl.cpp, src/nfs/nfs_client_impl.h, src/perf_counter/perf_counters.cpp, src/replica/replica_stub.cpp, src/runtime/service_engine.cpp, src/runtime/service_engine.h, src/utils/command_manager.cpp
On account of `std::remove` could not actually erase elements from containers, 
> The removal is done by replacing the elements that compare equal to val by the next element that does not, ...  [1]
we may delete `command_instance *` repeatly when destroy `command_manager`.
```
void command_manager::deregister_command(dsn_handle_t handle)
{
auto c = reinterpret_cast<command_instance *>(handle);
dassert(c != nullptr, "cannot deregister a null handle");
utils::auto_write_lock l(_lock);
for (const std::string &cmd : c->commands) {
ddebug("unregister command: %s", cmd.c_str());
_handlers.erase(cmd);
}
std::remove(_commands.begin(), _commands.end(), c);	
delete c;	
}
command_manager::~command_manager()
{	
for (command_instance *c : _commands) {	
delete c;	
}	
}
```
The correct way to remove …
=> fix(command_manager): avoid using std::remove to erase elements from std::vector

src/utils/simple_logger.cpp
Direct printing `std::function<std::string()> log_prefixed_message_func()` will cause garbled characters.
=> fix: fix log print

include/dsn/tool-api/command_manager.h, src/utils/command_manager.cpp
In the dstor of command_instance, the command_instances handled by `_handlers`.
=> fix(asan): memory leak in command_manager

src/block_service/fds/fds_service.cpp
set burst_size of _write_token_bucket in fds_service to max value of double.
1. restore a big app from fds_c3
```
restore_app -c c3srv-mall -p mico_device_sn_cmei_profile
```
2. backup app result to fds_c3, to see whether the backup process will success or not
```
add_backup_policy -p backup_restore_app -b fds_c3 -a 3 -i 864000 -s 16:00 -c 1
```
3. the backup process above is succeed finally.
=> fix: set burst_size of _write_token_bucket in fds_service to max value of double

src/block_service/fds/fds_service.cpp
`rocksdb_target_file_size_base` and `rocksdb_write_buffer_size` are unused now in fds_service.
=> fix: delete unused flags `rocksdb_target_file_size_base` and `rocksdb_write_buffer_size`

src/nfs/test/main.cpp
the error message that asan reported:
```
==24019==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 448 byte(s) in 1 object(s) allocated from:
#0 0x7efe0fc32448 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0448)
#1 0x5649a0ce3adf in operator() /home/mi/workspace/pegasus/rdsn/src/runtime/rpc/asio_net_provider.cpp:154
#2 0x5649a0ce3adf in operator() /home/mi/workspace/pegasus/rdsn/thirdparty/output/include/boost/asio/detail/bind_handler.hpp:65
#3 0x5649a0ce3adf in asio_handler_invoke<boost::asio::detail::binder1<dsn::tools::asio_network_provider::do_accept()::<lambda(boost::system::error_code)>, boost::system::error_code> > /home/mi/workspace/pegasus/rdsn/thirdparty/output/include/boost/asio/handler_invoke_hook.hpp:69
#4 0x5649a0ce3adf in …
```
=> fix: memory leak in nfs test

src/meta/meta_split_service.cpp, src/meta/server_state.cpp, src/meta/test/meta_split_service_test.cpp, src/replica/split/replica_split_manager.cpp
In pervious pull requests, cancel partition split is implemented, after adding those functions, we need to handle some cases specially.
1. In function `register_child_on_meta`
- when all replicas in group finish split, primary parent will send rpc to register child on meta server, if split is canceled, this register rpc should be failed
2. In function `on_config_sync`
- when partition split is canceled, the useless child replica is still in replica server memory, it will be included in on_config_sync rpc, meta server should not assert in this case, should let replica server gc this replica.
=> feat(split): supplement two cases after implementing cancel split

include/dsn/perf_counter/perf_counter_wrapper.h, src/perf_counter/perf_counters.cpp
The global variable `task_spec_profiler *s_spec_profilers` could be destroyed after the singleton `perf_counters::instance()` destroyed,
```
struct task_spec_profiler
{
perf_counter_wrapper ptr[PERF_COUNTER_COUNT];
bool collect_call_count;
bool is_profile;
std::atomic<int64_t> *call_counts;
task_spec_profiler()
{
collect_call_count = false;
is_profile = false;
call_counts = nullptr;
memset((void *)ptr, 0, sizeof(ptr));
}
};
```
so there would be issues if call `perf_counters::instance()`  in `perf_counter_wrapper` destructor.
Because it seems not easy to use something else to replace the global variable `task_spec_profiler *s_spec_profilers`, and make `perf_counter_wrapper` objects destroyed before `perf_counters::instance()` destroyed based on current codes, I removed the clear counter …
=> fix(perf_counter_wrapper): avoid using invalid perf_counters::instance() to remove counter

src/aio/aio_provider.cpp, src/aio/aio_provider.h, src/aio/disk_engine.cpp, src/aio/disk_engine.h, src/aio/file_io.cpp, src/runtime/CMakeLists.txt, src/runtime/service_api_c.cpp
When exiting the process, we need to close files using `disk_engine`, `disk_engine` should be destructed after `service_engine` destructed.
=> fix: make disk_engine destructed after service_engine destructed

src/failure_detector/failure_detector.cpp, src/nfs/nfs_node_impl.cpp
When exiting progress `dsn::task::get_current_node()` is `nullptr`, so we shouldn't call `dsn_rpc_unregiser_handler`. Also, when the `rpc_engine` destructed, all handlers have been cleared, this is no need to call `dsn_rpc_unregiser_handler`.
```
rpc_server_dispatcher::~rpc_server_dispatcher()
{
for (auto &h : _vhandlers) {
delete h;
}
_vhandlers.clear();
_handlers.clear();
dassert(_handlers.size() == 0,
"please make sure all rpc handlers are unregistered at this point");
}
```
=> fix: do not call unregister_rpc_handler when exiting progress

src/perf_counter/perf_counters.cpp, src/runtime/service_api_c.cpp
1. fix heap-use-after-free in perf_counters
2. Put the loading of configuration at the beginning of this func. Because in dsn_global_init(), it calls perf_counters::instance(), which calls shared_io_service::instance(). And in the cstor of shared_io_service, it calls dsn_config_get_value_uint64() to load the corresponding configs. That will make dsn_config_get_value_uint64() get wrong value if we put dsn_config_load in behind of dsn_global_init()
The error message asan reports:
```
==8642==ERROR: AddressSanitizer: heap-use-after-free on address 0x60b000000368 at pc 0x564e98eb17d9 bp 0x7ffe4593b030 sp 0x7ffe4593b020
READ of size 8 at 0x60b000000368 thread T0
#0 0x564e98eb17d8 in boost::asio::detail::deadline_timer_service<boost::asio::time_traits<boost::posix_time::ptime> …
```
=> fix(asan): fix heap-use-after-free in perf_counters

src/aio/sim_aio_provider.cpp
#777 removes parameter `async` for `native_linux_aio_provider::aio_internal`, `async=false` parameter is only used running simple kv tests. That pr left a problem that function `complete_io` would be called twice, which leading coredump running simple kv unit tests. This patch fixs it.
=> fix: fix core while running simple_kv unit test

src/replica/replica_config.cpp, src/replica/test/replica_test.cpp
Function `update_bool_envs` is used to update bool app envs:
- old value = false, app value = false/true -> new value =  false/true
- old value = true, app value = false/true -> new value =  false/true
But the previous implemetation didn't consider the value is not set. For example, old value = true, admin delete this app envs, replica will not update value into false, this patch fixs this bug and update unit tests.
=> fix: fix bug when update bool app envs

CMakeLists.txt
Some of the test code is written like this:
```
...
// exit without any destruction
#ifndef ENABLE_GCOV
dsn_exit(0);
#endif
return 0;
```
When we need to test destructors, `ENABLE_GCOV` should be defined, otherwise `dsn_exit()` would be called finally.
=> fix(cmake): define `ENABLE_GCOV` when build with `--enable_gcov`

src/replica/replica_context.h, src/replica/replica_stub.cpp, src/replica/replica_stub.h, src/replica/split/replica_split_manager.cpp
This pull request add bulk load perf-counters, including:
```
perf_counter_wrapper _counter_replicas_splitting_count;
perf_counter_wrapper _counter_replicas_splitting_max_duration_time_ms;
perf_counter_wrapper _counter_replicas_splitting_max_async_learn_time_ms;
perf_counter_wrapper _counter_replicas_splitting_max_copy_file_size;
perf_counter_wrapper _counter_replicas_splitting_recent_start_count;
perf_counter_wrapper _counter_replicas_splitting_recent_copy_file_count;
perf_counter_wrapper _counter_replicas_splitting_recent_copy_file_size;
perf_counter_wrapper _counter_replicas_splitting_recent_copy_mutation_count;
perf_counter_wrapper _counter_replicas_splitting_recent_split_fail_count;
perf_counter_wrapper _counter_replicas_splitting_recent_split_succ_count;
```
splitting_count
name: …
=> feat(split): add split related perf-counter

src/replica/replica_context.cpp, src/replica/replica_stub.cpp, src/replica/split/replica_split_manager.cpp
#789 adds partition split related perf-counters, this pr supplements some counters.
=> feat(split): update some split related perf-counter

src/utils/flags.cpp
The format before modify:
```
{"abnormal_write_trace_latency_threshold":"{\"name\":\"abnormal_write_trace_latency_threshold\",\"section\":\"replication\",\"type\":\"FV_UINT64\",\"tags\":\"\",\"description\":\"latency trace will be logged when exceed the write latency threshold\",\"value\":\"1000000000\"}\n","aio_factory_name":"{\"name\":\"aio_factory_name\",\"section\":\"core\",\"type\":\"FV_STRING\",\"tags\":\"\",\"description\":\"asynchonous file system provider\",\"value\":\"dsn::tools::native_aio_provider\"}\n","capacity_unit_saving_ttl_days":"{\"name\":\"capacity_unit_saving_ttl_days\",\"section\":\"pegasus.collector\",\"type\":\"FV_INT32\",\"tags\":\"\",\"description\":\"the ttl of the CU data, 0 if no ttl\",\"value\":\"90\"}\n","cluster_name":"{\"name\":\"cluster_name\",\"section\": …
```
=> fix: modify the ouput format for configs http api

src/replica/replica_http_service.cpp, src/replica/test/replica_test.cpp
#731 update replica query data version http interface. The pervious interface is like below:
```
{
"1":{
"data_version": "1",
"pidx" : "1",
},
......
}
```
This pull request simplify this interface, remove the duplicated pidx filed, like below:
```
{
"1":{
"data_version": "1",
},
......
}
```
=> feat(http): update query data version

bin/dsn.cmake, src/http/pprof_http_service.cpp, src/meta/test/meta_bulk_load_service_test.cpp, src/meta/test/meta_split_service_test.cpp, src/replica/replica.h
Errors: https://github.com/XiaoMi/rdsn/issues/802
=> build: fix compilation errors on clang-10

src/replica/replica.cpp, src/replica/replica.h, src/replica/replica_http_service.cpp, src/replica/replica_http_service.h, src/replica/replica_stub.cpp, src/replica/replica_stub.h, src/replica/test/replica_test.cpp
#696 adds a http interface to query manual compaction status, this pr updates it:
- rename all `compact` and `compaction` into `manual_compact` and `manual_compaction`
- add a new status `kIdle` to distinguish not execute manual compaction and manual compaction finished
- update count in response from string into integer
The previous request and response is like:
```
curl 'http://localhost:34801/replica/compaction?app_id=1'
{
"status": {
"CompactionFinish": "8", 
"CompactionQueue": "0", 
"CompactionRunning": "0"
}
}
```
The new request and response is like:
```
curl 'http://localhost:34801/replica/manual_compaction?app_id=1'
{
"status": {
"finished": 8,
"idle": 0, 
"queuing": 0, 
"running": 0
}
}
```
=> feat(http): update query manual compaction interface

bin/dsn.cmake
```
error: unknown warning option '-Wno-implicit-int-float-conversion'; did you mean '-Wno-implicit-float-conversion'? [-Werror,-Wunknown-warning-option]
```
Clang9 can't recognize the flag '-Wno-implicit-int-float-conversion' so I fallback to use '-Wno-implicit-float-conversion'. This flag works at both clang9 and clang10 environments.
Check this failure at here: https://github.com/pegasus-kv/pegasus-docker/runs/2221177367?check_suite_focus=true
=> fix: compilation errors on clang-9

src/meta/greedy_load_balancer.cpp, src/meta/meta_service.cpp, src/meta/server_load_balancer.cpp, src/meta/server_state.cpp, src/replica/replica_stub.cpp
```
-------------------------------------------------
help|Help|h|H [command] - display help information
help|Help|h|H [command] - display help information
profile|Profile|p|P - performance profiling
profiler data - get appointed data, using by pjs
profile|Profile|p|P - performance profiling
profiler data - get appointed data, using by pjs
repeat|Repeat|r|R interval_seconds max_count command - execute command periodically
repeat|Repeat|r|R interval_seconds max_count command - execute command periodically
config-dump - dump configuration
engine - get engine internal information
fd.allow_list
flush-log - flush log to stderr or log file
help|Help|h|H [command] - display help information
help|Help|h|H [command] - display help information
dump: dump app_states of meta server to local file …
```
=> fix: incorrect help info of meta/replica remote commands

src/block_service/local/local_service.cpp, src/block_service/local/local_service.h, src/meta/meta_backup_service.cpp, src/meta/meta_backup_service.h, src/meta/server_state.h, src/meta/test/backup_test.cpp, src/meta/test/clear.sh, src/meta/test/config-test.ini
Prior to this patch, if we got errors during backup process, meta would retry again and again, the backup would never stop or be disabled until backup success. 
This pr marked a policy failed when got fs errors during backup, and we could disable the policy after it is marked failed.
I tested it on a real cluster, set `fds_burst_size` to 500 bytes to mock fds errors.
```
-_write_token_bucket.reset(new folly::TokenBucket(FLAGS_fds_write_limit_rate << 20, std::numeric_limits<double>::max()));
+_write_token_bucket.reset(new folly::TokenBucket(FLAGS_fds_write_limit_rate << 20,500));
```
test steps:
1. add a backup policy
2. query the policy
```
>>> query_backup_policy -p test_fds
policy_info:
name                  : test_fds
backup_provider_type  : fds_wq  
backup_interval       : 86400s …
```
=> fix(backup_policy): do not try again when got fs errors

src/meta/backup_engine.cpp, src/meta/backup_engine.h, src/meta/test/meta_backup_test.cpp
This patch fixed the issue that backup engine would keep retrying to write backup_info when ERR_FS_INTERNAL occured.
=> fix(one-time backup): mark a backup failed when write backup info failed

include/dsn/dist/block_service.h, src/block_service/hdfs/hdfs_service.cpp, src/block_service/hdfs/hdfs_service.h, src/common/backup.thrift, src/meta/backup_engine.cpp, src/meta/backup_engine.h, src/meta/meta_backup_service.cpp, src/meta/meta_backup_service.h, src/meta/test/config-test.ini, src/meta/test/meta_backup_test.cpp, src/replica/replica.h, src/replica/replica_backup.cpp, src/replica/test/clear.sh, src/replica/test/config-test.ini, src/replica/test/mock_utils.h, src/replica/test/replica_test.cpp
This patch added a new optional field `backup_path` to `start_backup_app_request` so that users could backup an app to a specific path.
For local_service, suppose we had a configuration:
```
[[block_service.local_service]]
type = local_service
args = /usr/pegasus
```
If we specify `backup` as backup_path when use one-time backup, the previous backup directory is `/usr/pegasus`, now the backup directory is `/usr/pegasus/backup`. If we want to backup app to a totally user specified path, we should config args as '/'. 
For hdfs_service, the following configurations ard recommended, so that we could only constructed one `hdfsFS` object for the same namenode.
```
[[block_service.hdfs_tjwq]]
type = hdfs_service
args = hdfs://tjwqstaging-hdd
[[block_service.hdfs_zjy]]
type = hdfs_service
args = …
```
=> feat(one-time backup): support user specified backup path

src/client/replication_ddl_client.cpp, src/meta/meta_service.h, src/meta/server_state_restore.cpp, src/meta/test/server_state_restore_test.cpp
#816 introduced a not found error when restore app metadata with no specified path,  this patch fixed it and added a test to verify it has been fixed.
=> fix(restore): fix not found error when restore app metadata

src/block_service/test/CMakeLists.txt, src/block_service/test/clear.sh, src/block_service/test/hdfs_service_test.cpp, src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/replica_bulk_loader.h
Recently our users encountered problems while using bulk_load, their job always failed, and we found remove_directory errors in replica server log:
```
W2021-04-22 11:15:40.633 (1619061340633182759 122434) replica.replica20.0400de080018c494: filesystem.cpp:329:remove_directory(): remove /home/work/ssd3/pegasus/c4tst-bulkload/replica/reps/46.18.pegasus/bulk_load failed, err = Directory not empty
E2021-04-22 11:15:40.633 (1619061340633219926 122434) replica.replica20.0400de080018c494: replica_bulk_loader.cpp:599:remove_local_bulk_load_dir(): [46.18@10.132.5.22:34801] remove bulk_load dir(/home/work/ssd3/pegasus/c4tst-bulkload/replica/reps/46.18.pegasus/bulk_load) failed
```
The reason is that we couldn't remove a directory using whiling writing files in this directory(see the added tests in …
=> fix(bulk_load): fix remove_local_bulk_load_dir()

include/dsn/utility/fail_point.h, src/aio/native_linux_aio_provider.cpp, src/aio/test/aio.cpp
https://github.com/apache/incubator-pegasus/issues/659 has reported the io write operation bug and it only `retry` to decrease the probability of occurrence. This pr refer [stackovflow: handling-incomplete-write-calls](https://stackoverflow.com/questions/32683086/handling-incomplete-write-calls) ,  [rocksdb](https://github.com/facebook/rocksdb/blob/d89483098ff4a77bd0ef12454a64554805984cc5/env/io_posix.cc#L119) and add the retry operation.
- This pr only decrease the probability but not resolve it completely
- This pr add `FAIL_POINT_INJECT_OFF_F` macro to mock `pwrite` to reproduce the bug
=> fix: support retry when io write incompletely

src/replica/bulk_load/replica_bulk_loader.cpp
In bulk load download stage, replica server will download file from remote file provider, if a same-name file exists,  block service interface `download_file` will return `ERR_PATH_ALREADY_EXIST`. In previous implmentation, if local file doesn't pass verification, it will lead to bulk load failed. This pull request fixs it, if local file doesn't pass verifition, it will remove old file and redownload it.
I test this case in onebox manually in following step:
1. start bulk load
2. pause bulk load
3. modify one file content to simulate downloaded local file is different from remoted file
4. restart bulk load
5. I can find redownload log below
```
W2021-04-26 15:38:04.26 (1619422684026147118 7747) replica.rep_long0.0304000000000420: replica_bulk_loader.cpp:441:operator()(): [2.0@<ip>:<port>] …
```
=> fix(bulk_load): redownload file if local file damaged

src/replica/bulk_load/replica_bulk_loader.cpp
#823 fixs the bug that removing bulk load directory failed when replica cleanup bulk load context. This pull request is a supplement of it. This pr adds remove directory before starting bulk load (when replica bulk_load_status is INVALID).
=> fix(bulk_load): remove possible old directory when start bulk load

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp
During bulk load process, meta server will control the bulk load status switch: downloading -> downloaded -> ingesting -> succeed, if replica configuration changed or network failed, meta server will rollback status into downloading. In pervious implementation, it is possible for bulk load process rollback for long time. This pull request adds `bulk_load_max_rollback_times`, if the table has been rollback to downloading for too many times, it will turn status into failed to stop the process.
configuration update:
```diff
[meta_server]
+bulk_load_max_rollback_times = 10
```
=> feat(bulk_load): add bulk load max rollback count

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp
To shorten all partitions ingestion total time, the pervious implementation didn't do any restrction when meta server sent ingestion request to primaries. However, ingestion will cost replica server lots of cpu, io resource, even affect cluster read/write performance. This pull request adds ingestion concurrent count in meta server, if the count is 4, the fifth ingestion request won't be sent to primary partition unless meta received one ingestion response. Besides, this count can be updated dynamically through http interface.
```diff
[meta_server]
+bulk_load_ingestion_concurrent_count=4
```
=> feat(bulk_load): meta server adds bulk load ingestion concurrent count restriction

.github/workflows/compilation.yaml
When a new tag is created (for example, when we are preparing a release), this workflow will run compilation on multiple platforms.
=> test: add workflow for new tag creation and regular build

src/replica/replica_stub.cpp, src/replica/replica_stub.h
Sometimes, we need the status of tcmalloc to analyze some issues about memory.
add remote command to get status of tcmalloc
Manual test (add detailed scripts or steps below)
remote_command -t replica_server replica.get-tcmalloc-status
Need to update the documentation
Need to be included in the release note
=> feat: add a remote command to get status of tcmalloc

.github/workflows/pull_request.yaml
Sometimes we need to re-run github actions when they failed by reopening th PR.
Ref docs: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
=> fix: fix github actions not run when reopen a PR

src/common/replication_common.cpp, src/common/replication_common.h, src/common/test/replication_common_test.cpp
This pull request refactor part of function `replication_options::initialize`. This function will get options from config and store them including replica data directory (data_dirs). To get data_dirs, `initialize` will first parse `config[data_dirs]`, then read black_list file, finally exclude the directories in black list. This pr add three functions to implement them, called: `get_data_dir_and_tag`, `get_data_dirs_in_black_list` and `check_if_in_black_list`, besides, add unit tests for those functions.
=> refactor: refactor replication_options initialize function

src/replica/replica_stub.cpp
Fix a compilation error: https://github.com/XiaoMi/rdsn/runs/2786707126?check_suite_focus=true, which was introduced by https://github.com/XiaoMi/rdsn/pull/834
=> fix: fix a compilation error on clang

src/meta/meta_backup_service.cpp, src/meta/test/backup_test.cpp
Before this patch meta will continue last unfinished backup after restarted, however, whether the policy is disabled or not is not considered. This patch fixed it.
=> fix(backup_policy): ignore current backup when policy is diabled

include/dsn/utility/join_point.h
I met an error when pegasus exit, the progress ouput is:
```
terminate called after throwing an instance of 'std::bad_function_call'
what():  bad_function_call
```
coredump stack:
```
(gdb) bt
#0  0x00007f23db90d1d7 in raise () from /lib64/libc.so.6
#1  0x00007f23db90e8c8 in abort () from /lib64/libc.so.6
#2  0x00007f23dc23fb3d in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f23dc23dba6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f23dc23cbf9 in __cxa_call_terminate (ue_header=0x1bb0060) at ../../../../libstdc++-v3/libsupc++/eh_call.cc:54
#5  0x00007f23dc23d545 in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=<optimized out>, …
```
=> fix: add a destructor for `join_point`

include/dsn/tool-api/timer_service.h, src/aio/test/main.cpp, src/meta/meta_service.cpp, src/meta/meta_service.h, src/meta/meta_service_app.cpp, src/replica/replica_stub.cpp, src/replica/replica_stub.h, src/runtime/rpc/rpc_engine.h, src/runtime/service_engine.cpp, src/runtime/service_engine.h, src/runtime/task/simple_task_queue.cpp, src/runtime/task/simple_task_queue.h, src/runtime/task/task_engine.cpp, src/runtime/task/task_engine.h, src/runtime/task/task_engine.sim.h
See https://github.com/apache/incubator-pegasus/issues/734 for coredump stack details.
The stack shows that we still want to enqueue some tasks when `task_worker_pool` is destroyed.
This patch explicitly specified the order in which `service_app` , `rpc_engine` and `task_engine` stop in `~service_node()`, which is the reverese order they start.
=> fix(graceful_exit): adjust the destructing order

src/replica/replica_config.cpp, src/replica/replica_learn.cpp
https://github.com/apache/incubator-pegasus/issues/740 has describe the problem. 
private log from remote node when learning should be protected, which actually was considered in design of https://github.com/XiaoMi/rdsn/pull/355, but the problem is that the `duplicating status` is false when re-open replica,  and status sync(`on_config_sync` rpc)  is lagging to learning,  which result in the code will be ignored: https://github.com/XiaoMi/rdsn/blob/2b4232809262a1e6102a67ae86db2f37bd58e8ce/src/replica/replica_learn.cpp#L1556-L1559
that is to say, the private log is lost since the log of  path `/learn`don't replay to path `/plog`with the `duplicating = false` when replica re-open. for sync the `duplicating status` in time, this pr don't depend the `config sync`: …
=> fix: plog may be lost on going duplicating when replica re-open and then learn

include/dsn/dist/replication/replica_envs.h, src/common/replication_common.cpp, src/meta/app_env_validator.cpp
```
➜  pegasus git:(master) ✗ ./run.sh shell
W2021-07-02 11:48:40.629 (1625197720629655537 28820) : overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
W2021-07-02 11:48:40.629 (1625197720629708604 28820) : overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX_ACK from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
Pegasus Shell 2.1.SNAPSHOT
Type "help" for more information.
Type "Ctrl-D" or "Ctrl-C" to exit the shell.
The config file is: /home/mi/workspace/pegasus/config-shell.ini.28813
The cluster name is: onebox
The cluster meta list is: 127.0.0.1:34601,127.0.0.1:34602,127.0.0.1:34603
>>> ls
[general_info]
app_id  status     app_name  app_type  partition_count  replica_count …
```
=> feat: add env check entry in `app_env_validator` for user specified compaction

src/client/partition_resolver.cpp, src/client/partition_resolver_simple.cpp
Like the title shows, this pull request add not-retry logic for c++ client while receive splitting or disk insufficient error.
=> fix(client): client not retry while receive splitting or disk insufficient error

src/common/fs_manager.cpp, src/common/fs_manager.h, src/common/test/fs_manager_test.cpp, src/replica/replica.h, src/replica/replica_2pc.cpp, src/utils/filesystem.cpp
#833 adds the feature that when disk space is insufficient, server will reject write requests. Disk status will be checked and updated periodically, only when disk status changed, the replicas on it will update their status. Here existing a bug that if the disk space is insufficient when the server started, the disk status will always be insufficient, and it won't be updated when we close disk space check. This pull request fixs the bug above, and adds related unit test.
```diff
[replication]
-enable_disk_available_space_check=true
+reject_write_when_disk_insufficient=true
```
=> fix(disk): fix disk space insufficient bug

include/dsn/dist/replication/replica_envs.h, src/common/replication_common.cpp, src/meta/app_env_validator.cpp, src/replica/replica.cpp, src/replica/replica.h, src/replica/replica_throttle.cpp
Add rate limiter for backup request. Related issue: https://github.com/apache/incubator-pegasus/issues/778
1. `set_app_envs replica.backup_request_throttling 1*delay*100`
2. send read request to server with backup request
3. log shows that the backup request is delayed: `./data/log/log.1.txt:11761:[replica*eon.replica*recent.backup.request.throttling.delay.count@temp, VOLATILE_NUMBER, 3.00]`
4.  `set_app_envs replica.backup_request_throttling 1*reject*100`
5. send read request to server with backup request
6. log shows that the backup request is rejected: `./replica1/data/log/log.1.txt:9890:[replica*eon.replica*recent.backup.request.throttling.reject.count@temp, VOLATILE_NUMBER, 1.00]`
All requests send by these tests can receive response successfully
=> feat: add rate limiter for backup request

src/meta/partition_guardian.cpp
issue: https://github.com/XiaoMi/rdsn/issues/848
=> refactor: move on_redundant_secondary from simple_load_balancer to partition_guardian

src/replica/duplication/replica_duplicator_manager.cpp, src/replica/duplication/test/replica_duplicator_manager_test.cpp, src/replica/prepare_list.cpp, src/replica/replica_check.cpp
See https://github.com/apache/incubator-pegasus/issues/783, this pr reset confirmed_decree of secondary after duplication is removed
=> fix(duplication): reset confirmed_decree to delete secondary private log after remove duplication

include/dsn/cpp/rpc_stream.h, include/dsn/cpp/serialization_helper/thrift_helper.h, include/dsn/utility/binary_reader.h, src/replica/replica_2pc.cpp, src/utils/binary_reader.cpp, src/utils/test/binary_reader_test.cpp
In previous implementation, server will coredump if it reads corrupt data. 
In this pull request, I changed the way to throw exception. So someone can catch the exception if he don't want to make server crash.
=> feat: throw exception if reads corrupt data

src/replica/duplication/load_from_private_log.cpp, src/replica/duplication/mutation_batch.cpp, src/replica/duplication/mutation_batch.h, src/replica/duplication/test/load_from_private_log_test.cpp
See https://github.com/apache/incubator-pegasus/issues/784, this PR add wait logic berfore `replay log` of duplication
=> fix(duplication): force wait confirmed_decree sync complete when start duplication

src/replica/duplication/load_from_private_log.cpp, src/replica/duplication/mutation_batch.cpp, src/replica/duplication/mutation_batch.h, src/replica/duplication/test/mutation_batch_test.cpp, src/replica/mutation_cache.h, src/replica/prepare_list.h
In https://github.com/apache/incubator-pegasus/issues/766, we have list many problems related to `mutatiaon loss`:
Whose crush point is the code:
https://github.com/XiaoMi/rdsn/blob/e31d49ca6d98dba7b83b272cae0346edf6026337/src/replica/prepare_list.cpp#L154-L156
This is implementation of prepare_list in `2pc`, which can make sure the request is valid, otherwise, it will crush and need manual intervention.
Since the `crash` has serious impaction for service and it still cause the `duplication failed and mutation loss`, **the `dassert to crash` may be not necessary for `duplication`.**
This PR re-implement the `commit funtion` for `prepare_list` in duplication, which replace `dassert` to `derror`and add `perf-counter`, like:
```diff
- dassert_replica(mu != nullptr && mu->is_logged(), …
```
=> feat(duplication): derror and add perf-counter if mutation loss instead of dassert for duplication

src/meta/greedy_load_balancer.cpp, src/meta/greedy_load_balancer.h
implement move replicas for cluster load balance
=> feat:  add balance type for cluster load balance

src/replica/replica_stub.cpp, src/replica/replica_stub.h
As [pegasus#789](https://github.com/apache/incubator-pegasus/issues/789) shows, this pull request support releasing all tcmalloc reserved not-used memory by remote command.
NOTICE: Strongly recommend using this command when seriously lack of memory, releasing all reserved memory may affect performance.
I test this function on onebox:
```
>>> remote_command -t replica-server replica.release-all-reserved-memory
COMMAND: replica.release-all-reserved-memory
CALL [replica-server] [ip:por1] succeed: OK, release_bytes=933888
CALL [replica-server] [ip:por2] succeed: OK, release_bytes=6512640
CALL [replica-server] [ip:por3] succeed: OK, release_bytes=6709248
Succeed count: 3
Failed count: 0
```
The log is like:
```
D2021-07-23 10:22:36.125 (1627006956125927036 7178) …
```
=> feat: supporting release all tcmalloc reserved but not used memory

include/dsn/dist/replication/replica_envs.h, src/common/replication_common.cpp, src/meta/app_env_validator.cpp
Sometimes, there are some apps of different business in a cluster.Some apps  want to enable block cache, others my be not.
So we need add an env to enable or disable block cache of an app.
=> feat: add an env to enable or disable block cache of an app

include/dsn/tool-api/task.h, src/runtime/profiler.cpp
#859 adds perf counters to record dropped timeout rpc count ([pegasus#786](https://github.com/apache/incubator-pegasus/issues/786)). This pr update counter type and log level.
=> feat: update dropped-timeout-rpc-count counter type

src/block_service/test/hdfs_service_test.cpp
error log:
```
1 FAILED TEST
==19244==AddressSanitizer: while reporting a bug found another one. Ignoring.
#0 0x5638f789a0fa in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/7/bits/basic_string.h:440
#1 0x5638f789a0fa in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) /usr/include/c++/7/bits/basic_string.h:5928
#2 0x5638f789a0fa in operator() /home/mi/workspace/rdsn/src/block_service/test/hdfs_service_test.cpp:92
#3 0x5638f7b51e3c in …
```
=> fix(sanitizer): fix heap-use-after free in hdfs client test

src/meta/test/meta_service_test.cpp
it will produce coredump if `recvd_request ->io_session` is nullptr
=> fix(sanitizer): coredump in meta_service_test.check_status_failure

src/replica/test/main.cpp
Previously, `replication_service_test_app *app` was not initialized, which will produce coredump.
=> fix: init app before start cold backup context tests

src/meta/greedy_load_balancer.cpp, src/meta/greedy_load_balancer.h, src/meta/meta_data.cpp, src/meta/meta_data.h, src/meta/test/greedy_load_balancer_test.cpp
add a function to get info used for cluster load balance
=> feat: add function to get cluster migration info

scripts/linux/run-clang-format.sh, src/replica/replica.cpp
We should use taskcode(code).to_string() to get metric name , not taskcode(code) to get _internal_code.
=> fix: fix replica::init_table_level_latency_counter metric name error

src/block_service/fds/fds_service.cpp, src/block_service/fds/fds_service.h
- Restore
rate limiter rate: 100MB->500MB
and the batch size is from 100MB --> 500MB, and it can works well.
- Backup
At rate of 100MB, and change burst size from 100MB->500MB. it can works well
=> feat: make token bucket in fds configurable

CMakeLists.txt, src/block_service/test/hdfs_service_test.cpp
the `HDFSClientTest.test_remove_path_while_writing` test will produce error if sanitizer is defined, so I remove it when sanitizer is defined in this pull.
=> fix: don't build  HDFSClientTest.test_remove_path_while_writing if sanitizer is defined

include/dsn/utils/latency_tracer.h, src/replica/mutation.cpp, src/replica/replica_2pc.cpp
In the past, the mutation tracer name is init "mutation[tid]" to distinct, however, the `tid` is different from `primary` and `secondary` for the same mutation,  which is not conducive to tracking the time-consuming of cross-node requests. this pr use `mutation->name()` to track it, which is same for different node
=> fix: update mutation tracer name to mutation->name()

src/replica/replica.cpp, src/replica/replica.h
This pull requests add replica-level reject read/write requests count during partition split.
```
replica*eon.replica*recent.write.splitting.reject.count@[gpid] - VOLATILE_NUMBER
replica*eon.replica*recent.read.splitting.reject.count@[gpid] - VOLATILE_NUMBER
```
=> feat(split): add split reject counters

src/meta/partition_guardian.cpp, src/meta/partition_guardian.h, src/meta/server_state.cpp
simplely move function `register_ctrl_commands`  from `simple_load_balancer` to `partition_guardian`, in order to remove `simple_load_balancer` later.
No code changed actually
=> refactor: move register_ctrl_commands from simple_load_balancer to partition_guardian

src/replica/replica.cpp, src/replica/replica.h, src/replica/replica_2pc.cpp, src/replica/replica_stub.cpp, src/replica/replica_stub.h
This pull request adds replica-level bulk load ingestion reject write counter, and remove the old stub-level counter.
```diff
+ replica*eon.replica*recent.write.bulk.load.ingestion.reject.count@[gpid] - VOLATILE_NUMBER
- replica_stub.bulk.load.ingestion.reject.write.count - VOLATILE_NUMBER
```
=> feat(bulk_load): add replica-level bulk load reject write counter

src/meta/partition_guardian.cpp, src/meta/partition_guardian.h
simplely move function `reconfig`  from `simple_load_balancer` to `partition_guardian`, in order to remove `simple_load_balancer` later.
No code changed actually
=> refactor: move reconfig from simple_load_balancer to partition_guardian

src/meta/partition_guardian.cpp, src/meta/partition_guardian.h
simplely move function `get_ddd_partitions`  from `server_load_balancer` to `partition_guardian`. In order to simplify `server_load_balancer`
No code changed actually
=> refactor: move get_ddd_partitions from server_load_balancer to partition_guardian

src/meta/partition_guardian.h
Because partition_guardian has a sub class, so we  need add virtual to dstor of partition_guardian
=> fix: add virtual to destructor of partition_guardian

include/dsn/http/http_server.h, src/nfs/nfs_client_impl.cpp, src/nfs/nfs_server_impl.cpp, src/nfs/nfs_server_impl.h
In some test, we found that the influence usually caused by nfs_server side under `learning` copy checkpoint. this pr support the nfs server send rate limit.
- limit server send rate may casuse the rpc timeout,so this pr update `nfs rpc timeout` from `10s` to `100s`
- update `max_send_rate` via admin-cli [server-config ](https://github.com/pegasus-kv/admin-cli/blob/main/cmd/server_config.go) may be block for a long time, this pr update the task priority
- for compatibility with `remote-command`, this pr support it too
=> feat: support nfs server rate limit

include/dsn/tool-api/network.h, src/runtime/rpc/network.cpp
Add a perf counter to monitor the session kept on the server.
```
[server*network*client_session_count, NUMBER, 3.00]
[server*network*client_session_count, NUMBER, 4.00]
[server*network*client_session_count, NUMBER, 4.00]
[server*network*client_session_count, NUMBER, 4.00]
[server*network*client_session_count, NUMBER, 5.00]
[server*network*client_session_count, NUMBER, 14.00]
[server*network*client_session_count, NUMBER, 14.00]
[server*network*client_session_count, NUMBER, 4.00]
```
=> feat(perf_counter): add a perf_counter of server session

src/meta/greedy_load_balancer.cpp, src/meta/greedy_load_balancer.h, src/meta/test/greedy_load_balancer_test.cpp
In cluster load balance, we will try to migrate partition from `max_node` who has the max replica count to `min_node`, then we would like to pick up a `max_load_disk` who has the max replica count in `max_node`. 
The old pickup strategy, if different disks hold same replica count, it will chosse the first one.
```
max_node:                   |               min_node:
ssd1: 2.1, 2.2              |                2.1, 2.2, 2.5
ssd2: 2.3, 2.4              |
ssd3: 2.6                   |
...
```
Just as the example shows, `ssd1` will be choosen. However, 2.1 and 2.2 have already exsited in min_node, so there won't be any partition to be moved.
This pr fixs the problem above. We use `get_max_load_disk_set` to get a disk set. `ssd1` and `ssd2` will be included in the set. Then `pick_up_move` …
=> feat(load-balance): update selection strategy for max load disk

src/replica/prepare_list.cpp, src/replica/replica_2pc.cpp, src/replica/storage/simple_kv/test/case-210.ini, src/replica/storage/simple_kv/test/case-211.ini, src/replica/storage/simple_kv/test/case-213.ini
Related issue: https://github.com/apache/incubator-pegasus/issues/796
```
>>> set a b c 
OK
app_id          : 2
partition_index : 4
decree          : 5
server          : 10.231.57.100:34804
>>> get a b 
"c"
app_id          : 2
partition_index : 4
server          : 10.231.57.100:34804
```
1. insert data
```
>>> set a b e
OK
app_id          : 2
partition_index : 4
decree          : 26
server          : 10.231.57.100:34804
```
2. kill the corresponding primary replica
```
➜  pegasus git:(master) ✗ kill 25092
```
3. read data
```
>>> get a b 
"e"
app_id          : 2
partition_index : 4
server          : 10.231.57.100:34803
```
```
➜  pegasus git:(master) ✗ ./run.sh bench
W2021-09-09 13:15:47.443 (1631164547443349845 24518) : overwrite default thread pool for task …
```
=> feat: make secondary commit asynchronously

include/dsn/tool-api/task_queue.h, src/runtime/task/task_engine.cpp, src/runtime/task/task_engine.h, src/runtime/task/task_queue.cpp
In some cases, we found the task queue will be blocked by a lot of tasks. So I add a parameter to control the max length of the task queue, in order to control the memory unlimited growing.
This PR provides two functions:
1. add a remote command to control the specific task queue length
2. add a perf counter to record the count of tasks delayed/rejected to enqueue.
remote_command help:
```
>>> remote_command -l 10.231.57.104:34801 task.queue_max_length help
COMMAND: task.queue_max_length help
CALL [user-specified] [10.231.57.104:34801] succeed: 
get/set the max task queue length of specific thread_pool, `INT_MAX` means no limit 
pool_code can be found by `remote_command -t replica-server system.queue`
task.queue_max_length <pool_code> [queue_max_length | INT_MAX] [queue_max_length]
``` …
=> feat(task): add dynamic control of task queue length

src/meta/greedy_load_balancer.cpp, src/meta/greedy_load_balancer.h, src/meta/test/copy_replica_operation_test.cpp, src/meta/test/greedy_load_balancer_test.cpp
***cluster load balancer***
1. start onebox with 5 replica servers
```
./run.sh start_onebox -r 5
```
2. create serveral tables with 4 partitions
3. the cluster is not balanced now.
```
>>> nodes -d
[details]
address              status    replica_count  primary_count  secondary_count
10.231.57.100:34801  ALIVE                38             12               26
10.231.57.100:34802  ALIVE                35             12               23
10.231.57.100:34803  ALIVE                34             12               22
10.231.57.100:34804  ALIVE                34             12               22
10.231.57.100:34805  ALIVE                39             12               27
[summary]
total_node_count    : 5
alive_node_count    : 5
unalive_node_count  : 0
``` 
4. enable cluster load balancer
``` …
```
=> refactor: remove class cluster_balance_type which is duplicated

src/meta/app_balance_policy.cpp, src/meta/app_balance_policy.h, src/meta/greedy_load_balancer.cpp, src/meta/greedy_load_balancer.h, src/meta/load_balance_policy.cpp, src/meta/load_balance_policy.h, src/meta/test/copy_replica_operation_test.cpp
move code about app balancer from `greedy_load_balancer` to clss `app_balance_policy`
***App Balance Test***
1. start onebox with 4 replica servers
```
./run.sh start_onebox -r 4
```
2. kill one replica server
```
➜  pegasus git:(master) ✗ ps aux | grep pegasus 
mi        8155  1.7  0.1 11680324 55080 pts/0  Sl   09:50   0:00 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /home/mi/workspace/pegasus/.zk_install/zookeeper-3.4.6/bin/../build/classes:/home/mi/workspace/pegasus/.zk_install/zookeeper-3.4.6/bin/../build/lib/*.jar:/home/mi/workspace/pegasus/.zk_install/zookeeper-3.4.6/bin/../lib/slf4j-log4j12-1.6.1.jar:/home/mi/workspace/pegasus/.zk_install/zookeeper-3.4.6/bin/../lib/slf4j-api-1.6.1.jar:/home/mi/workspace/pegasus/.zk_insta …
```
=> refactor: implement app balance policy

src/meta/partition_guardian.cpp
What problem does this PR solve?
partitions are unbalanced after the table is created
For details, see apache/incubator-pegasus#832
Check List
Tests
Manual test (add detailed scripts or steps below)
1. start a onebox with 5 repicaserver: ./run start_onebox -r 5
2. create an app with 100 partitions : create test100 -p 100
3. to view the balancer of the test100 app: app test100 -d
=> fix: partitions are unbalanced after the table is created

src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/replica_bulk_loader.h, src/replica/bulk_load/test/replica_bulk_loader_test.cpp, src/replica/storage/simple_kv/test/case-212.ini
When bulk load started, replica server will firstly connect to the remote file provider and download metadata file synchronously. However, creating connection may cost seconds in production environment, will sometimes affect performance.
This pull request does following update:
- create connection with remote file provider asynchronously
- download metadata file asynchronously
- use default threadpool rather than replication threadpool
- add lock for the related varieties
=> feat(bulk_load): async create connection with remote file provider

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp, src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/test/replica_bulk_loader_test.cpp
When bulk load meet errors in normal stage, it will rollback to downloading stage, including succeed stage. However, there are only some cleanup works in this stage such as delete files and context update. It is unnecessary to rollback to downloading, which will ingestion repeatedly, especially for replica will remove garbage files and reset context while starting a new bulk load process.
This pull request includes following update:
- if bulk load meet error in succeed stage, it won't rollback to downloading
- replica update validate check: succeed -> downloading is an invalid switch
- when replica cleanup bulk load context, if local bulk load folder is not removed, context can't be considered as cleanup
=> feat(bulk_load): not rollback to downloading if bulk load meet error in succeed stage

src/common/replication_common.cpp, src/common/replication_common.h, src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h
Server will reject user write requests during bulk load ingestion stage, so bulk_load_request used to send more frequently during ingestion. However, it sometimes leads unnecessary timeout when server has heavy load. This pull request remove short interval, all requests will be sent in fixed interval.
=> feat(bulk_load): remove bulk load request short interval avoid unnecessary timeout

src/replica/prepare_list.cpp, src/replica/prepare_list.h, src/replica/replica_2pc.cpp
For more details: https://github.com/XiaoMi/rdsn/pull/909
```
>>> use temp
OK
>>> set a c b 
OK
app_id          : 2
partition_index : 4
decree          : 21
server          : 10.231.57.100:34802
>>> get a c 
"b"
app_id          : 2
partition_index : 4
server          : 10.231.57.100:34802
```
1. insert data
```
>>> use temp
OK
>>> set a b c
OK
app_id          : 2
partition_index : 4
decree          : 29
server          : 10.231.57.100:34802
```
2. kill the corresponding primary replica server
```
➜  pegasus git:(master) ✗ ps aux | grep pegasus
mi       16833  0.3  0.1 11680324 55756 pts/0  Sl   11:42   0:01 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Dzookeeper.log.dir=. -Dzookeeper.root.logger=INFO,CONSOLE -cp /home/mi/workspace/pegasus/.zk_install/zookeeper-3.4.6/bin/../build/classes:/ho …
```
=> fix: bug in learn that can't complete

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp
This pull request adds a function called `check_partition_status`, will be called by `partition_bulk_load` and `partition_ingestion`, checking if primary address is valid and if partition has unhealthy partition. This pull request also adds related unit test.
=> feat(bulk_load): add unhealthy partition check

src/meta/meta_service.cpp, src/meta/meta_service.h
Currently we've counted unalive nodes which can be used to warn that some node is dead. Since we've managed lots of clusters, one of the first things that we tend to learn is how many replica servers this cluster has. However, now we cannot read this from a graph. We have to connect to the cluster and check it by commands.
Therefore, I added a counter for alive nodes. Then, taking Prometheus for example,  we can read the number of alive nodes by `meta_eon_meta_service_alive_nodes`, and also the total number of replica servers by `meta_eon_meta_service_alive_nodes + meta_eon_meta_service_unalive_nodes`.
The name and type of the counter is listed as below:
```
meta*eon.meta_service*alive_nodes - NUMBER
```
=> feat: add alive nodes perf-counter

src/meta/server_load_balancer.cpp, src/meta/server_load_balancer.h
As we've moved `on_missing_primary` from `server_load_balancer` to `partition_guardian` in https://github.com/XiaoMi/rdsn/pull/885,  `recent_choose_primary_fail_count` is counted in `partition_guardian` rather than `server_load_balancer`. `recent_choose_primary_fail_count` can be removed from `server_load_balancer`.
=> fix: drop redundant recent_choose_primary_fail_count

include/dsn/dist/replication/replication_app_base.h, include/dsn/dist/replication/replication_enums.h, src/common/metadata.thrift, src/replica/replica.cpp, src/replica/replica.h, src/replica/replica_http_service.cpp, src/replica/replica_http_service.h, src/replica/replica_stub.cpp, src/replica/replica_stub.h, src/replica/storage/simple_kv/simple_kv.server.impl.h, src/replica/storage/simple_kv/test/simple_kv.server.impl.h, src/replica/test/mock_utils.h
As https://github.com/apache/incubator-pegasus/issues/850 shows, meta server should know the status of manual compaction.
This pull request is the part1 of the replica servers report manual compaction status to meta server:
1. move structure manual_compaction_status from `replica.h` to `metadata.thrift`
2. add a new function `query_compact_status` in `replication_app_base.h`, which will be implemented by pegasus repo to return the actual compaction status.
=> feat(manual_compaction): replica report status part1. add function query_compact_status

src/meta/meta_service.cpp, src/meta/meta_service.h, src/meta/test/meta_service_test.cpp
https://github.com/apache/incubator-pegasus/issues/845
=> feat(op_status_lock): add an operation status lock for meta

src/meta/meta_data.cpp, src/meta/meta_data.h, src/replica/replica_stub.cpp
As apache/incubator-pegasus#850 shows, meta server should know the status of manual compaction.
This pull request is the part3 of the replica servers report manual compaction status to meta server:
1. replica report manual compaction status through `on_config_sync`, reference `get_replica_info` in this pr
2. meta also update manual compaction status throught `on_config_sync`, reference `collect_serving_replica` in this pr
=> feat(manual_compaction): replica report status part3

src/runtime/task/task_spec.cpp
The join point name of `on_rpc_create_response` seems not to conform to the naming convention, let's fix it.
=> fix: the join point name of on_rpc_create_response

include/dsn/utility/flags.h, src/utils/flags.cpp, src/utils/test/flag_test.cpp
We've implemented `flag_validator` to validate the value of individual flag. However, there are scenarios where inconsistency should be detected and avoided between 2 or more flags.
For example, `FLAGS_a` and `FLAGS_b` are mutually exclusive: they cannot both be true. Therefore, the related validator may be something like:
```c++
bool validate() {
return !FLAGS_a || !FLAGS_b;
}
```
Another example is that FLAGS_c must be less than FLAGS_d. As for this example, the related validator can be implemented as:
```c++
bool validate() {
return FLAGS_c < FLAGS_d;
}
```
A recent scenario is from https://github.com/XiaoMi/rdsn/pull/963 where we should guarantee that  `FLAGS_min_allowed_replica_count` will never be greater than `FLAGS_max_allowed_replica_count`.
Unfortunately, `flag_validator` is …
=> feat: implement grouped flag validators

src/nfs/nfs_client_impl.cpp, src/nfs/nfs_server_impl.cpp
Setting nfs rate 500MB is equal with `no limiter`, so we disable the nfs limiter to avoid some bugs of `folly-limiter`: https://github.com/apache/incubator-pegasus/issues/846
=> feat: change the nfs limiter diable by default

src/block_service/hdfs/hdfs_service.cpp, src/block_service/hdfs/hdfs_service.h
This pull request adds a folly read limiter for HDFS, different from FDS implementation, this pr uses `BasicDynamicTokenBucket` provided by folly to make it thread-safe to update limiter size dynamically.
- Unit test
- Manual test
```diff
+ [replication]
+ hdfs_read_limit_rate_mb_per_sec = 200
+ hdfs_write_limit_rate_mb_per_sec = 200
- hdfs_read_limit_rate_megabytes
```
=> feat(backup): add write limiter for hdfs

src/client/replication_ddl_client.cpp, src/common/manual_compact.h, src/common/replication_common.h, src/meta/meta_service.h
manual compaction has nothing to do with replication. So in this pull request, I move the corresponding typs to a seperate file named `manual_compaction.h`
=> refactor: move manual compaction common  types to a seperate file

src/common/backup_common.cpp, src/common/backup_common.h, src/common/replication_common.cpp, src/common/replication_common.h, src/meta/backup_engine.cpp, src/meta/meta_backup_service.cpp, src/meta/server_state_restore.cpp, src/meta/test/meta_backup_test.cpp, src/meta/test/server_state_restore_test.cpp, src/replica/backup/cold_backup_context.cpp, src/replica/backup/cold_backup_context.h, src/replica/backup/replica_backup_server.h, src/replica/test/backup_block_service_mock.h, src/replica/test/replica_test.cpp
backup types have nothing to do with replication. So move it from replication_common.h to backup_common.h
=> refactor: move backup common types to backup_common.h

thirdparty/CMakeLists.txt
Previously in https://github.com/apache/incubator-pegasus/issues/745 we'd reported a bug that the values of all metrics of rocksdb flush are always 0.
Since this bug has been fixed in https://github.com/XiaoMi/pegasus-rocksdb/pull/34 by cherry-pick, we could upgrade the rocksdb to the latest fixed version.
=> fix(rocksdb): upgrade rocksdb to fix NotifyOnFlushCompleted() for atomic flush

include/dsn/dist/replication/replication_ddl_client.h, src/client/replication_ddl_client.cpp, src/common/bulk_load.thrift, src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp
As apache/incubator-pegasus#851 show, we decide to support online migration.
This pull request add `ingest_behind` option for bulk load, including:
- Add `ingest_behind` in `start_bulk_load_request` and `app_bulk_load_info`
- Add parameter check for `ingest_behind`, reference function `validate_ingest_behind`
- Add related unit test
=> feat(online_migration): part2 - add ingest_behind option for bulk load

src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/test/replica_bulk_loader_test.cpp
#958 updates the bulk load status check for replica server, it considers that SUCCEED into DOWNLOADING is an invalid transition. However, If a table meet error during ingestion, some partitions have already switch to SUCCEED, and some partitions are INGESTING, it's possible for replica switch SUCCEED into DOWNLOADING. This pull request fixs it.
=> fix(bulk_load): fix replica validate status check

src/common/bulk_load.thrift, src/meta/meta_bulk_load_service.cpp
#986 adds `is_bulk_loading` filed in `query_bulk_load_response` to support manager function(https://github.com/apache/incubator-pegasus/issues/856).
To make related tools (pegasus-spark) compatible, this pull request updates it as optional and other corresponding modification.
=> fix: make is_bulk_loading filed optional in query_bulk_load_response

src/runtime/rpc/thrift_message_parser.cpp, src/runtime/test/thrift_message_parser_test.cpp
see https://github.com/apache/incubator-pegasus/issues/866
We have noticed pegasus 2.0 are using much more network/disk bandwidths than pegasus 1.12.3. After weeks of debugging, we have finally found that this is a bug introduced in #255, when a new thrift message parser that compatible with both old format and new format is refactored to replace the old one. Now we are trying to fix this.
The main cause is that when parsing the message body, instead of return exactly size of the body, it actually return the whole buffer that holds all the received messages. Thus, when there are many write requests piled up, from the moment the write request arrives,  to the moment it writes to mutation logs and to other nodes, the throughput is significantly amplified.
To fix that we merely add one line …
=> fix: message body size unset after parsed which leads to large io throughputs

include/dsn/dist/fmt_logging.h, include/dsn/dist/replication/replication_app_base.h, src/replica/replication_app_base.cpp
Related issue:
https://github.com/apache/incubator-pegasus/issues/875
=> refactor: simplify code by macros

include/dsn/dist/replication/replication_app_base.h, src/replica/replica.cpp, src/replica/replica_init.cpp, src/replica/replication_app_base.cpp
ref issue:
https://github.com/apache/incubator-pegasus/issues/879
=> fix: use fsync() to prevent .app-info/.init-info lost risk on XFS after power outage

include/dsn/dist/replication/replication_app_base.h, src/common/bulk_load.thrift, src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/replica/replica.h, src/replica/replication_app_base.cpp
As https://github.com/apache/incubator-pegasus/issues/877 shows, move files during ingestion will speech up ingestion and decrease disk write throughput. (https://github.com/apache/incubator-pegasus/pull/864)
However, it exposes that in some error handling cases, it is possible to execute an out-dated ingestion request repeated. 
In previous `copy_files` mode, it won't have problems, just ingest files repeatly, now is `move_files` mode, once ingestion is succeed, the original files doesn't exist, which will lead to unexpected ingestion failed.
This pull request is to update error handling during ingestion, including:
- Delay to send ingestion_request to make replica server receive request with ingestion status
- Add ballot in `ingestion_request` (It will be used in pegasus repo to do …
=> fix(bulk_load): update ingestion error handling with move_files mode

include/dsn/utils/latency_tracer.h
https://github.com/apache/incubator-pegasus/issues/883
In previous implementation,  the function `latency_tracer::add_point` will always be called even if `enable_tracer` is false. And before the calling of this function, `fmt::format("{}:{}:{}", __FILENAME__, __LINE__, __FUNCTION__)` will be called to generate the parameter need by it, which will cause waste of cpu cycle and memory usage.
=> fix: avoid to call add_point in latency_tracer

src/replica/mutation_log.cpp
I will add dsn_unlikely in ADD_POINT in later pull request
=> fix: remove unused judgement of FLAGS_enable_latency_tracer in private log

include/dsn/utils/latency_tracer.h
https://github.com/apache/incubator-pegasus/issues/883
To improve execution efficiency, add dsn_unlikely in macro ADD_POINT. Because in most situations, we don't need to add tracer point.
=> feat: add dsn_unlikely in macro ADD_POINT

src/common/bulk_load.thrift, src/meta/meta_bulk_load_service.cpp
https://github.com/apache/incubator-pegasus/issues/885
In current implmentation, before rocksdb execute ingestion, replica will compare file size and md5 with the content of metadata.
Removing this verification will decrease disk.io.read_bytes during ingestion.
```diff
[meta_server]
+bulk_load_verify_before_ingest = false
```
=> feat(bulk_load): add verify_before_ingest option

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h
https://github.com/apache/incubator-pegasus/issues/861
This pull request includes:
- rename `update update_partition_status_on_remote_storage` into `update_partition_info_on_remote_storage` 
- rename `update_partition_status_on_remote_storage_reply` into `update_partition_info_on_remote_storage_reply`
Such refactor will support feature avoid unecessary repeated ingestion.
=> refactor(bulk_load): rename update_partition_status_on_remote_storage

src/replica/replica.cpp, src/replica/replica.h, src/replica/split/replica_split_manager.cpp, src/replica/split/test/replica_split_test.cpp, src/replica/test/mock_utils.h
Use `std::unique_ptr` to avoid memory leak, for example: L132 in src/replica/split/test/replica_split_test.cpp
https://github.com/apache/incubator-pegasus/issues/887
=> refactor: change the type of prepare_list from raw pointer to std::unique_ptr

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp, src/replica/bulk_load/replica_bulk_loader.cpp, src/replica/bulk_load/test/replica_bulk_loader_test.cpp, src/replica/replica.h
As https://github.com/apache/incubator-pegasus/issues/861 shows, this pull request implements avoiding repeated ingestion, including:
- Add `ever_ingest_succeed` and `addresses` in `partition_bulk_load_info` to store address of replica server who has executed ingestion succeed, this structure will store in zk while partition ingestion succeed, reference function`update_partition_info_on_remote_storage`
- Add `check_ever_ingestion_succeed` function before sending ingestion request, if this partition has already executed ingestion succeed and replica nodes not changed, it shoudn't send ingestion, and convert partition bulk load status into `succeed`.
- Mark download into succeed transition valid in replica, reference function `replica_bulk_loader::validate_status`
- Add and update related …
=> feat(bulk_load): avoid unecessary repeated ingestion

src/runtime/rpc/asio_net_provider.cpp, src/runtime/rpc/asio_net_provider.h, src/runtime/rpc/asio_rpc_session.cpp, src/runtime/rpc/asio_rpc_session.h
related issue: https://github.com/apache/incubator-pegasus/issues/307
This issue reported a bug that the core dump will happen in some scenes. It's caused by the race condition when multi-threads read/write/close the same socket. 
**Original way**
```
Epoll
+-------------------------------+
| socket1  socket2  socket3     |
|  +--+     +--+     +--+       |
|  +--+     +--+     +--+       |
|                               |
+------------^------------------+
             |
io_service   |polling
+------------+------------------+
| task_queue                    |
| +-----------+--------------+  |
| | epollwait | call_back    |  |
| +-----+-----+--+--------+--+  |
|       |        |        |     |
+-------+--------+--------+-----+
Thread1 |  2     |     3  |
      +-v-+    +-v-+    +-v-+
    …
```
=> fix(network): use multi io_services in asio

bin/dsn.cmake, src/runtime/CMakeLists.txt
issue: https://github.com/apache/incubator-pegasus/issues/894
CMake issue: https://discourse.cmake.org/t/base-filename-gets-set-to-compiler-depend-ts-after-update-to-cmake-3-20/3075
This patch is inspired by: https://stackoverflow.com/questions/1706346/file-macro-manipulation-handling-at-compile-time/27990434#27990434
Before and after this patch, logs look like:
```
==> replica.log.20220125_135753_521 <==
D2022-01-25 13:57:53.521 (1643090273521305878 2cff) unknown.io-thrd.11519: compiler_depend.ts:466:run(): process(11519) start: 1643090273510, date: 2022-01-25 13:57:53.510
D2022-01-25 13:57:53.527 (1643090273527174447 2cff) unknown.io-thrd.11519: compiler_depend.ts:122:ipv4_from_network_interface(): get ip address from network interface(eth0), addr(x.x.x.x), input interface("") …
```
=> fix(build): fix higher version cmake produce filename as 'compiler_depend.ts' bug

src/meta/meta_bulk_load_ingestion_context.cpp, src/meta/meta_bulk_load_ingestion_context.h, src/meta/test/meta_bulk_load_ingestion_test.cpp
As https://github.com/apache/incubator-pegasus/issues/886 shows, we plan to provide a disk-level concurrent ingesting count restriction. This pull request adds a new class called `ingestion_context`, recording the ingesting partitions and every node and disk ingesting count.
This pull request also adds two configurations to implememt the restriction:
- `bulk_load_node_max_ingesting_count` - restrict node max ingesting partition count
- `bulk_load_node_min_disk_count` - node min disk count
For example:
- `node_max_count=1`, `disk_count=3`: only one partition can do ingestion
- `node_max_count=3`, `disk_count=3`: each disk can only have one partition do ingestion
- `node_max_count=4`, `disk_count=3`: each disk can have 2 partitions do ingestion, but node concurrent count is 4
Configuration …
=> feat(bulk_load): support disk_level ingesting restriction part1 - add ingestion_context class

src/meta/meta_options.cpp, src/meta/meta_options.h, src/meta/meta_service.cpp, src/meta/test/meta_app_operation_test.cpp, src/meta/test/meta_test_base.cpp, src/meta/test/update_configuration_test.cpp
https://github.com/apache/incubator-pegasus/issues/896
=> fix: remove min_live_node_count_for_unfreeze from meta_options to ensure it can be correctly updated dynamically

include/dsn/utility/fail_point.h, src/aio/native_linux_aio_provider.cpp, src/aio/test/aio.cpp, src/replica/duplication/load_from_private_log.cpp, src/replica/duplication/test/load_from_private_log_test.cpp, src/utils/fail_point.cpp, src/utils/fail_point_impl.h
https://github.com/apache/incubator-pegasus/issues/903
https://github.com/XiaoMi/rdsn/pull/818 add `FAIL_POINT_INJECT_VOID_F` to support some no-need return `point`, but use `off()` is error, which will casue any`point` will be executed, though it not be register
=> fix: fail_point is failed when use `FAIL_POINT_INJECT_VOID_F`

src/common/replication_common.cpp, src/common/replication_common.h, src/replica/replica_check.cpp, src/replica/split/replica_split_manager.cpp
https://github.com/apache/incubator-pegasus/issues/859
Empty write is used for flushing WAL log entry which is submit asynchronously. Make sure it can work well if you diable it.
=> feat: make option empty_write_disable mutable

include/dsn/dist/replication/replication_app_base.h, src/replica/replica.cpp
https://github.com/apache/incubator-pegasus/issues/906
This pull request should be reviewed with https://github.com/apache/incubator-pegasus/pull/909 together.
=> fix: shutdown error while closing replica

CMakeLists.txt, bin/dsn.cmake, thirdparty/CMakeLists.txt
Related issue:
https://github.com/apache/incubator-pegasus/issues/898
Also related to https://github.com/XiaoMi/rdsn/issues/573
=> fix(build): update GCC and CMake checker 

src/meta/duplication/duplication_info.h, src/meta/duplication/meta_duplication_service.cpp, src/replica/replica_chkpt.cpp, src/replica/test/replica_test.cpp
`manual checkpoint` status need recovery to `false` when completed.  In the past, the status is updated by [old_decree < last_durable](https://github.com/XiaoMi/rdsn/blob/duplication_dev/src/replica/replica_chkpt.cpp#L144), But once checkpoint may not catch up with `old_decree`, and the following `catch up with task` request will be block. This pr fix it
=> fix(dup_enhancement#19): change checkpoint status after manual checkpoint completed

include/dsn/tool-api/task_tracker.h, src/meta/duplication/duplication_info.h, src/meta/duplication/meta_duplication_service.cpp, src/replica/duplication/replica_duplicator.cpp, src/replica/duplication/replica_follower.cpp, src/replica/duplication/test/replica_follower_test.cpp, src/replica/replica_init.cpp
`THREAD_POOL_REPLICATION_LONG` has limited count, when `duplicate_checkpoint` put into it and `sync execute`, it will be exhausted and casue thread lock, this pr fix it
=> fix(dup_enhancement#20): put `async_duplicate_checkpoint_from_master_replica` into `DEFAULT_POOL` to avoid thread lock

include/dsn/utility/casts.h, include/dsn/utility/metrics.h, src/utils/metrics.cpp, src/utils/test/metrics_test.cpp
https://github.com/apache/incubator-pegasus/issues/928
=> feat(new_metrics): implement the metric & its prototype

src/meta/server_state.cpp, src/meta/server_state.h, src/meta/test/meta_app_operation_test.cpp
https://github.com/apache/incubator-pegasus/issues/865
=> feat(update_replication_factor#3): support to set the replication factor for all partitions of each table

include/dsn/utility/metrics.h, src/utils/test/metrics_test.cpp
https://github.com/apache/incubator-pegasus/issues/931
=> feat(new_metrics): implement the counter

.github/workflows/compilation.yaml, .github/workflows/cpp_actions.yaml, .github/workflows/cpp_always_pass_actions.yaml
ref: https://github.com/apache/incubator-pegasus/issues/948
DockerHub created by JIRA: https://issues.apache.org/jira/browse/INFRA-23150
=> chore: Use official apache/pegasus repo of DockerHub

.github/workflows/cpp_actions.yaml, .github/workflows/cpp_always_pass_actions.yaml
ref: https://github.com/apache/incubator-pegasus/issues/954
- fix the paths and paths-ignore syntax errors in on.pull_request
- use dorny/paths-filter@v2 instead of tj-actions/changed-files@v18.7, which seems more stable
=> ci: fix syntax errors in action yaml files

include/dsn/tool-api/aio_task.h, src/aio/aio_provider.cpp, src/aio/aio_provider.h, src/aio/disk_engine.cpp, src/aio/disk_engine.h, src/aio/native_linux_aio_provider.cpp, src/aio/native_linux_aio_provider.h
https://github.com/apache/incubator-pegasus/issues/903
when buffer of slog is more 2GB, then flush to slog file, it maybe crash.
=> fix: crash when huge write

src/meta/meta_bulk_load_service.cpp, src/meta/meta_bulk_load_service.h, src/meta/test/meta_bulk_load_service_test.cpp
[Pegasus#872](https://github.com/apache/incubator-pegasus/issues/872)
In previous implementation, we restrict only one table can execute bulk load in cluster to guarantee performance. We have already added more restriction to control bulk load download and ingestion, it is safety to permit concurrent bulk load. This pull request adds a gflags to control it.
```diff
[meta_server]
+ enable_concurrent_bulk_load = false
```
=> feat(bulk_load): support different tables can execute bulk load concurrently

src/meta/server_state.cpp, src/meta/test/meta_app_operation_test.cpp
https://github.com/apache/incubator-pegasus/issues/865
=> feat(update_replication_factor#5): support to set the replication factor for app-level metadata of each table

src/meta/meta_data.cpp, src/meta/meta_service.cpp, src/meta/server_state.cpp, src/meta/server_state.h, src/meta/test/meta_app_operation_test.cpp
This is a subtask of https://github.com/apache/incubator-pegasus/issues/865.
Since in https://github.com/XiaoMi/rdsn/pull/1087 we've supported to set env for the replication factor in case there are duplicate requests trying to update the same table, there is still a problem that the request for updating replication factor may fail once meta server crashes. It's possible that there are partial steps finished while others are uncompleted.
Therefore, After meta server has got primary lock, it will initialize, during which recovering replication factor should be relaunched.  Any table whose env of updating replication factor is not removed (once updating replication factor is complete, the env will be eliminated) will be the candidate that needs to recover as long as it's available. All …
=> feat(update_replication_factor#8): recover uncompleted update of replication factor during initialization of meta service

src/meta/test/meta_app_operation_test.cpp
Fix unit tests for the issue: https://github.com/apache/incubator-pegasus/issues/1002.
=> fix: drop unused 'this' from lambda capture for unit-tests that verify replication factor

src/client/partition_resolver_simple.cpp
https://github.com/apache/incubator-pegasus/issues/903.
c++ client will crush for `assert` if server table config is changed, for example, remove table and re-build same name table.
But it's not necessary because `config-update` will trigger the client fetch `latest right config`, which don't has any problem.
I found the problem is that the `duplication module` use the c++ client code: if one duplication failed, I want drop the remote table and re-start new duplication task, but it will result that all the master replica crush for the remote table config changing
=> fix: assert is not necessary when the table config is updated
