bin/dsn.cmake
thirdparty/build-thirdparty.sh
thirdparty/download-thirdparty.sh

thirdparty: add gperftools as a 3rdparty dependency

---

thirdparty/download-thirdparty.sh

because ```return -1``` is not valid in some bash:
```
bash: return: -1: invalid option
```

script: fix download-thirdparty.sh

---

src/dist/replication/lib/replica_stub.cpp

because it may core when learn app

replication: revert gc shared log to depend on last_durable_decree

---

src/core/tests/clientlet.cpp

A test in clientlet.cpp mistakenly assume "when returning by task wait, it have been released by the executor thread".

test: bug fix in test

---

include/dsn/cpp/rpc_holder.h
src/dist/replication/meta_server/server_state.cpp

现在MetaServer收到app envs操作后，没有什么日志，很难追踪app envs的操作。

meta: logging when set/del/clear app envs

---

include/dsn/dist/replication/replication_ddl_client.h
src/dist/replication/ddl_lib/replication_ddl_client.cpp

refer to https://github.com/XiaoMi/pegasus/issues/149

ddl: add cluster_name() method

---

include/dsn/dist/replication/storage_serverlet.h
src/core/core/rpc_engine.cpp
src/core/core/rpc_message.cpp

refer to https://github.com/XiaoMi/pegasus/issues/124 and https://github.com/XiaoMi/pegasus/issues/162

return ERR_HANDLER_NOT_FOUND if task code not exist or not handled

---

src/dist/replication/lib/replica.cpp
src/dist/replication/lib/replica_context.cpp
src/dist/replication/lib/replica_context.h
src/dist/replication/lib/replica_learn.cpp
src/dist/replication/lib/replica_stub.h

refer to https://github.com/XiaoMi/pegasus/issues/165

replica_server: fix learn_app_concurrent_count increment bug

---

compile_thrift.py
include/dsn/c/api_layer1.h
include/dsn/utility/hpc_locks/benaphore.h
include/dsn/utility/preloadable.h
include/dsn/utility/process_utils.h
include/dsn/utility/utils.h
src/core/core/process_utils.cpp
src/core/core/service_api_c.cpp
src/core/core/service_engine.cpp
src/core/core/service_engine.h
src/core/core/task_worker.cpp
src/core/core/thread_access_checker.cpp
src/core/core/tool_api.cpp
src/core/core/utils.cpp
src/core/tools/common/native_aio_provider.linux.cpp
src/dist/failure_detector/failure_detector.cpp
src/dist/replication/lib/replica_stub.cpp

1. add module process_utils, and put process_start_time to it;
2. utitiy class "preloadable" is added for record the process start time

core: refactor utility

---

src/dist/replication/ddl_lib/replication_ddl_client.cpp

pegasus https://github.com/XiaoMi/pegasus/issues/199

restore_app: add table name validation

---

src/dist/replication/ddl_lib/replication_ddl_client.cpp

refer to https://github.com/XiaoMi/pegasus/issues/221

shell: improve ls command to statistics total counts

---

include/dsn/toollet/profiler.h
src/core/tools/common/profiler.cpp
src/core/tools/common/profiler_command.cpp
src/core/tools/common/profiler_header.h
src/core/tools/common/profiler_output.cpp

fix [Pegasus#320](https://github.com/XiaoMi/pegasus/issues/320)
refer [Pegasus#323](https://github.com/XiaoMi/pegasus/issues/323)

maintenance: record p99 rpc byte size

---

src/dist/nfs/nfs_client_impl.cpp
src/dist/nfs/nfs_client_impl.h
src/dist/nfs/nfs_node_impl.cpp
src/dist/nfs/nfs_node_simple.h
src/dist/nfs/nfs_server.h
src/dist/nfs/nfs_server_impl.cpp
src/dist/nfs/nfs_server_impl.h

Use `flags.h` to load the config

refactor: use flag api to load the config in nfs module

---

include/dsn/tool-api/logging_provider.h
include/dsn/tool_api.h
src/core/core/coredump.posix.cpp
src/core/core/logging.cpp
src/core/core/service_api_c.cpp
src/core/core/tool_api.cpp
src/core/tools/common/providers.common.cpp

1. use DSN_REGISTER_COMPONENT_PROVIDER to register simple_logger and screen_logger
2. some small refactor for optimization

refactor: use DSN_REGISTER_COMPONENT_PROVIDER to register logger

---

src/meta/greedy_load_balancer.cpp
src/meta/server_state.cpp

This pull request add a check for load balance, apps who are executing bulk load should not be balanced.

feat(bulk-load): ignore bulk loading app while load balance

---

src/nfs/nfs_client_impl.cpp

When update the `max_copy_rate_megabytes` via remote-command, the DEFAULT value will be changed. This PR add `current_max_copy_rate_megabytes` store the latest value and let the `FLAGS_max_copy_rate_megabytes` store the default value.

fix: remote-command max_copy_rate_megabytes failed when set "DEFAULT"

---

src/runtime/security/client_negotiation.cpp
src/runtime/security/client_negotiation.h
src/runtime/security/sasl_client_wrapper.cpp
src/runtime/test/client_negotiation_test.cpp

client_negotiation handle challenge which is sent from server_negotiation
```
negotiation process:
client                             server
|---   SASL_LIST_MECHANISMS    -->|
|<-- SASL_LIST_MECHANISMS_RESP ---|
|---  SASL_SELECT_MECHANISMS  --->|
|<-- SASL_SELECT_MECHANISMS_OK ---|
|                                 |
|------    SASL_INITIATE   ------>|
|                                 |
|<----     SASL_CHALLENGE    -----|
|-----      SASL_RESPONSE    ---->|
|                                 |
|              .....              |
|                                 |
|<----     SASL_CHALLENGE    -----|
|-----      SASL_RESPONSE    ---->|
|                                 |        (authentication will succeed
|                                 |        if all chanllenges passed)
| <--- …
```

feat(security): client_negotiation handle challenge

---

src/meta/meta_bulk_load_service.h
src/meta/meta_http_service.cpp
src/meta/meta_http_service.h
src/meta/test/meta_http_service_test.cpp

This pull request adds a new http interface for meta server to query bulk load.

feat(bulk-load): add query bulk load http interface

---

include/dsn/dist/replication/replication_app_base.h
src/replica/replica.cpp
src/replica/replica.h
src/replica/replica_http_service.cpp
src/replica/replica_http_service.h
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/storage/simple_kv/simple_kv.server.impl.h
src/replica/storage/simple_kv/test/simple_kv.server.impl.h
src/replica/test/mock_utils.h
src/replica/test/replica_test.cpp

This pr adds http interface to query app data_version by app_id.

feat: add query app data_version

---

src/meta/meta_backup_service.h
src/meta/meta_service.h
src/meta/server_state.h
src/meta/test/backup_test.cpp
src/meta/test/main.cpp
src/meta/test/meta_service_test_app.h

This patch doesn't contain functional changes.

refactor: refactor backup_test

---

.github/workflows/pull_request.yaml
src/meta/meta_backup_service.cpp

Action for checking out a repo: https://github.com/actions/checkout

fix: fix compilation errors

---

src/replica/replica_stub.cpp

Fix the daily compilation error, https://github.com/XiaoMi/rdsn/runs/2658613923?check_suite_focus=true
This bug is introduced by https://github.com/XiaoMi/rdsn/pull/832

fix: fix a compile error on clang

---

src/meta/greedy_load_balancer.cpp
src/meta/greedy_load_balancer.h

add remote command to enable cluster load balance. I will add the implementation of cluster load balance in later pull requests.

feat: add flag to enable cluster load balance

---

src/meta/greedy_load_balancer.cpp
src/meta/greedy_load_balancer.h

implement move primary for cluster load balancer

feat: implement move primary for cluster load balancer

---

src/meta/greedy_load_balancer.cpp
src/meta/greedy_load_balancer.h
src/meta/test/greedy_load_balancer_test.cpp

add the implementation of `greedy_load_balancer::pick_up_partition`. And add the corresponding unit test

feat: implement greedy_load_balancer::pick_up_partition

---

src/meta/greedy_load_balancer.cpp
src/meta/greedy_load_balancer.h

add class `ford_fulkerson` used for primary load balance

refactor: add class ford_fulkerson

---

src/meta/meta_bulk_load_service.cpp
src/meta/meta_bulk_load_service.h

This pull request adds `get_app` function for class bulk_load_service

refactor(bulk_load): refactor get_app for bulk_load_service

---

src/replica/mutation_log.cpp

Related issue: https://github.com/apache/incubator-pegasus/issues/859

feat: add tracer point in plog

---

src/replica/mutation_log.cpp

Related issue: apache/incubator-pegasus#859

feat: support callback for plog append

---

src/replica/mutation_log.cpp

[replication]
plog_force_flush = false

feat: add force flush option for private log

---

src/common/replication_common.cpp
src/common/replication_common.h
src/replica/duplication/test/load_from_private_log_test.cpp
src/replica/duplication/test/replica_duplicator_test.cpp
src/replica/mutation_log.cpp
src/replica/mutation_log.h
src/replica/replica_init.cpp
src/replica/test/mock_utils.h
src/replica/test/mutation_log_learn_test.cpp
src/replica/test/mutation_log_test.cpp

Remove unused options in privated log,  making it like shared_log

feat: remove unused options in privated log

---

.github/workflows/issue_ref.yaml

see issue https://github.com/apache/incubator-pegasus/issues/869
ci passed need you add issue ref like above URL later

build: require add issue reference in description using github action

---

include/dsn/dist/replication/replication_app_base.h
src/replica/replica.h
src/replica/replica_init.cpp
src/replica/replication_app_base.cpp
src/replica/test/replica_disk_migrate_test.cpp

related issue:
[apache/incubator-pegasus#876](https://github.com/apache/incubator-pegasus/issues/876)

refactor: remove deprecated replica .info file

---

.github/workflows/pull_request.yaml
src/replica/duplication/test/load_from_private_log_test.cpp
src/utils/test/latency_tracer_test.cpp

https://github.com/apache/incubator-pegasus/issues/859

fix: stack overflow in duplication test

---

src/meta/meta_bulk_load_service.cpp
src/meta/meta_bulk_load_service.h
src/meta/test/meta_bulk_load_service_test.cpp

As https://github.com/apache/incubator-pegasus/issues/886 and #1035 shows, we plan to provide a disk-level concurrent ingesting count restriction. This pull request adds ingesting count check for meta bulk load process.
Configuration changed:
```diff
[meta_server]
- bulk_load_ingestion_concurrent_count = 4
```

feat(bulk_load): support disk_level ingesting restriction part2 implementation

---

include/dsn/dist/replication/duplication_common.h
src/common/duplication.thrift
src/meta/duplication/duplication_info.cpp
src/meta/duplication/duplication_info.h
src/meta/duplication/meta_duplication_service.cpp
src/meta/duplication/meta_duplication_service.h
src/meta/test/duplication_info_test.cpp
src/meta/test/meta_duplication_service_test.cpp
src/replica/duplication/replica_duplicator.cpp
src/replica/duplication/replica_duplicator.h
src/replica/duplication/replica_duplicator_manager.cpp
src/replica/duplication/test/replica_duplicator_test.cpp
src/replica/duplication/test/ship_mutation_test.cpp

This PR refactor `DS_START` to three stage: `DS_PREPARE`, `DS_APP`, `DS_LOG`, and update the status transfer logic

feat(dup_enhancement#1): add new dup status to support new dup  

---

src/meta/meta_data.h
src/meta/meta_split_service.cpp
src/meta/server_state.cpp

https://github.com/apache/incubator-pegasus/issues/908

refactor: drop redundant config_status::pending_proposal

---

src/aio/test/aio.cpp
src/http/http_message_parser.cpp
src/meta/meta_state_service_simple.h
src/replica/log_file.cpp
src/runtime/rpc/thrift_message_parser.cpp

https://github.com/apache/incubator-pegasus/issues/887

refactor: use the corrent cast operation

---

include/dsn/dist/replication/duplication_common.h
src/common/duplication_common.cpp
src/replica/duplication/replica_follower.cpp
src/replica/duplication/test/replica_follower_test.cpp
src/replica/replication_app_base.cpp

fix(dup_enhancement#15): follower replica add `duplciation_dir` in `replica_app_base`

---

include/dsn/dist/replication/replica_test_utils.h
include/dsn/dist/replication/replication_app_base.h
src/replica/replica_test_utils.cpp

Pegasus unit test code need virtual to mock these function

fix(dup_enhancement#16): change some `replica_app_base` function to virtual for polymorphism

---

include/dsn/perf_counter/perf_counters.h
include/dsn/utility/singleton.h
src/block_service/block_service_manager.h
src/common/duplication_common.cpp
src/http/http_call_registry.h
src/meta/app_env_validator.h
src/runtime/rpc/message_parser_manager.h
src/runtime/scheduler.h
src/runtime/security/kinit_context.cpp
src/runtime/security/negotiation_manager.h
src/runtime/service_engine.h
src/utils/flags.cpp
src/utils/shared_io_service.h
src/zookeeper/zookeeper_session_mgr.h

make ctor functions of singleton to be private, to avoid creating more than one object for singleton classes
https://github.com/apache/incubator-pegasus/issues/887

refactor: make ctor/dtor function of singleton classes to be private

---

include/dsn/utility/metrics.h
src/utils/metrics.cpp
src/utils/test/metrics_test.cpp

https://github.com/apache/incubator-pegasus/issues/925

feat(new_metrics): implement the metric entity & its prototype

---

include/dsn/utility/metrics.h
src/utils/metrics.cpp
src/utils/test/metrics_test.cpp

https://github.com/apache/incubator-pegasus/issues/927

feat(new_metrics): implement the metric registry

---

src/common/fs_manager.h
src/replica/replica.h
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/storage/simple_kv/test/case-207.act
src/replica/storage/simple_kv/test/case-208.act
src/replica/storage/simple_kv/test/case-209.act
src/replica/test/mock_utils.h
src/replica/test/open_replica_test.cpp

Related issue:
https://github.com/apache/incubator-pegasus/issues/895

fix: add a decree check when replica server receive the assign_primary request (#895)

---

include/dsn/utility/metrics.h
src/utils/test/metrics_test.cpp

https://github.com/apache/incubator-pegasus/issues/929

feat(new_metrics): implement the gauge

---

include/dsn/dist/replication/replication_ddl_client.h
src/client/replication_ddl_client.cpp
src/common/duplication.thrift
src/meta/test/meta_duplication_service_test.cpp

refactor(dup_enhancement#22): delete useless `freezed` argument

---

include/dsn/dist/replication/replication_ddl_client.h
src/client/replication_ddl_client.cpp
src/common/duplication.thrift
src/meta/duplication/duplication_info.h
src/meta/duplication/meta_duplication_service.cpp
src/meta/test/duplication_info_test.cpp

feat(dup_enhancement#25): add `-s | --sst` argument to support ignoring checkpoint when duplicate

---

include/dsn/dist/replication/replica_envs.h
src/common/replication_common.cpp
src/meta/server_state.cpp
src/meta/server_state.h
src/meta/test/meta_app_operation_test.cpp

https://github.com/apache/incubator-pegasus/issues/865

feat(update_replication_factor#4): support to set env for the replication factor

---

include/dsn/utility/metrics.h
src/utils/test/metrics_test.cpp

https://github.com/apache/incubator-pegasus/issues/933

feat(new_metrics): implement the volatile counter

---

src/meta/duplication/duplication_info.h
src/replica/test/mock_utils.h
src/replica/test/replica_test_base.h

issue: https://github.com/apache/incubator-pegasus/issues/959

fix: Fix build error when build by clang

---

src/replica/replica.h
src/replica/replica_config.cpp
src/replica/test/replica_test.cpp

https://github.com/apache/incubator-pegasus/issues/865

feat(update_replication_factor#6): sync max_replica_count from meta server into .app-info file for each replica

---

.licenserc.yaml
LICENSE

https://github.com/apache/incubator-pegasus/issues/823
https://github.com/apache/incubator-pegasus/issues/945

chore: Add license declaration to LICENSE file
